import { useEffect, useState } from 'react';
import type { AppSettings, AppSettingsStatus, R2ConnectionInput, R2ConnectionStatus } from '../../shared/types';
import type { Runner } from '../ui';

const EMPTY_R2:R2ConnectionInput={name:'Personal R2',accountId:'',accessKeyId:'',secretAccessKey:'',publicUrl:'',cloudflareApiToken:''};
function appSettingsInput(s:AppSettingsStatus):AppSettings{return {comfyUiInstallPath:s.comfyUiInstallPath,catalogPath:s.catalogPath,r2Bucket:s.r2Bucket,r2ModelPrefix:s.r2ModelPrefix,r2IndexPath:s.r2IndexPath,templatePath:s.templatePath,manifestPath:s.manifestPath};}

export function R2IntegrationPanel({run,onBack,onOpenManager,onStatus}:{run:Runner;onBack:()=>void;onOpenManager:()=>void;onStatus:(s:R2ConnectionStatus)=>void}){
  const [input,setInput]=useState<R2ConnectionInput>(EMPTY_R2),[status,setStatus]=useState<R2ConnectionStatus|null>(null),[appSettings,setAppSettings]=useState<AppSettingsStatus|null>(null);
  useEffect(()=>{let cancelled=false;void Promise.all([window.batchStudio.r2.settings(),window.batchStudio.appSettings.get()]).then(([s,a])=>{if(cancelled)return;setStatus(s);onStatus(s);setAppSettings(a);setInput({name:s.name||'Personal R2',accountId:s.accountId,accessKeyId:s.accessKeyId,secretAccessKey:'',publicUrl:s.publicUrl,cloudflareApiToken:''});}).catch(()=>{});return()=>{cancelled=true};},[]);
  const set=(key:keyof R2ConnectionInput,value:string)=>setInput(prev=>({...prev,[key]:value}));
  const save=()=>run(async()=>{const next=await window.batchStudio.r2.saveSettings(input);setStatus(next);onStatus(next);if(appSettings){const updated=await window.batchStudio.appSettings.save({...appSettingsInput(appSettings),r2Bucket:appSettings.r2Bucket,r2ModelPrefix:appSettings.r2ModelPrefix});setAppSettings(updated);}});
  return <section className="panel service-page"><div className="service-page-head"><button onClick={onBack}>← サービス連携</button><div><h3>Cloudflare R2</h3><p>モデル保管とリモート成果物転送で使用する接続設定です。SecretはOSの安全な暗号化ストレージで保護します。</p></div><b className={status?.configured||status?.secretConfigured?'ok':'muted'}>{status?.configured?'設定済み':status?.secretConfigured?'環境変数を使用':'未設定'}</b></div><div className="formgrid service-form">
    <label>接続名<input value={input.name??''} onChange={e=>set('name',e.target.value)}/></label><label><span>Account ID <code>R2_ACCOUNT_ID</code></span><input value={input.accountId} onChange={e=>set('accountId',e.target.value)}/></label><label><span>Access Key ID <code>R2_ACCESS_KEY</code></span><input value={input.accessKeyId} onChange={e=>set('accessKeyId',e.target.value)}/></label><label><span>Secret Access Key <code>R2_SECRET_ACCESS_KEY</code></span><input type="password" value={input.secretAccessKey??''} onChange={e=>set('secretAccessKey',e.target.value)} placeholder={status?.secretConfigured?'保存済み / 環境変数（変更時のみ入力）':'Secret Access Key'}/></label><label className="wide"><span>Public URL（任意） <code>R2_PUBLIC_URL</code></span><input value={input.publicUrl??''} onChange={e=>set('publicUrl',e.target.value)} placeholder="https://..."/></label><label className="wide"><span>Cloudflare API Token（メトリクス用・任意） <code>CLOUDFLARE_API_TOKEN</code></span><input type="password" value={input.cloudflareApiToken??''} onChange={e=>set('cloudflareApiToken',e.target.value)} placeholder={status?.metricsTokenConfigured?'保存済み（変更時のみ入力）':'任意'}/></label>
    <label><span>デフォルトモデルバケット <code>BATCH_STUDIO_R2_BUCKET</code></span><input value={appSettings?.r2Bucket??''} onChange={e=>setAppSettings(prev=>prev?{...prev,r2Bucket:e.target.value}:prev)}/></label><label><span>モデルプレフィックス <code>BATCH_STUDIO_R2_MODEL_PREFIX</code></span><input value={appSettings?.r2ModelPrefix??''} onChange={e=>setAppSettings(prev=>prev?{...prev,r2ModelPrefix:e.target.value}:prev)} placeholder="例: models"/></label>
  </div><div className="actions service-actions"><button onClick={()=>void run(()=>window.batchStudio.r2.test(input))}>接続テスト</button><button className="primary" onClick={()=>void save()}>保存</button><button onClick={onOpenManager}>R2 File Managerを開く</button></div></section>;
}
