import { useEffect, useMemo, useState } from 'react';
import type { VastAiConnectionInput, VastAiConnectionStatus, VastAiInstance } from '../../shared/types';
import type { Runner } from '../ui';

const EMPTY_VAST:VastAiConnectionInput={apiKey:'',sshPrivateKeyPath:'',sshUser:'root',comfyUiDirectory:'/workspace/ComfyUI',comfyUiPort:18188};
function statusLabel(status:VastAiConnectionStatus|null){if(!status?.configured)return'未設定';return status.source==='environment'?'環境変数を使用':'設定済み';}
function instanceStatusLabel(status:VastAiInstance['status']){return ({running:'RUNNING',stopped:'STOPPED',starting:'STARTING',scheduling:'SCHEDULING',stopping:'STOPPING',offline:'OFFLINE',error:'ERROR',unknown:'UNKNOWN'} as const)[status];}
function formatCost(value:number|null){return value==null?'-':`$${value.toFixed(3)}/h`;}
function formatVram(value:number|null){return value==null?'-':`${Math.round(value/1024)} GB`;}

export function VastAiIntegrationPanel({run,onBack,onStatus}:{run:Runner;onBack:()=>void;onStatus:(s:VastAiConnectionStatus)=>void}){
  const [status,setStatus]=useState<VastAiConnectionStatus|null>(null),[input,setInput]=useState<VastAiConnectionInput>(EMPTY_VAST),[instances,setInstances]=useState<VastAiInstance[]>([]),[loadingInstances,setLoadingInstances]=useState(false);
  const configured=Boolean(status?.configured);
  const loadInstances=async()=>{setLoadingInstances(true);try{setInstances(await window.batchStudio.vastai.instances());}finally{setLoadingInstances(false);}};
  const load=async()=>{const s=await window.batchStudio.vastai.settings();setStatus(s);onStatus(s);setInput({apiKey:'',sshPrivateKeyPath:s.sshPrivateKeyPath,sshUser:s.sshUser,comfyUiDirectory:s.comfyUiDirectory,comfyUiPort:s.comfyUiPort});if(s.configured)await loadInstances();};
  useEffect(()=>{void load().catch(()=>{});},[]);
  const set=(key:keyof VastAiConnectionInput,value:string|number|undefined)=>setInput(prev=>({...prev,[key]:value}));
  const save=()=>run(async()=>{const next=await window.batchStudio.vastai.saveSettings(input);setStatus(next);onStatus(next);setInput(prev=>({...prev,apiKey:''}));await loadInstances();});
  const chooseKey=()=>run(async()=>{const selected=await window.batchStudio.vastai.selectPrivateKey();if(selected)set('sshPrivateKeyPath',selected);});
  const changeState=(instance:VastAiInstance,next:'start'|'stop')=>run(async()=>{if(next==='start')await window.batchStudio.vastai.startInstance(instance.id);else await window.batchStudio.vastai.stopInstance(instance.id);await loadInstances();});
  const sorted=useMemo(()=>instances.slice().sort((a,b)=>Number(b.status==='running')-Number(a.status==='running')||b.id-a.id),[instances]);
  return <section className="panel service-page"><div className="service-page-head"><button onClick={onBack}>← クラウドインスタンス</button><div><h3>Vast.ai</h3><p>Vast.ai APIと、リモートComfyUIへ接続するためのSSH既定値を管理します。</p></div><b className={configured?'ok':'muted'}>{statusLabel(status)}</b></div>
    <div className="formgrid service-form"><label className="wide">Vast.ai API Key<input type="password" value={input.apiKey??''} onChange={e=>set('apiKey',e.target.value)} placeholder={configured?'設定済み（変更時のみ入力）':'API Keyを入力'}/></label><label className="wide">SSH秘密鍵<div className="actions"><input style={{flex:1}} value={input.sshPrivateKeyPath??''} readOnly placeholder="秘密鍵ファイルを選択"/><button onClick={()=>void chooseKey()}>選択</button><button disabled={!input.sshPrivateKeyPath} onClick={()=>set('sshPrivateKeyPath','')}>解除</button></div></label><label>SSH User<input value={input.sshUser??''} onChange={e=>set('sshUser',e.target.value)} placeholder="root"/></label><label>ComfyUI Port<input type="number" min={1} max={65535} value={input.comfyUiPort??18188} onChange={e=>set('comfyUiPort',Number(e.target.value))}/></label><label className="wide">Remote ComfyUI Directory<input value={input.comfyUiDirectory??''} onChange={e=>set('comfyUiDirectory',e.target.value)} placeholder="/workspace/ComfyUI"/></label></div>
    <p className="hint">API Key環境変数: <code>VASTAI_API_KEY</code>。SSHは公開Host/Port + 秘密鍵認証を前提とし、SSH Tunnelは使用しません。</p><div className="actions service-actions"><button disabled={!configured&&!input.apiKey?.trim()} onClick={()=>void run(()=>window.batchStudio.vastai.test(input))}>API接続テスト</button><button className="primary" disabled={!configured&&!input.apiKey?.trim()} onClick={()=>void save()}>保存</button></div>
    <div className="service-subsection"><div className="panelhead"><div><h4>インスタンス</h4><p>既存Instanceの状態確認・起動・停止を行います。新規作成・Destroy・Rebootはこの初期実装の対象外です。</p></div><button disabled={!configured||loadingInstances} onClick={()=>void run(loadInstances)}>{loadingInstances?'更新中…':'更新'}</button></div>{configured&&sorted.length===0&&!loadingInstances&&<p className="hint">Vast.ai Instanceがありません。</p>}{sorted.length>0&&<div className="vast-instance-table"><div className="vast-instance-row vast-instance-head"><span>ID / Label</span><span>GPU</span><span>Status</span><span>Cost</span><span>SSH</span><span>操作</span></div>{sorted.map(instance=><div className="vast-instance-row" key={instance.id}><span><b>#{instance.id}</b><small>{instance.label||'ラベルなし'}</small></span><span>{instance.gpuName??'-'}<small>{instance.gpuCount??'-'} GPU / {formatVram(instance.gpuRamMb)}</small></span><span><b className={`vast-status vast-status-${instance.status}`}>{instanceStatusLabel(instance.status)}</b><small>{instance.statusMessage??instance.rawStatus}</small></span><span>{formatCost(instance.hourlyCost)}</span><span>{instance.sshHost&&instance.sshPort?<code>{instance.sshHost}:{instance.sshPort}</code>:'-'}</span><span className="actions">{instance.status==='running'?<button onClick={()=>void changeState(instance,'stop')}>停止</button>:instance.status==='stopped'?<button onClick={()=>void changeState(instance,'start')}>起動</button>:<button disabled>操作待ち</button>}</span></div>)}</div>}</div>
  </section>;
}
