const { contextBridge, ipcRenderer } = require('electron');
const I = {
  APP_SETTINGS_GET: 'app-settings:get',
  APP_SETTINGS_SELECT_COMFYUI: 'app-settings:select-comfyui',
  APP_SETTINGS_SAVE: 'app-settings:save',
  PROJECT_SELECT: 'project:select',
  PROJECT_LAST: 'project:last',
  PROJECT_RECENT: 'project:recent',
  PROJECT_REMOVE_RECENT: 'project:remove-recent',
  PROJECT_OPEN: 'project:open',
  PROJECT_CLOSE: 'project:close',
  PROJECT_SELECT_PARENT: 'project:select-parent',
  PROJECT_CREATE: 'project:create',
  PROJECT_MENU_COMMAND: 'project:menu-command',
  PROJECT_SCAN: 'project:scan',
  PROJECT_OPEN_FOLDER: 'project:open-folder',
  PROJECT_SAVE_SETTINGS: 'project:save-settings',
  PROJECT_SAVE_BRIEF: 'project:save-brief',
  ARTIFACT_READ: 'artifact:read',
  ARTIFACT_BEGIN_EDIT: 'artifact:begin-edit',
  ARTIFACT_SAVE_DRAFT: 'artifact:save-draft',
  ARTIFACT_IMPORT_GROK: 'artifact:import-grok',
  ARTIFACT_CONFIRM: 'artifact:confirm',
  ARTIFACT_GROK_LORA_HISTORY: 'artifact:grok-lora-history',
  ARTIFACT_RESET_FROM: 'artifact:reset-from',
  PROMPT_PLAN_SAVE: 'prompt-plan:save',
  GROK_TASK_BUILD: 'grok-task:build',
  FILE_SHOW_IN_FOLDER: 'file:show-in-folder',
  CATALOG_STATUS: 'catalog:status',
  CATALOG_INTEGRATED_STATUS: 'catalog:integrated-status',
  CATALOG_INTEGRATED_SNAPSHOT: 'catalog:integrated-snapshot',
  CATALOG_INTEGRATED_SYNC: 'catalog:integrated-sync',
  CATALOG_LINK_PROJECT: 'catalog:link-project',
  CATALOG_TEMPLATES: 'catalog:templates',
  CATALOG_SAVE_TEMPLATE: 'catalog:save-template',
  CATALOG_DELETE_TEMPLATE: 'catalog:delete-template',
  CATALOG_OPEN_MODEL: 'catalog:open-model',
  CIVITAI_SETTINGS: 'civitai:settings',
  CIVITAI_SAVE_SETTINGS: 'civitai:save-settings',
  VASTAI_SETTINGS: 'vastai:settings',
  VASTAI_SAVE_SETTINGS: 'vastai:save-settings',
  VASTAI_TEST: 'vastai:test',
  VASTAI_SELECT_PRIVATE_KEY: 'vastai:select-private-key',
  VASTAI_SELECT_PUBLIC_KEY: 'vastai:select-public-key',
  VASTAI_INSTANCES: 'vastai:instances',
  VASTAI_COMFYUI_TEMPLATE: 'vastai:comfyui-template',
  VASTAI_SEARCH_OFFERS: 'vastai:search-offers',
  VASTAI_RENT_OFFER: 'vastai:rent-offer',
  VASTAI_START_INSTANCE: 'vastai:start-instance',
  VASTAI_STOP_INSTANCE: 'vastai:stop-instance',
  VASTAI_DESTROY_INSTANCE: 'vastai:destroy-instance',
  VASTAI_REBOOT_INSTANCE: 'vastai:reboot-instance',
  VASTAI_RESOLVE_SSH: 'vastai:resolve-ssh',
  WORKFLOW_COMPILE: 'workflow:compile',
  AVAILABILITY_CHECK: 'availability:check',
  AVAILABILITY_CHECK_LORA_FILES: 'availability:check-lora-files',
  AVAILABILITY_OPEN_R2: 'availability:open-r2',
  PREFLIGHT_RUN: 'preflight:run',
  EXECUTION_START: 'execution:start',
  EXECUTION_STATUS: 'execution:status',
  EXECUTION_GET: 'execution:get',
  EXECUTION_STOP_SCHEDULING: 'execution:stop-scheduling',
  EXECUTION_FORCE_INTERRUPT: 'execution:force-interrupt',
  EXECUTION_RESUME: 'execution:resume',
  EXECUTION_RESTART_REMOTE: 'execution:restart-remote',
  EXECUTION_RESTART_FROM_SCRATCH: 'execution:restart-from-scratch',
  FINAL_ARTIFACT_STATUS: 'final-artifact:status',
  FINAL_ARTIFACT_SELECT_DIRECTORY: 'final-artifact:select-directory',
  CAPTION_STATUS: 'caption:status',
  CAPTION_SELECT_SOURCE_DIRECTORY: 'caption:select-source-directory',
  CAPTION_IMPORT_GROK: 'caption:import-grok',
  CAPTION_GENERATE: 'caption:generate',
  THUMBNAIL_FONTS: 'thumbnail:fonts',
  THUMBNAIL_LOAD: 'thumbnail:load',
  THUMBNAIL_SAVE: 'thumbnail:save',
  THUMBNAIL_SELECT_IMAGE: 'thumbnail:select-image',
  THUMBNAIL_LIST_IMAGES: 'thumbnail:list-images',
  THUMBNAIL_READ_IMAGE: 'thumbnail:read-image',
  THUMBNAIL_READ_PREVIEW: 'thumbnail:read-preview',
  THUMBNAIL_READ_TEMPLATE: 'thumbnail:read-template',
  THUMBNAIL_EXPORT: 'thumbnail:export',
  THUMBNAIL_PICKER_OPEN: 'thumbnail-picker:open',
  THUMBNAIL_PICKER_CONTEXT: 'thumbnail-picker:context',
  THUMBNAIL_PICKER_PREVIEW: 'thumbnail-picker:preview',
  THUMBNAIL_PICKER_COMMIT: 'thumbnail-picker:commit',
  THUMBNAIL_PICKER_PREVIEWED: 'thumbnail-picker:previewed',
  THUMBNAIL_PICKER_COMMITTED: 'thumbnail-picker:committed',
  THUMBNAIL_PICKER_CANCELLED: 'thumbnail-picker:cancelled',
  R2_SETTINGS: 'r2:settings',
  R2_ENVIRONMENT: 'r2:environment',
  R2_TEST: 'r2:test',
  R2_SAVE_SETTINGS: 'r2:save-settings',
  R2_BUCKETS: 'r2:buckets',
  R2_CREATE_BUCKET: 'r2:create-bucket',
  R2_DELETE_BUCKET: 'r2:delete-bucket',
  R2_LIST: 'r2:list',
  R2_SEARCH: 'r2:search',
  R2_DOWNLOAD_INFO: 'r2:download-info',
  R2_BATCH_DOWNLOAD_INFO: 'r2:batch-download-info',
  R2_PUT_URL_INFO: 'r2:put-url-info',
  R2_DELETE_OBJECTS: 'r2:delete-objects',
  R2_MOVE: 'r2:move',
  R2_SELECT_UPLOAD_FILES: 'r2:select-upload-files',
  R2_BEGIN_UPLOAD: 'r2:begin-upload',
  R2_UPLOADS: 'r2:uploads',
  R2_RESUME_UPLOAD: 'r2:resume-upload',
  R2_PAUSE_UPLOAD: 'r2:pause-upload',
  R2_CANCEL_UPLOAD: 'r2:cancel-upload',
  R2_TEMPLATES: 'r2:templates',
  R2_SAVE_TEMPLATE: 'r2:save-template',
  R2_DELETE_TEMPLATE: 'r2:delete-template',
  R2_METRICS: 'r2:metrics',
  CLIPBOARD_WRITE_TEXT: 'clipboard:write-text',
  GROK_SET_VISIBLE: 'grok:set-visible',
  GROK_SET_CONTEXT: 'grok:set-context',
  GROK_SET_RATIO: 'grok:set-ratio',
  GROK_SET_DIVIDER_X: 'grok:set-divider-x',
  GROK_RELOAD: 'grok:reload',
  GROK_OPEN_EXTERNAL: 'grok:open-external',
};
contextBridge.exposeInMainWorld('batchStudio', {
  appSettings: {
    get: () => ipcRenderer.invoke(I.APP_SETTINGS_GET),
    selectComfyUiDirectory: () => ipcRenderer.invoke(I.APP_SETTINGS_SELECT_COMFYUI),
    save: (s) => ipcRenderer.invoke(I.APP_SETTINGS_SAVE, s),
  },
  project: {
    select: () => ipcRenderer.invoke(I.PROJECT_SELECT),
    last: () => ipcRenderer.invoke(I.PROJECT_LAST),
    recent: () => ipcRenderer.invoke(I.PROJECT_RECENT),
    removeRecent: (r) => ipcRenderer.invoke(I.PROJECT_REMOVE_RECENT, r),
    open: (r) => ipcRenderer.invoke(I.PROJECT_OPEN, r),
    close: () => ipcRenderer.invoke(I.PROJECT_CLOSE),
    selectParent: (defaultPath) => ipcRenderer.invoke(I.PROJECT_SELECT_PARENT, defaultPath),
    create: (p, b) => ipcRenderer.invoke(I.PROJECT_CREATE, p, b),
    onMenuCommand: (listener) => {
      const handler = (_event, command, project) => listener(command, project);
      ipcRenderer.on(I.PROJECT_MENU_COMMAND, handler);
      return () => ipcRenderer.removeListener(I.PROJECT_MENU_COMMAND, handler);
    },
    scan: (r) => ipcRenderer.invoke(I.PROJECT_SCAN, r),
    openFolder: (r) => ipcRenderer.invoke(I.PROJECT_OPEN_FOLDER, r),
    saveSettings: (r, s) => ipcRenderer.invoke(I.PROJECT_SAVE_SETTINGS, r, s),
    saveBrief: (r, b) => ipcRenderer.invoke(I.PROJECT_SAVE_BRIEF, r, b),
  },
  artifact: {
    read: (r, k, s) => ipcRenderer.invoke(I.ARTIFACT_READ, r, k, s),
    beginEdit: (r, k) => ipcRenderer.invoke(I.ARTIFACT_BEGIN_EDIT, r, k),
    saveDraft: (r, k, c) => ipcRenderer.invoke(I.ARTIFACT_SAVE_DRAFT, r, k, c),
    importGrok: (r, k, x, s) => ipcRenderer.invoke(I.ARTIFACT_IMPORT_GROK, r, k, x, s),
    confirm: (r, k) => ipcRenderer.invoke(I.ARTIFACT_CONFIRM, r, k),
    savePromptPlan: (r, p) => ipcRenderer.invoke(I.PROMPT_PLAN_SAVE, r, p),
    grokLoraHistory: (r) => ipcRenderer.invoke(I.ARTIFACT_GROK_LORA_HISTORY, r),
    resetFrom: (r, s) => ipcRenderer.invoke(I.ARTIFACT_RESET_FROM, r, s),
  },
  grokTask: { build: (r, s, e) => ipcRenderer.invoke(I.GROK_TASK_BUILD, r, s, e) },
  file: { showInFolder: (p) => ipcRenderer.invoke(I.FILE_SHOW_IN_FOLDER, p) },
  catalog: {
    status: (r) => ipcRenderer.invoke(I.CATALOG_STATUS, r),
    integratedStatus: () => ipcRenderer.invoke(I.CATALOG_INTEGRATED_STATUS),
    snapshot: () => ipcRenderer.invoke(I.CATALOG_INTEGRATED_SNAPSHOT),
    sync: () => ipcRenderer.invoke(I.CATALOG_INTEGRATED_SYNC),
    linkProject: (r) => ipcRenderer.invoke(I.CATALOG_LINK_PROJECT, r),
    templates: () => ipcRenderer.invoke(I.CATALOG_TEMPLATES),
    saveTemplate: (i) => ipcRenderer.invoke(I.CATALOG_SAVE_TEMPLATE, i),
    deleteTemplate: (id) => ipcRenderer.invoke(I.CATALOG_DELETE_TEMPLATE, id),
    openModel: (u) => ipcRenderer.invoke(I.CATALOG_OPEN_MODEL, u),
  },
  civitai: {
    settings: () => ipcRenderer.invoke(I.CIVITAI_SETTINGS),
    saveSettings: (i) => ipcRenderer.invoke(I.CIVITAI_SAVE_SETTINGS, i),
  },
  vastai: {
    settings: () => ipcRenderer.invoke(I.VASTAI_SETTINGS),
    saveSettings: (i) => ipcRenderer.invoke(I.VASTAI_SAVE_SETTINGS, i),
    test: (i) => ipcRenderer.invoke(I.VASTAI_TEST, i),
    selectPrivateKey: () => ipcRenderer.invoke(I.VASTAI_SELECT_PRIVATE_KEY),
    selectPublicKey: () => ipcRenderer.invoke(I.VASTAI_SELECT_PUBLIC_KEY),
    instances: () => ipcRenderer.invoke(I.VASTAI_INSTANCES),
    comfyUiTemplate: () => ipcRenderer.invoke(I.VASTAI_COMFYUI_TEMPLATE),
    searchOffers: (i) => ipcRenderer.invoke(I.VASTAI_SEARCH_OFFERS, i),
    rentOffer: (i) => ipcRenderer.invoke(I.VASTAI_RENT_OFFER, i),
    startInstance: (id) => ipcRenderer.invoke(I.VASTAI_START_INSTANCE, id),
    stopInstance: (id) => ipcRenderer.invoke(I.VASTAI_STOP_INSTANCE, id),
    destroyInstance: (id) => ipcRenderer.invoke(I.VASTAI_DESTROY_INSTANCE, id),
    rebootInstance: (id) => ipcRenderer.invoke(I.VASTAI_REBOOT_INSTANCE, id),
    resolveSshEndpoint: (id) => ipcRenderer.invoke(I.VASTAI_RESOLVE_SSH, id),
  },
  workflow: { compile: (r) => ipcRenderer.invoke(I.WORKFLOW_COMPILE, r) },
  availability: {
    check: (r) => ipcRenderer.invoke(I.AVAILABILITY_CHECK, r),
    checkLoraFiles: (r, f) => ipcRenderer.invoke(I.AVAILABILITY_CHECK_LORA_FILES, r, f),
    openR2: (r) => ipcRenderer.invoke(I.AVAILABILITY_OPEN_R2, r),
  },
  preflight: { run: (r) => ipcRenderer.invoke(I.PREFLIGHT_RUN, r) },
  execution: {
    start: (r) => ipcRenderer.invoke(I.EXECUTION_START, r),
    status: (r) => ipcRenderer.invoke(I.EXECUTION_STATUS, r),
    get: (r, id) => ipcRenderer.invoke(I.EXECUTION_GET, r, id),
    stopScheduling: (r, id) => ipcRenderer.invoke(I.EXECUTION_STOP_SCHEDULING, r, id),
    forceInterrupt: (r, id) => ipcRenderer.invoke(I.EXECUTION_FORCE_INTERRUPT, r, id),
    resume: (r, id) => ipcRenderer.invoke(I.EXECUTION_RESUME, r, id),
    restartRemote: (r, id) => ipcRenderer.invoke(I.EXECUTION_RESTART_REMOTE, r, id),
    restartFromScratch: (r, id) => ipcRenderer.invoke(I.EXECUTION_RESTART_FROM_SCRATCH, r, id),
  },
  finalArtifact: {
    status: (r) => ipcRenderer.invoke(I.FINAL_ARTIFACT_STATUS, r),
    selectDirectory: (r) => ipcRenderer.invoke(I.FINAL_ARTIFACT_SELECT_DIRECTORY, r),
  },
  caption: {
    status: (r) => ipcRenderer.invoke(I.CAPTION_STATUS, r),
    selectSourceDirectory: (r) => ipcRenderer.invoke(I.CAPTION_SELECT_SOURCE_DIRECTORY, r),
    importGrok: (r, x) => ipcRenderer.invoke(I.CAPTION_IMPORT_GROK, r, x),
    generate: (r) => ipcRenderer.invoke(I.CAPTION_GENERATE, r),
  },
  thumbnail: {
    fonts: () => ipcRenderer.invoke(I.THUMBNAIL_FONTS),
    load: (r) => ipcRenderer.invoke(I.THUMBNAIL_LOAD, r),
    save: (r, s) => ipcRenderer.invoke(I.THUMBNAIL_SAVE, r, s),
    selectImage: (r) => ipcRenderer.invoke(I.THUMBNAIL_SELECT_IMAGE, r),
    listImages: (r) => ipcRenderer.invoke(I.THUMBNAIL_LIST_IMAGES, r),
    readImage: (p) => ipcRenderer.invoke(I.THUMBNAIL_READ_IMAGE, p),
    readPreview: (p) => ipcRenderer.invoke(I.THUMBNAIL_READ_PREVIEW, p),
    readTemplate: (p) => ipcRenderer.invoke(I.THUMBNAIL_READ_TEMPLATE, p),
    openPicker: (r, s, p) => ipcRenderer.invoke(I.THUMBNAIL_PICKER_OPEN, r, s, p),
    pickerContext: () => ipcRenderer.invoke(I.THUMBNAIL_PICKER_CONTEXT),
    previewPicker: (p) => ipcRenderer.invoke(I.THUMBNAIL_PICKER_PREVIEW, p),
    commitPicker: (p) => ipcRenderer.invoke(I.THUMBNAIL_PICKER_COMMIT, p),
    onPickerPreview: (listener) => {
      const handler = (_event, selection) => listener(selection);
      ipcRenderer.on(I.THUMBNAIL_PICKER_PREVIEWED, handler);
      return () => ipcRenderer.removeListener(I.THUMBNAIL_PICKER_PREVIEWED, handler);
    },
    onPickerCommit: (listener) => {
      const handler = (_event, selection) => listener(selection);
      ipcRenderer.on(I.THUMBNAIL_PICKER_COMMITTED, handler);
      return () => ipcRenderer.removeListener(I.THUMBNAIL_PICKER_COMMITTED, handler);
    },
    onPickerCancel: (listener) => {
      const handler = (_event, session) => listener(session);
      ipcRenderer.on(I.THUMBNAIL_PICKER_CANCELLED, handler);
      return () => ipcRenderer.removeListener(I.THUMBNAIL_PICKER_CANCELLED, handler);
    },
    exportImage: (r, i, f, d) => ipcRenderer.invoke(I.THUMBNAIL_EXPORT, r, i, f, d),
  },
  clipboard: { writeText: (t) => ipcRenderer.invoke(I.CLIPBOARD_WRITE_TEXT, t) },
  r2: {
    settings: () => ipcRenderer.invoke(I.R2_SETTINGS),
    environment: () => ipcRenderer.invoke(I.R2_ENVIRONMENT),
    test: (i) => ipcRenderer.invoke(I.R2_TEST, i),
    saveSettings: (i) => ipcRenderer.invoke(I.R2_SAVE_SETTINGS, i),
    buckets: () => ipcRenderer.invoke(I.R2_BUCKETS),
    createBucket: (n) => ipcRenderer.invoke(I.R2_CREATE_BUCKET, n),
    deleteBucket: (n) => ipcRenderer.invoke(I.R2_DELETE_BUCKET, n),
    list: (b, p, t) => ipcRenderer.invoke(I.R2_LIST, b, p, t),
    search: (b, q, t) => ipcRenderer.invoke(I.R2_SEARCH, b, q, t),
    downloadInfo: (b, k, e) => ipcRenderer.invoke(I.R2_DOWNLOAD_INFO, b, k, e),
    batchDownloadInfo: (b, k, e) => ipcRenderer.invoke(I.R2_BATCH_DOWNLOAD_INFO, b, k, e),
    putUrlInfo: (b, k, e, c) => ipcRenderer.invoke(I.R2_PUT_URL_INFO, b, k, e, c),
    deleteObjects: (b, k) => ipcRenderer.invoke(I.R2_DELETE_OBJECTS, b, k),
    move: (b, s, d, o) => ipcRenderer.invoke(I.R2_MOVE, b, s, d, o),
    selectUploadFiles: () => ipcRenderer.invoke(I.R2_SELECT_UPLOAD_FILES),
    beginUpload: (b, p, f, o) => ipcRenderer.invoke(I.R2_BEGIN_UPLOAD, b, p, f, o),
    uploads: () => ipcRenderer.invoke(I.R2_UPLOADS),
    resumeUpload: (id) => ipcRenderer.invoke(I.R2_RESUME_UPLOAD, id),
    pauseUpload: (id) => ipcRenderer.invoke(I.R2_PAUSE_UPLOAD, id),
    cancelUpload: (id) => ipcRenderer.invoke(I.R2_CANCEL_UPLOAD, id),
    templates: (b) => ipcRenderer.invoke(I.R2_TEMPLATES, b),
    saveTemplate: (i) => ipcRenderer.invoke(I.R2_SAVE_TEMPLATE, i),
    deleteTemplate: (id) => ipcRenderer.invoke(I.R2_DELETE_TEMPLATE, id),
    metrics: () => ipcRenderer.invoke(I.R2_METRICS),
  },
  grok: {
    setVisible: (v) => ipcRenderer.invoke(I.GROK_SET_VISIBLE, v),
    setContext: (r, s) => ipcRenderer.invoke(I.GROK_SET_CONTEXT, r, s),
    setRatio: (r) => ipcRenderer.invoke(I.GROK_SET_RATIO, r),
    setDividerScreenX: (x) => ipcRenderer.invoke(I.GROK_SET_DIVIDER_X, x),
    reload: () => ipcRenderer.invoke(I.GROK_RELOAD),
    openExternal: () => ipcRenderer.invoke(I.GROK_OPEN_EXTERNAL),
  },
});
