export const IPC = {
  APP_SETTINGS_GET:'app-settings:get', APP_SETTINGS_SELECT_COMFYUI:'app-settings:select-comfyui', APP_SETTINGS_SAVE:'app-settings:save',
  PROJECT_SELECT:'project:select', PROJECT_LAST:'project:last', PROJECT_RECENT:'project:recent', PROJECT_REMOVE_RECENT:'project:remove-recent', PROJECT_OPEN:'project:open', PROJECT_CLOSE:'project:close', PROJECT_SELECT_PARENT:'project:select-parent', PROJECT_CREATE:'project:create', PROJECT_SCAN:'project:scan', PROJECT_OPEN_FOLDER:'project:open-folder', PROJECT_SAVE_SETTINGS:'project:save-settings', PROJECT_SAVE_BRIEF:'project:save-brief',
  ARTIFACT_READ:'artifact:read', ARTIFACT_BEGIN_EDIT:'artifact:begin-edit', ARTIFACT_SAVE_DRAFT:'artifact:save-draft', ARTIFACT_IMPORT_GROK:'artifact:import-grok', ARTIFACT_CONFIRM:'artifact:confirm', ARTIFACT_GROK_LORA_HISTORY:'artifact:grok-lora-history', ARTIFACT_RESET_FROM:'artifact:reset-from', PROMPT_PLAN_SAVE:'prompt-plan:save',
  GROK_TASK_BUILD:'grok-task:build', FILE_SHOW_IN_FOLDER:'file:show-in-folder', CATALOG_STATUS:'catalog:status', CATALOG_INTEGRATED_STATUS:'catalog:integrated-status', CATALOG_INTEGRATED_SNAPSHOT:'catalog:integrated-snapshot', CATALOG_INTEGRATED_SYNC:'catalog:integrated-sync', CATALOG_LINK_PROJECT:'catalog:link-project', CATALOG_TEMPLATES:'catalog:templates', CATALOG_SAVE_TEMPLATE:'catalog:save-template', CATALOG_DELETE_TEMPLATE:'catalog:delete-template', CATALOG_OPEN_MODEL:'catalog:open-model', CIVITAI_SETTINGS:'civitai:settings', CIVITAI_SAVE_SETTINGS:'civitai:save-settings',
  VASTAI_SETTINGS:'vastai:settings', VASTAI_SAVE_SETTINGS:'vastai:save-settings', VASTAI_TEST:'vastai:test', VASTAI_SELECT_PRIVATE_KEY:'vastai:select-private-key', VASTAI_INSTANCES:'vastai:instances', VASTAI_START_INSTANCE:'vastai:start-instance', VASTAI_STOP_INSTANCE:'vastai:stop-instance', VASTAI_RESOLVE_SSH:'vastai:resolve-ssh',
  WORKFLOW_COMPILE:'workflow:compile', AVAILABILITY_CHECK:'availability:check', AVAILABILITY_CHECK_LORA_FILES:'availability:check-lora-files', AVAILABILITY_OPEN_R2:'availability:open-r2', PREFLIGHT_RUN:'preflight:run', EXECUTION_START:'execution:start', EXECUTION_STATUS:'execution:status', EXECUTION_GET:'execution:get', EXECUTION_STOP_SCHEDULING:'execution:stop-scheduling', EXECUTION_FORCE_INTERRUPT:'execution:force-interrupt', EXECUTION_RESUME:'execution:resume',
  R2_SETTINGS:'r2:settings', R2_ENVIRONMENT:'r2:environment', R2_TEST:'r2:test', R2_SAVE_SETTINGS:'r2:save-settings', R2_BUCKETS:'r2:buckets', R2_CREATE_BUCKET:'r2:create-bucket', R2_DELETE_BUCKET:'r2:delete-bucket', R2_LIST:'r2:list', R2_SEARCH:'r2:search', R2_DOWNLOAD_INFO:'r2:download-info', R2_BATCH_DOWNLOAD_INFO:'r2:batch-download-info', R2_PUT_URL_INFO:'r2:put-url-info', R2_DELETE_OBJECTS:'r2:delete-objects', R2_MOVE:'r2:move', R2_SELECT_UPLOAD_FILES:'r2:select-upload-files', R2_BEGIN_UPLOAD:'r2:begin-upload', R2_UPLOADS:'r2:uploads', R2_RESUME_UPLOAD:'r2:resume-upload', R2_PAUSE_UPLOAD:'r2:pause-upload', R2_CANCEL_UPLOAD:'r2:cancel-upload', R2_TEMPLATES:'r2:templates', R2_SAVE_TEMPLATE:'r2:save-template', R2_DELETE_TEMPLATE:'r2:delete-template', R2_METRICS:'r2:metrics',
  CLIPBOARD_WRITE_TEXT:'clipboard:write-text', GROK_SET_VISIBLE:'grok:set-visible', GROK_SET_CONTEXT:'grok:set-context', GROK_SET_RATIO:'grok:set-ratio', GROK_SET_DIVIDER_X:'grok:set-divider-x', GROK_RELOAD:'grok:reload', GROK_OPEN_EXTERNAL:'grok:open-external'
} as const;
