import { mkdir, readdir } from 'node:fs/promises';
import path from 'node:path';
import type { ArtifactKey, ArtifactReadResult, ImportResult, MissingRequirement, PromptPlanArtifact, ProjectBriefInput, ValidationResult } from '../shared/types.js';
import { backupIfExists, exists, readText, removeIfExists, writeJsonAtomic, writeTextAtomic } from './fs-utils.js';
import { parseModels, parsePromptPlan, validateModels, validateProjectBrief, validatePromptPlan } from './validation.js';
import { validateModelsAgainstCatalog } from './model-catalog.js';
const FILES:Partial<Record<ArtifactKey,string>>={projectBrief:'project_brief.json',story:'story.md',models:'models.json',promptPlan:'prompt_plan.json'}; const DRAFTS:Partial<Record<ArtifactKey,string>>={story:'story.md',models:'models.json',promptPlan:'prompt_plan.json'};
export const internalDir=(root:string)=>path.join(root,'._batch_studio'); export function draftPath(root:string,key:ArtifactKey){const n=DRAFTS[key];if(!n)throw new Error(`No draft mapping for ${key}`);return path.join(internalDir(root),'drafts',n);} export function confirmedPath(root:string,key:ArtifactKey){const n=FILES[key];if(!n)throw new Error(`No artifact mapping for ${key}`);return path.join(root,n);}
function fence(raw:string,lang?:string){const spec=lang??'[a-zA-Z0-9_-]*';const m=raw.match(new RegExp('```'+spec+'\\s*\\n([\\s\\S]*?)```','i'));return m?.[1]?.trim()??null;} function jsonCandidate(raw:string){const f=fence(raw,'json');if(f)return f;const a=raw.indexOf('{'),b=raw.lastIndexOf('}');return a>=0&&b>a?raw.slice(a,b+1).trim():raw.trim();} function storyCandidate(raw:string){return fence(raw,'markdown')??fence(raw,'md')??fence(raw)??raw.trim();}
async function validateContent(root:string,key:ArtifactKey,content:string):Promise<ValidationResult>{if(key==='story')return {valid:!!content.trim(),issues:content.trim()?[]:[{severity:'error',code:'STORY_EMPTY',message:'ストーリーが空です。'}]};if(key==='models'){const p=parseModels(content);if(!p)return {valid:false,issues:[{severity:'error',code:'MODELS_PARSE',message:'models.jsonをJSONとして解析できません。'}]};const base=validateModels(p);const unresolved=missing(p);if(unresolved.length)base.issues.push({severity:'error',code:'MISSING_REQUIREMENTS',message:`未解決の不足モデルが${unresolved.length}件あります。`});base.valid=!base.issues.some(x=>x.severity==='error');return base.valid?validateModelsAgainstCatalog(root,p,base):base;}if(key==='promptPlan'){const p=parsePromptPlan(content);if(!p)return {valid:false,issues:[{severity:'error',code:'PLAN_PARSE',message:'prompt_plan.jsonをJSONとして解析できません。'}]};const mt=await readText(path.join(root,'models.json'));return validatePromptPlan(p,mt?parseModels(mt):null);}if(key==='projectBrief'){try{return validateProjectBrief(JSON.parse(content) as ProjectBriefInput)}catch{return {valid:false,issues:[{severity:'error',code:'BRIEF_PARSE',message:'project_brief.jsonを解析できません。'}]}}}return {valid:true,issues:[]};}
export async function readArtifact(root:string,key:ArtifactKey,source:'confirmed'|'draft'):Promise<ArtifactReadResult>{if(!FILES[key]&&source==='confirmed')return {key,source,content:null,exists:false,validation:{valid:false,issues:[{severity:'error',code:'MISSING',message:'対象Artifactではありません。'}]}}; if(!DRAFTS[key]&&source==='draft')return {key,source,content:null,exists:false,validation:{valid:false,issues:[{severity:'error',code:'MISSING',message:'下書き対象ではありません。'}]}}; const file=source==='confirmed'?confirmedPath(root,key):draftPath(root,key);const content=await readText(file);return {key,source,content,exists:content!=null,validation:content==null?{valid:false,issues:[{severity:'error',code:'MISSING',message:'ファイルがありません。'}]}:await validateContent(root,key,content)};}
export async function saveDraft(root:string,key:'story'|'models'|'promptPlan',content:string){await writeTextAtomic(draftPath(root,key),content.endsWith('\n')?content:content+'\n');return readArtifact(root,key,'draft');}
function missing(parsed:any):MissingRequirement[]{return Array.isArray(parsed?.missingRequirements)?parsed.missingRequirements.filter((x:any)=>x&&typeof x.role==='string'&&typeof x.requirement==='string'&&typeof x.reason==='string'):[];}
export async function importGrok(root:string,key:'story'|'models'|'promptPlan',raw:string):Promise<ImportResult>{let extracted=key==='story'?storyCandidate(raw):jsonCandidate(raw),miss:MissingRequirement[]=[];if(key==='models'){try{const p=JSON.parse(extracted);miss=missing(p);if(!miss.length&&'missingRequirements'in p)delete p.missingRequirements;extracted=JSON.stringify(p,null,2)}catch{}}const saved=await saveDraft(root,key,extracted);const issues=[...saved.validation.issues];if(miss.length)issues.push({severity:'error',code:'MISSING_REQUIREMENTS',message:`未解決の不足モデルが${miss.length}件あります。`});const validation={valid:!issues.some(x=>x.severity==='error'),issues};const summary:Record<string,string|number|boolean|null>={};if(key==='promptPlan'){const p=parsePromptPlan(extracted);if(p){summary.branches=p.branches.length;summary.items=p.branches.reduce((n,b)=>n+b.leaves.length,0);summary.images=summary.items;}}return {extracted,validation,summary,missingRequirements:miss};}
export async function confirmArtifact(root:string,key:'story'|'models'|'promptPlan'){const d=await readArtifact(root,key,'draft');if(!d.exists||!d.content)throw new Error('確定する下書きがありません。');if(!d.validation.valid)throw new Error('検証エラーがあるため確定できません。');const target=confirmedPath(root,key);await backupIfExists(target,path.join(internalDir(root),'history',key));await writeTextAtomic(target,d.content);await removeIfExists(draftPath(root,key));}
export async function createProject(parent:string,brief:ProjectBriefInput){const v=validateProjectBrief(brief);if(!v.valid)throw new Error(v.issues.map(i=>i.message).join('\n'));const root=path.join(parent,brief.project.id);if(await exists(root)){const es=await readdir(root);if(es.length)throw new Error('同名のプロジェクトフォルダーが既に存在します。');}await mkdir(path.join(root,'._batch_studio','drafts'),{recursive:true});await mkdir(path.join(root,'._batch_studio','history'),{recursive:true});await writeJsonAtomic(path.join(root,'project_brief.json'),{schemaVersion:1,...brief});await writeJsonAtomic(path.join(root,'project_meta.json'),{schemaVersion:1,createdAt:new Date().toISOString(),settings:{}});return root;}
export async function savePromptPlan(root:string,plan:PromptPlanArtifact){return saveDraft(root,'promptPlan',JSON.stringify(plan,null,2));}

export async function beginEditArtifact(root:string,key:'story'|'models'|'promptPlan'){
  const currentDraft=await readArtifact(root,key,'draft');
  if(currentDraft.exists) return currentDraft;
  const confirmed=await readArtifact(root,key,'confirmed');
  if(!confirmed.exists||confirmed.content==null) return currentDraft;
  return saveDraft(root,key,confirmed.content);
}

export async function saveProjectBrief(root:string,brief:ProjectBriefInput){const v=validateProjectBrief(brief);if(!v.valid)throw new Error(v.issues.map(i=>i.message).join('\n'));const current=await readText(path.join(root,'project_brief.json'));let currentId:string|null=null;if(current){try{currentId=JSON.parse(current)?.project?.id??null}catch{}}if(currentId&&currentId!==brief.project.id)throw new Error('既存プロジェクトのproject.idは変更できません。');await backupIfExists(path.join(root,'project_brief.json'),path.join(internalDir(root),'history','projectBrief'));await writeJsonAtomic(path.join(root,'project_brief.json'),{schemaVersion:1,...brief});}
