import { readdir } from 'node:fs/promises';
import path from 'node:path';
import type { ModelAvailabilityItem, ModelsArtifact } from '../shared/types.js';
import { readJson } from './fs-utils.js';
import { readProjectSettings } from './project-meta.js';

async function recursiveNames(root:string):Promise<Map<string,string>>{ const map=new Map<string,string>(); async function walk(dir:string){let entries;try{entries=await readdir(dir,{withFileTypes:true});}catch{return;} for(const e of entries){const p=path.join(dir,e.name); if(e.isDirectory())await walk(p); else if(!map.has(e.name.toLowerCase()))map.set(e.name.toLowerCase(),p);} } await walk(root); return map; }
async function r2Names(file:string|undefined):Promise<Set<string>|null>{ if(!file)return null; const data=await readJson<unknown>(file); if(!data)return null; const names=new Set<string>(); const visit=(v:unknown)=>{if(Array.isArray(v)){v.forEach(visit);return;} if(v&&typeof v==='object'){const o=v as Record<string,unknown>; for(const k of ['name','fileName','key','path'])if(typeof o[k]==='string')names.add(path.basename(o[k] as string).toLowerCase()); Object.values(o).forEach(visit);} else if(typeof v==='string')names.add(path.basename(v).toLowerCase());}; visit(data); return names; }
export async function checkAvailability(root:string):Promise<ModelAvailabilityItem[]>{ const models=await readJson<ModelsArtifact>(path.join(root,'models.json')); if(!models)return[]; const settings=await readProjectSettings(root); const local=settings.comfyUiModelsRoot?await recursiveNames(settings.comfyUiModelsRoot):new Map<string,string>(); const r2=await r2Names(settings.r2InventoryPath); return [models.checkpoint,...models.loras].map(s=>{const key=s.fileName.toLowerCase(); const lp=local.get(key); const localOk=!!lp; const r2Ok=r2? r2.has(key):null; let status:ModelAvailabilityItem['status']='unknown'; if(localOk)status='available'; else if(r2Ok===true)status='transfer-required'; else if(r2Ok===false)status='missing'; return {ref:s.ref,fileName:s.fileName,local:localOk,r2:r2Ok,status,localPath:lp};}); }
