import path from 'node:path';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import type { CatalogSelectionTemplate, CatalogSelectionTemplateInput, CivitaiCatalogStatus, ModelCatalog, StrengthBaseline } from '../shared/types.js';

const METHOD='median-of-post-medians:newest-200';
const MIN_DISTINCT_POSTS=5;
const MAX_COLLECTION_PAGES=1000;

function numberValue(value:unknown):number|null{return typeof value==='number'&&Number.isFinite(value)?value:null}
function median(values:number[]){const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2}
export function calculateStrengthBaseline(items:unknown[],versionId:number):StrengthBaseline|null{
  const byPost=new Map<string,number[]>();
  for(const image of items){if(!image||typeof image!=='object')continue;const row=image as Record<string,unknown>;if(row.postId==null||!row.meta||typeof row.meta!=='object')continue;const resources=(row.meta as Record<string,unknown>).civitaiResources;if(!Array.isArray(resources))continue;for(const resource of resources){if(!resource||typeof resource!=='object')continue;const r=resource as Record<string,unknown>;if(String(r.type??'').toLowerCase()!=='lora'||Number(r.modelVersionId)!==versionId)continue;const weight=numberValue(r.weight);if(weight==null)continue;const key=String(row.postId),values=byPost.get(key)??[];values.push(weight);byPost.set(key,values)}}
  if(byPost.size<MIN_DISTINCT_POSTS)return null;const perPost=[...byPost.values()].filter(x=>x.length).map(median);if(perPost.length<MIN_DISTINCT_POSTS)return null;return {value:median(perPost),provenance:{source:'civitai',basis:'observed-usage-derived',method:METHOD,sampleCount:perPost.length}};
}

async function atomicJson(file:string,value:unknown){await mkdir(path.dirname(file),{recursive:true});const temp=path.join(path.dirname(file),`.${path.basename(file)}.tmp`);await writeFile(temp,JSON.stringify(value,null,2)+'\n','utf8');await rename(temp,file)}
async function readJson<T>(file:string):Promise<T|null>{try{return JSON.parse(await readFile(file,'utf8')) as T}catch{return null}}
async function mapLimit<T,R>(items:T[],limit:number,fn:(item:T,index:number)=>Promise<R>):Promise<R[]>{const result=new Array<R>(items.length);let cursor=0;async function worker(){for(;;){const index=cursor++;if(index>=items.length)return;result[index]=await fn(items[index],index)}}await Promise.all(Array.from({length:Math.min(limit,Math.max(items.length,1))},worker));return result}
class CivitaiError extends Error{constructor(message:string,readonly statusCode=502){super(message)}}

export class CivitaiCatalogService{
  readonly catalogPath:string;readonly templatesPath:string;private readonly apiKey:string;private readonly baseUrl:string;private readonly matureBaseUrl:string;private readonly timeoutMs:number;private snapshot:ModelCatalog|null=null;private syncPromise:Promise<void>|null=null;private statusValue:CivitaiCatalogStatus;
  constructor(storageRoot:string){this.catalogPath=path.join(storageRoot,'model_catalog.json');this.templatesPath=path.join(storageRoot,'selection_templates.json');this.apiKey=(process.env.CIVIT_API_KEY??'').trim();this.baseUrl=(process.env.CIVITAI_BASE_URL??'https://civitai.com').replace(/\/$/,'');this.matureBaseUrl=(process.env.CIVITAI_MATURE_BASE_URL??'https://civitai.red').replace(/\/$/,'');this.timeoutMs=Math.max(1000,Number(process.env.CIVITAI_TIMEOUT??20)*1000);this.statusValue={state:'idle',phase:'待機中',completed:0,total:0,message:'同期待ち',generation:0,changes:{added:0,updated:0,removed:0},error:null,apiKeyConfigured:Boolean(this.apiKey),catalogPath:this.catalogPath};}
  async initialize(){this.snapshot=await readJson<ModelCatalog>(this.catalogPath);if(this.snapshot?.schemaVersion===1&&Array.isArray(this.snapshot.collections)){this.statusValue={...this.statusValue,state:'ready',phase:'完了',message:'保存済みカタログを使用できます',generation:this.snapshot.generation,total:this.snapshot.collections.length,completed:this.snapshot.collections.length}}else this.snapshot=null;}
  status(){return structuredClone(this.statusValue)} catalog(){return this.snapshot?structuredClone(this.snapshot):null}
  async startSync(){if(this.syncPromise)return this.status();if(!this.apiKey){this.statusValue={...this.statusValue,state:'error',phase:'同期失敗',message:'Civitai APIキーが必要です',error:'環境変数 CIVIT_API_KEY が設定されていません。'};return this.status()}this.statusValue={...this.statusValue,state:'running',phase:'準備中',completed:0,total:1,message:'Civitaiからコレクション一覧を取得しています',changes:{added:0,updated:0,removed:0},error:null};this.syncPromise=this.sync().finally(()=>{this.syncPromise=null});return this.status()}
  async waitForSync(){await this.syncPromise} private progress(phase:string,completed:number,total:number,message:string){this.statusValue={...this.statusValue,state:'running',phase,completed,total:Math.max(total,1),message}}
  private async sync(){try{const collections=await this.getCollections();if(!collections.length)throw new CivitaiError('同期できるModelコレクションがありません。');const collectionIds=collections.map(x=>x.id);this.progress('コレクション確認中',0,collectionIds.length,'コレクション内容を確認しています');const itemSets=await mapLimit(collectionIds,6,async(id,index)=>{const items=await this.getCollectionItems(id);this.progress('コレクション確認中',index+1,collectionIds.length,`コレクション ${index+1}/${collectionIds.length} を確認中`);return items});
    const rows:Array<{collectionId:number;item:any}>=[];collectionIds.forEach((id,index)=>{for(const item of itemSets[index]){const data=item?.data,version=data?.version;if(item?.type==='model'&&data?.id&&version?.id)rows.push({collectionId:id,item})}});
    const modelIds=[...new Set(rows.map(x=>Number(x.item.data.id)))];const models=new Map<number,any>();this.progress('モデル収集中',0,modelIds.length,'モデル詳細を収集中');await mapLimit(modelIds,4,async(id,index)=>{models.set(id,await this.getJson(`/api/v1/models/${id}`));this.progress('モデル収集中',index+1,modelIds.length,`モデル ${index+1}/${modelIds.length} を収集中`)});
    const fallbackIds=[...new Set(rows.filter(x=>{const data=x.item.data,id=Number(data.version.id),versions=models.get(Number(data.id))?.modelVersions;return !Array.isArray(versions)||!versions.some((v:any)=>Number(v?.id)===id)}).map(x=>Number(x.item.data.version.id)))];const fallback=new Map<number,any>();await mapLimit(fallbackIds,8,async(id)=>{try{fallback.set(id,await this.getJson(`/api/v1/model-versions/${id}`))}catch{}});
    const exportVersion=(modelId:number,detail:any,fallbackName='名称未設定')=>{const id=Number(detail?.id),trained=Array.isArray(detail?.trainedWords)?detail.trainedWords.map(String):[],files=(Array.isArray(detail?.files)?detail.files:[]).map((f:any)=>({id:Number(f.id),name:String(f.name??'名称未設定'),primary:Boolean(f.primary),sizeKB:numberValue(f.sizeKB)??undefined,type:typeof f.type==='string'?f.type:undefined,componentType:typeof f.metadata?.component==='string'?f.metadata.component:typeof f.metadata?.componentType==='string'?f.metadata.componentType:undefined,format:f.metadata?.format??undefined,precision:f.metadata?.fp??undefined}));const images=Array.isArray(detail?.images)?detail.images:[];const image=images.find((x:any)=>x?.url&&String(x.type??'').toLowerCase()!=='video'&&!/\.(mp4|webm|mov)(?:$|[?#])/i.test(String(x.url)))??{};let thumbnailUrl=typeof image.url==='string'?image.url:undefined;if(thumbnailUrl&&/^https:\/\/(image|imagecache)\.civitai\.com\//.test(thumbnailUrl))thumbnailUrl=thumbnailUrl.replace(/\/(?:original=true|width=\d+)\//,'/width=450/');return {versionId:id,versionName:String(detail?.name??fallbackName),baseModel:typeof detail?.baseModel==='string'?detail.baseModel:undefined,modelUrl:`https://civitai.com/models/${modelId}?modelVersionId=${id}`,thumbnailUrl,thumbnailWidth:numberValue(image.width)??undefined,thumbnailHeight:numberValue(image.height)??undefined,trainedWords:trained,files}};
    const byCollection=new Map<number,any[]>();for(const id of collectionIds)byCollection.set(id,[]);for(const {collectionId,item} of rows){const data=item.data,modelId=Number(data.id),selectedId=Number(data.version.id),modelDetail=models.get(modelId)??{},rawVersions=Array.isArray(modelDetail.modelVersions)?modelDetail.modelVersions:[];const versions=rawVersions.filter((v:any)=>v?.id!=null).map((v:any)=>exportVersion(modelId,v));let selected=versions.find((v:any)=>v.versionId===selectedId);if(!selected){const detail={...(fallback.get(selectedId)??{}),id:selectedId,name:fallback.get(selectedId)?.name??data.version.name,baseModel:fallback.get(selectedId)?.baseModel??data.version.baseModel,trainedWords:fallback.get(selectedId)?.trainedWords??data.version.trainedWords??[],files:fallback.get(selectedId)?.files??data.version.files??[],images:fallback.get(selectedId)?.images??data.version.images??[]};selected=exportVersion(modelId,detail,String(data.version.name??'名称未設定'));versions.unshift(selected)}byCollection.get(collectionId)!.push({modelId,modelName:String(data.name??modelDetail.name??'名称未設定'),modelType:String(modelDetail.type??data.type??data.modelType??''),...selected,versions})}
    const versionIds=[...new Set([...byCollection.values()].flatMap(items=>items.filter(item=>['lora','locon','dora'].includes(String(item.modelType).toLowerCase())).flatMap(item=>item.versions.map((v:any)=>Number(v.versionId)))))];const baselines=new Map<number,StrengthBaseline|null>();this.progress('LoRA強度根拠確認中',0,versionIds.length,'LoRA強度根拠を確認しています');await mapLimit(versionIds,6,async(id,index)=>{try{const payload=await this.getJson('/api/v1/images',{modelVersionId:id,withMeta:'true',sort:'Newest',limit:200});baselines.set(id,calculateStrengthBaseline(Array.isArray(payload?.items)?payload.items:[],id))}catch{baselines.set(id,null)}this.progress('LoRA強度根拠確認中',index+1,versionIds.length,`LoRA強度根拠 ${index+1}/${versionIds.length} を確認中`)});for(const items of byCollection.values())for(const item of items){for(const version of item.versions){const baseline=baselines.get(Number(version.versionId));if(baseline)version.strengthBaseline=baseline}const selectedBaseline=baselines.get(Number(item.versionId));if(selectedBaseline)item.strengthBaseline=selectedBaseline}
    const metaById=new Map(collections.map(x=>[x.id,x]));const enriched=[];for(let i=0;i<collectionIds.length;i++){const id=collectionIds[i],meta=metaById.get(id)!;this.progress('サムネイル確認中',i+1,collectionIds.length,`サムネイル ${i+1}/${collectionIds.length} を確認中`);let thumbnailUrl:string|undefined;try{thumbnailUrl=await this.getCollectionThumbnail(meta,itemSets[i])}catch{}enriched.push({id,name:meta.name,description:meta.description,read:meta.read,type:meta.type,imageId:meta.imageId,thumbnailUrl,items:byCollection.get(id)??[]})}
    const previous=this.snapshot;const prevMap=new Map((previous?.collections??[]).map(x=>[x.id,x])),curMap=new Map(enriched.map(x=>[x.id,x]));const added=[...curMap.keys()].filter(k=>!prevMap.has(k)).length,removed=[...prevMap.keys()].filter(k=>!curMap.has(k)).length,updated=[...curMap.keys()].filter(k=>prevMap.has(k)&&JSON.stringify(curMap.get(k))!==JSON.stringify(prevMap.get(k))).length;const snapshot:ModelCatalog={schemaVersion:1,generation:(previous?.generation??0)+1,generatedAt:new Date().toISOString(),collections:enriched};await atomicJson(this.catalogPath,snapshot);this.snapshot=snapshot;this.statusValue={...this.statusValue,state:'ready',phase:'完了',completed:enriched.length,total:enriched.length,message:'モデルカタログを更新しました',generation:snapshot.generation,changes:{added,updated,removed},error:null};}catch(error){this.statusValue={...this.statusValue,state:'error',phase:'同期失敗',message:'モデルカタログを更新できませんでした',error:error instanceof Error?error.message:String(error)}}}
  private async getJson(endpoint:string,params?:Record<string,string|number|boolean>,base=this.baseUrl){const url=new URL(endpoint,base);for(const [key,value] of Object.entries(params??{}))url.searchParams.set(key,String(value));let response:Response|null=null;for(let attempt=0;attempt<4;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.timeoutMs);try{response=await fetch(url,{headers:{Authorization:`Bearer ${this.apiKey}`,Accept:'application/json','User-Agent':'comfyui-batch-studio/1.0'},signal:controller.signal})}catch(error){clearTimeout(timer);throw new CivitaiError(`Civitaiへの接続に失敗しました: ${error instanceof Error?error.message:String(error)}`)}clearTimeout(timer);if(response.status!==429||attempt===3)break;const retry=Number(response.headers.get('Retry-After'));await new Promise(r=>setTimeout(r,Math.min(Number.isFinite(retry)?retry*1000:500*2**attempt,10000)))}if(!response)throw new CivitaiError('Civitaiから応答がありません。');if(response.status===401||response.status===403)throw new CivitaiError('CIVIT_API_KEYが無効か、CollectionsRead権限がありません。',response.status);if(response.status===429)throw new CivitaiError('Civitaiのレート制限に達しました。しばらく待ってから再試行してください。',429);if(!response.ok)throw new CivitaiError(`Civitai APIがHTTP ${response.status}を返しました。`,response.status);try{return await response.json()}catch{throw new CivitaiError('Civitai APIから不正なJSONが返されました。')}}
  private async trpc(procedure:string,payload:Record<string,unknown>,base=this.baseUrl){const body=await this.getJson(`/api/trpc/${procedure}`,{input:JSON.stringify({json:payload})},base);const result=body?.result?.data?.json;if(result===undefined)throw new CivitaiError(body?.error?.json?.message??'Civitai内部APIの形式が変更されました。');return result}
  private async getCollections(){const raw=await this.trpc('collection.getAllUser',{});if(!Array.isArray(raw))throw new CivitaiError('コレクション一覧の形式が変更されました。');return raw.filter((x:any)=>x?.type==='Model'||x?.type==null).map((x:any)=>({id:Number(x.id),name:String(x.name??'名称未設定'),description:String(x.description??''),read:String(x.read??'Private'),type:String(x.type??'Model'),imageId:x.imageId==null?undefined:Number(x.imageId)}))}
  private async getCollectionItems(collectionId:number){const items:any[]=[];let cursor:string|undefined;const seen=new Set<string>();for(let page=0;page<MAX_COLLECTION_PAGES;page++){const payload:any={collectionId,limit:100,browsingLevel:31};if(cursor)payload.cursor=cursor;const data=await this.trpc('collection.getAllCollectionItems',payload,this.matureBaseUrl);const rows=Array.isArray(data?.collectionItems)?data.collectionItems:[];items.push(...rows);if(!data?.nextCursor)break;cursor=String(data.nextCursor);if(seen.has(cursor))throw new CivitaiError('Civitai APIが同じページカーソルを返しました。');seen.add(cursor);if(page===MAX_COLLECTION_PAGES-1)throw new CivitaiError('コレクションのページ数が安全上限を超えました。')}return items}
  private async getCollectionThumbnail(meta:any,items:any[]){let imageId=meta.imageId;if(!imageId){const found=items.find(x=>x?.data?.images?.[0]?.id);imageId=found?.data?.images?.[0]?.id}if(!imageId)return undefined;const payload=await this.getJson('/api/v1/images',{imageId:Number(imageId),limit:1});const row=Array.isArray(payload?.items)?payload.items[0]:null;return typeof row?.url==='string'?row.url:undefined}
  async templates(){return (await readJson<CatalogSelectionTemplate[]>(this.templatesPath))??[]}
  async saveTemplate(input:CatalogSelectionTemplateInput){const name=input.name.trim();if(!name)throw new Error('テンプレート名を入力してください。');const templates=await this.templates(),now=new Date().toISOString(),existing=input.id?templates.find(x=>x.id===input.id):null;const value:CatalogSelectionTemplate={id:existing?.id??`template-${Date.now().toString(36)}`,name:name.slice(0,60),createdAt:existing?.createdAt??now,updatedAt:now,selection:input.selection};const next=[...templates.filter(x=>x.id!==value.id),value].sort((a,b)=>a.name.localeCompare(b.name,'ja'));await atomicJson(this.templatesPath,next);return next}
  async deleteTemplate(id:string){const next=(await this.templates()).filter(x=>x.id!==id);await atomicJson(this.templatesPath,next);return next}
}
