import { createHash } from 'node:crypto';
import path from 'node:path';
import type { ModelsArtifact, PromptBranch, PromptPlanArtifact, ValidationIssue, WorkflowCompileResult } from '../shared/types.js';
import { readJson, readText, writeJsonAtomic } from './fs-utils.js';
import { readProjectSettings } from './project-meta.js';
import { parseModels, parsePromptPlan, validateModels, validatePromptPlan } from './validation.js';

interface RoleBinding { nodeId:number }
interface Boundary { id:string; source:{role:string;slot:number}; target:{role:string;slot:number} }
interface Manifest { schemaVersion:number; manifestVersion:string; template:{id:string;version:string;sha256:string}; common:{roles:Record<string,RoleBinding>}; branchPrototype:{nodeIds:number[];groupIds:number[];roles:Record<string,RoleBinding>;boundaries:Boundary[];layout:{offset:{x:number;y:number}}} }
interface NodeLike { id:number; type?:string; title?:string; pos?:[number,number]; inputs?:Array<{link?:number|null;[k:string]:unknown}>; outputs?:Array<{links?:number[]|null;[k:string]:unknown}>; widgets_values?:unknown[]; widgets_values_named?:Record<string,unknown>; [k:string]:unknown }
interface GroupLike { id:number; title?:string; bounding?:[number,number,number,number]; [k:string]:unknown }
interface Workflow { last_node_id:number; last_link_id:number; nodes:NodeLike[]; links:unknown[][]; groups?:GroupLike[]; [k:string]:unknown }

const clone=<T>(v:T):T=>structuredClone(v);
function hashText(text:string){return createHash('sha256').update(Buffer.from(text,'utf8')).digest('hex');}
function nodeById(w:Workflow,id:number):NodeLike{const n=w.nodes.find(x=>x.id===id);if(!n)throw new Error(`Template node ${id} not found.`);return n;}
function linkInfo(raw:unknown[]):{id:number;origin:number;originSlot:number;target:number;targetSlot:number}{return {id:Number(raw[0]),origin:Number(raw[1]),originSlot:Number(raw[2]),target:Number(raw[3]),targetSlot:Number(raw[4])};}
function setNamed(node:NodeLike,key:string,value:unknown){ node.widgets_values_named={...(node.widgets_values_named??{}),[key]:value}; }
function setTitle(node:NodeLike,title:string){node.title=title;}
function patchCheckpoint(node:NodeLike,models:ModelsArtifact){setNamed(node,'ckpt_name',models.checkpoint.fileName);setNamed(node,'checkpoint',models.checkpoint.fileName); if(Array.isArray(node.widgets_values)&&node.widgets_values.length)node.widgets_values[0]=models.checkpoint.fileName;}
function loraPayload(loras:PromptPlanArtifact['rootLoras'],models:ModelsArtifact){const map=new Map(models.loras.map(x=>[x.ref,x]));return loras.map(x=>({ref:x.modelRef,fileName:map.get(x.modelRef)?.fileName??x.modelRef,strengthModel:x.strengthModel,strengthClip:x.strengthClip}));}
function patchLoras(node:NodeLike,loras:PromptPlanArtifact['rootLoras'],models:ModelsArtifact){const payload=loraPayload(loras,models); const stack={version:1,loras:payload.map(x=>({enabled:true,name:x.fileName,strength_model:x.strengthModel,strength_clip:x.strengthClip}))}; const encoded=JSON.stringify(stack); setNamed(node,'lora_stack_data',encoded); if(Array.isArray(node.widgets_values)){node.widgets_values[0]=encoded;} }
function patchCommon(node:NodeLike,plan:PromptPlanArtifact){setNamed(node,'positive_base',plan.common.positive);setNamed(node,'negative_base',plan.common.negative);setNamed(node,'positive_json','{"version":1,"categories":{}}');setNamed(node,'negative_json','{"version":1,"categories":{}}'); if(Array.isArray(node.widgets_values)){if(node.widgets_values.length>1)node.widgets_values[1]=plan.common.positive;if(node.widgets_values.length>3)node.widgets_values[3]=plan.common.negative;} setTitle(node,'Batch Studio 共通プロンプト');}
function sceneLine(leaf:PromptBranch['leaves'][number]){return {type:'SCENE_MATRIX_LINE',version:1,row_id:leaf.id,node_id:'',category:'',name:leaf.name,path_label:leaf.id,enabled:true,filename_enabled:true,positive_base:leaf.positive,positive_json:'{"version":1,"categories":{}}',negative_base:leaf.negative,negative_json:'{"version":1,"categories":{}}',category_order:'',positive_parts:[],negative_parts:[],display_labels:[],display_label_groups:[]};}
function patchMatrix(node:NodeLike,branch:PromptBranch){const rows=branch.leaves.map(sceneLine);const encoded=JSON.stringify({version:1,sets:rows});setNamed(node,'matrix_json',encoded);if(Array.isArray(node.widgets_values)){node.widgets_values[0]=encoded;}setTitle(node,`Prompt - ${branch.id} - ${displayLabel(branch.label)} (${branch.leaves.length})`);}
function patchCounter(node:NodeLike){setNamed(node,'count',1);setNamed(node,'images_per_leaf',1);setTitle(node,'1 image per leaf'); if(Array.isArray(node.widgets_values)){const idx=node.widgets_values.findIndex(v=>typeof v==='number');if(idx>=0)node.widgets_values[idx]=1;}}
function patchSave(node:NodeLike,projectId:string,branch:PromptBranch){const p=`BatchStudio/${projectId}/${branch.id}`;setNamed(node,'path',p);if(Array.isArray(node.widgets_values)){node.widgets_values[0]=p;}setTitle(node,`Save - ${branch.id} - ${displayLabel(branch.label)} (${branch.leaves.length})`);}
function displayLabel(label:string){return label.trim().replace(/[\r\n]+/g,' ').replace(/\s+/g,' ').slice(0,80);}

function validateManifest(m:Manifest,w:Workflow):ValidationIssue[]{const issues:ValidationIssue[]=[]; if(m.schemaVersion!==1)issues.push({severity:'error',code:'MANIFEST_SCHEMA',message:'Manifest schemaVersionは1である必要があります。'}); const ids=new Set(w.nodes.map(n=>n.id)); const proto=new Set(m.branchPrototype.nodeIds); for(const id of m.branchPrototype.nodeIds)if(!ids.has(id))issues.push({severity:'error',code:'MANIFEST_NODE',message:`Prototype node ${id} がTemplateにありません。`}); for(const [role,b] of Object.entries(m.branchPrototype.roles))if(!proto.has(b.nodeId))issues.push({severity:'error',code:'MANIFEST_ROLE',message:`Branch role ${role} はPrototype外のNodeを参照しています。`}); const boundaryIds=new Set<string>(); for(const b of m.branchPrototype.boundaries){if(boundaryIds.has(b.id))issues.push({severity:'error',code:'BOUNDARY_DUP',message:`Boundary ${b.id} が重複しています。`});boundaryIds.add(b.id);const sr=m.common.roles[b.source.role],tr=m.branchPrototype.roles[b.target.role];if(!sr||!tr){issues.push({severity:'error',code:'BOUNDARY_ROLE',message:`Boundary ${b.id} のroleが解決できません。`});continue;}const matches=w.links.filter(raw=>{const li=linkInfo(raw);return li.origin===sr.nodeId&&li.originSlot===b.source.slot&&li.target===tr.nodeId&&li.targetSlot===b.target.slot;});if(matches.length!==1)issues.push({severity:'error',code:'BOUNDARY_LINK',message:`Boundary ${b.id} に一致するTemplate Linkは1本必要です（${matches.length}本）。`});} const declared=new Set(m.branchPrototype.boundaries.map(b=>{const sr=m.common.roles[b.source.role],tr=m.branchPrototype.roles[b.target.role];return sr&&tr?`${sr.nodeId}:${b.source.slot}->${tr.nodeId}:${b.target.slot}`:'';})); for(const raw of w.links){const li=linkInfo(raw);if(!proto.has(li.origin)&&proto.has(li.target)){const k=`${li.origin}:${li.originSlot}->${li.target}:${li.targetSlot}`;if(!declared.has(k))issues.push({severity:'error',code:'BOUNDARY_UNDECLARED',message:`未宣言のCommon→Branch Linkがあります: ${k}`});} if(proto.has(li.origin)&&!proto.has(li.target))issues.push({severity:'error',code:'BOUNDARY_DIRECTION',message:'v1で未対応のBranch→Common Linkがあります。'});} if(m.branchPrototype.layout.offset.x===0&&m.branchPrototype.layout.offset.y===0)issues.push({severity:'error',code:'LAYOUT_OFFSET',message:'Branch layout offsetが0のため複製Branchが重なります。'}); return issues;}

function cloneBranch(w:Workflow,m:Manifest,index:number):{nodeMap:Map<number,number>;linkMap:Map<number,number>;groupMap:Map<number,number>}{
 const proto=new Set(m.branchPrototype.nodeIds); const nodeMap=new Map<number,number>();const linkMap=new Map<number,number>();const groupMap=new Map<number,number>();
 const dx=m.branchPrototype.layout.offset.x*index,dy=m.branchPrototype.layout.offset.y*index;
 for(const oldId of m.branchPrototype.nodeIds){const old=nodeById(w,oldId);const n=clone(old);n.id=++w.last_node_id;nodeMap.set(oldId,n.id);if(Array.isArray(n.pos)){n.pos=[n.pos[0]+dx,n.pos[1]+dy];} if(Array.isArray(n.inputs))n.inputs=n.inputs.map(i=>({...i,link:null})); if(Array.isArray(n.outputs))n.outputs=n.outputs.map(o=>({...o,links:[]}));w.nodes.push(n);}
 const sourceLinks=[...w.links]; for(const raw of sourceLinks){const li=linkInfo(raw);if(proto.has(li.origin)&&proto.has(li.target)){const id=++w.last_link_id;linkMap.set(li.id,id);const nr=[...raw];nr[0]=id;nr[1]=nodeMap.get(li.origin)!;nr[3]=nodeMap.get(li.target)!;w.links.push(nr);const on=nodeById(w,nr[1] as number),tn=nodeById(w,nr[3] as number);const out=on.outputs?.[li.originSlot];if(out){out.links=[...(out.links??[]),id];}const inp=tn.inputs?.[li.targetSlot];if(inp)inp.link=id;}}
 if(w.groups){for(const gid of m.branchPrototype.groupIds){const g=w.groups.find(x=>x.id===gid);if(!g)continue;const ng=clone(g);ng.id=Math.max(0,...w.groups.map(x=>x.id))+1;groupMap.set(gid,ng.id);if(Array.isArray(ng.bounding)){ng.bounding=[ng.bounding[0]+dx,ng.bounding[1]+dy,ng.bounding[2],ng.bounding[3]];}w.groups.push(ng);}}
 for(const b of m.branchPrototype.boundaries){const sourceRole=m.common.roles[b.source.role];const targetRole=m.branchPrototype.roles[b.target.role];if(!sourceRole||!targetRole)continue;const source=sourceRole.nodeId,target=nodeMap.get(targetRole.nodeId)!;const original=w.links.find(raw=>{const li=linkInfo(raw);return li.origin===sourceRole.nodeId&&li.originSlot===b.source.slot&&li.target===targetRole.nodeId&&li.targetSlot===b.target.slot;});const linkType=original?.[5]??'*';const id=++w.last_link_id;w.links.push([id,source,b.source.slot,target,b.target.slot,linkType]);const sn=nodeById(w,source),tn=nodeById(w,target);const out=sn.outputs?.[b.source.slot];if(out)out.links=[...(out.links??[]),id];const inp=tn.inputs?.[b.target.slot];if(inp)inp.link=id;}
 return {nodeMap,linkMap,groupMap};
}

function patchBranchGroup(w:Workflow,m:Manifest,branch:PromptBranch,map?:Map<number,number>){if(!w.groups)return;for(const gid of m.branchPrototype.groupIds){const targetId=map?.get(gid)??gid;const g=w.groups.find(x=>x.id===targetId);if(g)g.title=`Gen - ${branch.id} - ${displayLabel(branch.label)} (${branch.leaves.length})`;}}
function branchRoleNode(w:Workflow,m:Manifest,role:string,map?:Map<number,number>){const id=m.branchPrototype.roles[role]?.nodeId;if(id==null)throw new Error(`Missing branch role ${role}`);return nodeById(w,map?.get(id)??id);}
function patchBranch(w:Workflow,m:Manifest,branch:PromptBranch,models:ModelsArtifact,projectId:string,map?:Map<number,number>,groupMap?:Map<number,number>){patchBranchGroup(w,m,branch,groupMap);patchLoras(branchRoleNode(w,m,'loraStack',map),branch.loras,models);setTitle(branchRoleNode(w,m,'loraStack',map),`LoRA - ${branch.id} - ${displayLabel(branch.label)}`);patchMatrix(branchRoleNode(w,m,'mainMatrix',map),branch);patchCounter(branchRoleNode(w,m,'counter',map));patchSave(branchRoleNode(w,m,'save',map),projectId,branch);}

export async function compileWorkflow(root:string):Promise<WorkflowCompileResult>{const issues:ValidationIssue[]=[];try{
 const settings=await readProjectSettings(root); const templatePath=settings.workflowTemplatePath||path.join(process.cwd(),'templates','default-scene-batch','workflow.json'); const manifestPath=settings.workflowManifestPath||path.join(process.cwd(),'templates','default-scene-batch','manifest.json');
 const templateText=await readText(templatePath);const manifest=await readJson<Manifest>(manifestPath);const modelsText=await readText(path.join(root,'models.json'));const planText=await readText(path.join(root,'prompt_plan.json'));const brief=await readJson<{project?:{id?:string}}>(path.join(root,'project_brief.json'));
 if(!templateText||!manifest||!modelsText||!planText||!brief?.project?.id)throw new Error('Compiler inputs are incomplete.'); const models=parseModels(modelsText);const plan=parsePromptPlan(planText);if(!models||!plan)throw new Error('models.json / prompt_plan.json parse failed.');
 const mv=validateModels(models);const pv=validatePromptPlan(plan,models);issues.push(...mv.issues,...pv.issues); if(!mv.valid||!pv.valid)return {ok:false,branchCount:plan.branches.length,imageCount:plan.branches.reduce((n,b)=>n+b.leaves.length,0),issues};
 const actualHash=hashText(templateText);if(actualHash!==manifest.template.sha256){issues.push({severity:'error',code:'TEMPLATE_HASH',message:'Template SHA-256 がManifestと一致しません。'});return {ok:false,branchCount:plan.branches.length,imageCount:plan.branches.reduce((n,b)=>n+b.leaves.length,0),issues};}
 const w=JSON.parse(templateText) as Workflow;issues.push(...validateManifest(manifest,w));if(issues.some(i=>i.severity==='error'))return {ok:false,branchCount:plan.branches.length,imageCount:plan.branches.reduce((n,b)=>n+b.leaves.length,0),issues};
 patchCheckpoint(nodeById(w,manifest.common.roles.checkpoint.nodeId),models);patchLoras(nodeById(w,manifest.common.roles.rootLoraStack.nodeId),plan.rootLoras,models);patchCommon(nodeById(w,manifest.common.roles.planCommonPrompt.nodeId),plan);
 patchBranch(w,manifest,plan.branches[0],models,brief.project.id); for(let i=1;i<plan.branches.length;i++){const maps=cloneBranch(w,manifest,i);patchBranch(w,manifest,plan.branches[i],models,brief.project.id,maps.nodeMap,maps.groupMap);}
 const outputPath=path.join(root,`LoRA_${brief.project.id}.json`);await writeJsonAtomic(outputPath,w); const imageCount=plan.branches.reduce((n,b)=>n+b.leaves.length,0);return {ok:true,outputPath,branchCount:plan.branches.length,imageCount,nodeCount:w.nodes.length,linkCount:w.links.length,issues};
 }catch(e){issues.push({severity:'error',code:'COMPILE_EXCEPTION',message:e instanceof Error?e.message:String(e)});return {ok:false,branchCount:0,imageCount:0,issues};}}
