import { app, BaseWindow, clipboard, dialog, ipcMain, shell, WebContentsView } from 'electron';
import type { WebContents } from 'electron';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { IPC } from '../shared/ipc.js';
import type { CatalogSelectionTemplateInput, GrokPaneState, ProjectBriefInput, ProjectSettings, PromptPlanArtifact, GrokTask } from '../shared/types.js';
import { createProject, confirmArtifact, importGrok, readArtifact, beginEditArtifact, saveDraft, savePromptPlan, saveProjectBrief } from './artifact-service.js';
import { scanProject } from './project-scan.js';
import { readProjectMeta, saveProjectSettings } from './project-meta.js';
import { buildGrokTask } from './grok-context.js';
import { catalogStatus } from './model-catalog.js';
import { compileWorkflow } from './compiler.js';
import { checkAvailability } from './availability.js';
import { runPreflight } from './preflight.js';
import { GROK_PARTITION, isGrokNavigationUrl, isOAuthPopupUrl, isSafeExternalUrl, isSecureWebUrl } from './grok-navigation.js';
import { CivitaiCatalogService } from './civitai-catalog.js';
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename);const GROK_URL='https://grok.com/';let mainWindow:BaseWindow|null=null,localView:WebContentsView|null=null,grokView:WebContentsView|null=null,grokVisible=false,localRatio=.45,civitaiCatalog:CivitaiCatalogService|null=null;
function state():GrokPaneState{return {visible:grokVisible,ratio:localRatio}}
function layout(){if(!mainWindow||!localView||!grokView)return;const {width,height}=mainWindow.getContentBounds();if(!grokVisible||width<840){localView.setBounds({x:0,y:0,width,height});grokView.setBounds({x:width,y:0,width:0,height});return;}const lw=Math.max(420,Math.min(width-420,Math.round(width*localRatio)));localView.setBounds({x:0,y:0,width:lw,height});grokView.setBounds({x:lw,y:0,width:width-lw,height});}
async function loadRenderer(v:WebContentsView){const dev=process.env.VITE_DEV_SERVER_URL;if(dev)await v.webContents.loadURL(dev);else await v.webContents.loadFile(path.resolve(__dirname,'../../dist-renderer/index.html'));}
function configureGrokContents(contents:WebContents,oauthFlow=false){contents.setWindowOpenHandler(({url})=>{const startsOAuth=isOAuthPopupUrl(url);if(startsOAuth||isGrokNavigationUrl(url)||(oauthFlow&&isSecureWebUrl(url))){return {action:'allow',overrideBrowserWindowOptions:{width:560,height:760,autoHideMenuBar:true,webPreferences:{partition:GROK_PARTITION,contextIsolation:true,nodeIntegration:false,sandbox:true}}};}if(isSafeExternalUrl(url))void shell.openExternal(url);return {action:'deny'};});contents.on('will-navigate',(e,url)=>{const allow=oauthFlow?isSecureWebUrl(url):isGrokNavigationUrl(url);if(!allow){e.preventDefault();if(isSafeExternalUrl(url))void shell.openExternal(url);}});contents.on('did-create-window',(window,details)=>configureGrokContents(window.webContents,oauthFlow||isOAuthPopupUrl(details.url)));}
function createWindow(){mainWindow=new BaseWindow({width:1540,height:920,minWidth:900,minHeight:640,title:'ComfyUI Batch Studio'});localView=new WebContentsView({webPreferences:{preload:path.resolve(__dirname,'../preload/index.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});grokView=new WebContentsView({webPreferences:{partition:GROK_PARTITION,contextIsolation:true,nodeIntegration:false,sandbox:true}});mainWindow.contentView.addChildView(localView);mainWindow.contentView.addChildView(grokView);configureGrokContents(grokView.webContents);mainWindow.on('resize',layout);mainWindow.on('closed',()=>{localView?.webContents.close();grokView?.webContents.close();mainWindow=null;localView=null;grokView=null});layout();void loadRenderer(localView);void grokView.webContents.loadURL(GROK_URL);}
function validRoot(x:unknown):asserts x is string{if(typeof x!=='string'||!x.trim())throw new Error('Invalid project root.');}
function catalogService(){if(!civitaiCatalog)throw new Error('Civitai Catalog Serviceが初期化されていません。');return civitaiCatalog}
async function scanWithCatalog(root:string){const service=catalogService(),meta=await readProjectMeta(root);if(!meta?.settings.catalogPath?.trim())await saveProjectSettings(root,{catalogPath:service.catalogPath});return scanProject(root)}
function validCivitaiUrl(value:unknown){if(typeof value!=='string')return false;try{const u=new URL(value),host=u.hostname.toLowerCase();return u.protocol==='https:'&&(host==='civitai.com'||host.endsWith('.civitai.com'))}catch{return false}}
function register(){ipcMain.handle(IPC.PROJECT_SELECT,async()=>{const r=await dialog.showOpenDialog({title:'プロジェクトフォルダーを選択',properties:['openDirectory']});return r.canceled?null:scanWithCatalog(r.filePaths[0]);});ipcMain.handle(IPC.PROJECT_SELECT_PARENT,async()=>{const r=await dialog.showOpenDialog({title:'作成先フォルダーを選択',properties:['openDirectory','createDirectory']});return r.canceled?null:r.filePaths[0]});ipcMain.handle(IPC.PROJECT_CREATE,async(_e,parent:unknown,brief:ProjectBriefInput)=>{if(typeof parent!=='string')throw new Error('Invalid parent path');return scanWithCatalog(await createProject(parent,brief));});ipcMain.handle(IPC.PROJECT_SCAN,(_e,root:unknown)=>{validRoot(root);return scanProject(root)});ipcMain.handle(IPC.PROJECT_OPEN_FOLDER,async(_e,root:unknown)=>{validRoot(root);const err=await shell.openPath(root);if(err)throw new Error(err)});ipcMain.handle(IPC.PROJECT_SAVE_SETTINGS,async(_e,root:unknown,settings:ProjectSettings)=>{validRoot(root);await saveProjectSettings(root,settings);return scanProject(root)});ipcMain.handle(IPC.PROJECT_SAVE_BRIEF,async(_e,root:unknown,brief:ProjectBriefInput)=>{validRoot(root);await saveProjectBrief(root,brief);return scanProject(root)});
 ipcMain.handle(IPC.ARTIFACT_READ,(_e,root:unknown,key:any,source:any)=>{validRoot(root);return readArtifact(root,key,source)});ipcMain.handle(IPC.ARTIFACT_BEGIN_EDIT,(_e,root:unknown,key:any)=>{validRoot(root);return beginEditArtifact(root,key)});ipcMain.handle(IPC.ARTIFACT_SAVE_DRAFT,(_e,root:unknown,key:any,content:unknown)=>{validRoot(root);if(typeof content!=='string')throw new Error('Invalid content');return saveDraft(root,key,content)});ipcMain.handle(IPC.ARTIFACT_IMPORT_GROK,(_e,root:unknown,key:any,raw:unknown)=>{validRoot(root);if(typeof raw!=='string')throw new Error('Invalid Grok response');return importGrok(root,key,raw)});ipcMain.handle(IPC.ARTIFACT_CONFIRM,async(_e,root:unknown,key:any)=>{validRoot(root);await confirmArtifact(root,key);return scanProject(root)});ipcMain.handle(IPC.PROMPT_PLAN_SAVE,(_e,root:unknown,plan:PromptPlanArtifact)=>{validRoot(root);return savePromptPlan(root,plan)});
 ipcMain.handle(IPC.GROK_TASK_BUILD,(_e,root:unknown,stage:GrokTask['stage'],extra:unknown)=>{validRoot(root);return buildGrokTask(root,stage,typeof extra==='string'?extra:'')});ipcMain.handle(IPC.FILE_SHOW_IN_FOLDER,(_e,filePath:unknown)=>{if(typeof filePath!=='string'||!path.isAbsolute(filePath))throw new Error('Invalid file path');shell.showItemInFolder(filePath)});
 ipcMain.handle(IPC.CATALOG_STATUS,(_e,root:unknown)=>{validRoot(root);return catalogStatus(root)});ipcMain.handle(IPC.CATALOG_INTEGRATED_STATUS,()=>catalogService().status());ipcMain.handle(IPC.CATALOG_INTEGRATED_SNAPSHOT,()=>catalogService().catalog());ipcMain.handle(IPC.CATALOG_INTEGRATED_SYNC,()=>catalogService().startSync());ipcMain.handle(IPC.CATALOG_LINK_PROJECT,async(_e,root:unknown)=>{validRoot(root);await saveProjectSettings(root,{catalogPath:catalogService().catalogPath});return scanProject(root)});ipcMain.handle(IPC.CATALOG_TEMPLATES,()=>catalogService().templates());ipcMain.handle(IPC.CATALOG_SAVE_TEMPLATE,(_e,input:CatalogSelectionTemplateInput)=>catalogService().saveTemplate(input));ipcMain.handle(IPC.CATALOG_DELETE_TEMPLATE,(_e,id:unknown)=>{if(typeof id!=='string'||!id)throw new Error('Invalid template id');return catalogService().deleteTemplate(id)});ipcMain.handle(IPC.CATALOG_OPEN_MODEL,async(_e,url:unknown)=>{if(!validCivitaiUrl(url))throw new Error('Civitai URLが不正です。');await shell.openExternal(url as string)});
 ipcMain.handle(IPC.WORKFLOW_COMPILE,(_e,root:unknown)=>{validRoot(root);return compileWorkflow(root)});ipcMain.handle(IPC.AVAILABILITY_CHECK,(_e,root:unknown)=>{validRoot(root);return checkAvailability(root)});ipcMain.handle(IPC.AVAILABILITY_OPEN_R2,async(_e,root:unknown)=>{validRoot(root);const p=(await scanProject(root)).meta?.settings.r2FileManagerUrl;if(!p)throw new Error('R2 File Manager URLが設定されていません。');if(!isSafeExternalUrl(p))throw new Error('R2 File Manager URLが不正です。');await shell.openExternal(p)});ipcMain.handle(IPC.PREFLIGHT_RUN,(_e,root:unknown)=>{validRoot(root);return runPreflight(root)});
 ipcMain.handle(IPC.CLIPBOARD_WRITE_TEXT,(_e,text:unknown)=>{if(typeof text!=='string')throw new Error('Clipboard text must be string');clipboard.writeText(text)});ipcMain.handle(IPC.GROK_SET_VISIBLE,(_e,v:unknown)=>{grokVisible=v===true;layout();return state()});ipcMain.handle(IPC.GROK_SET_RATIO,(_e,r:unknown)=>{if(typeof r!=='number'||!Number.isFinite(r))throw new Error('Invalid ratio');localRatio=Math.max(.3,Math.min(.7,r));layout();return state()});ipcMain.handle(IPC.GROK_RELOAD,()=>grokView?.webContents.reload());ipcMain.handle(IPC.GROK_OPEN_EXTERNAL,()=>shell.openExternal(GROK_URL));}
app.whenReady().then(async()=>{civitaiCatalog=new CivitaiCatalogService(path.join(app.getPath('userData'),'civitai'));await civitaiCatalog.initialize();register();createWindow();app.on('activate',()=>{if(!mainWindow)createWindow()})});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
