import path from 'node:path';
import type { CatalogSummary, ModelsArtifact, ProjectSettings, ValidationResult } from '../shared/types.js';
import { readJson } from './fs-utils.js';
import { readProjectSettings } from './project-meta.js';

interface CatalogRoot { schemaVersion?:number; generation?:number; generatedAt?:string; [key:string]:unknown }
function collectObjects(value:unknown,out:Record<string,unknown>[]):void { if(Array.isArray(value)){value.forEach(v=>collectObjects(v,out));return;} if(!value||typeof value!=='object')return; const o=value as Record<string,unknown>; if(Number.isInteger(o.modelId)&&Number.isInteger(o.versionId))out.push(o); Object.values(o).forEach(v=>{if(v&&typeof v==='object')collectObjects(v,out);}); }
export async function catalogPathFor(root:string):Promise<string|null>{ const settings=await readProjectSettings(root); return settings.catalogPath?.trim()||null; }
export async function getCatalogSummary(root:string):Promise<CatalogSummary>{ const catalogPath=await catalogPathFor(root); if(!catalogPath)return {path:'',schemaVersion:null,generation:null,generatedAt:null,modelCount:0,error:'モデルカタログのパスが未設定です。'}; const data=await readJson<CatalogRoot>(catalogPath); if(!data)return {path:catalogPath,schemaVersion:null,generation:null,generatedAt:null,modelCount:0,error:'モデルカタログを読み込めません。'}; const objs:Record<string,unknown>[]=[]; collectObjects(data,objs); return {path:catalogPath,schemaVersion:typeof data.schemaVersion==='number'?data.schemaVersion:null,generation:typeof data.generation==='number'?data.generation:null,generatedAt:typeof data.generatedAt==='string'?data.generatedAt:null,modelCount:objs.length}; }
function exactMatch(obj:Record<string,unknown>, s:{modelId:number;versionId:number;fileId:number;fileName:string}):boolean { if(obj.modelId!==s.modelId||obj.versionId!==s.versionId)return false; const files=Array.isArray(obj.files)?obj.files:[]; return files.some((f)=>!!f&&typeof f==='object'&&((f as Record<string,unknown>).id===s.fileId||(f as Record<string,unknown>).fileId===s.fileId)&&((f as Record<string,unknown>).name===s.fileName||(f as Record<string,unknown>).fileName===s.fileName)); }
export async function validateModelsAgainstCatalog(root:string,models:ModelsArtifact,base:ValidationResult):Promise<ValidationResult>{ const issues=[...base.issues]; const p=await catalogPathFor(root); if(!p){issues.push({severity:'error',code:'CATALOG_PATH',message:'モデルカタログのパスが未設定です。'});return {valid:false,issues};} const data=await readJson<CatalogRoot>(p); if(!data){issues.push({severity:'error',code:'CATALOG_READ',message:'model_catalog.jsonを読み込めません。'});return {valid:false,issues};} const objs:Record<string,unknown>[]=[]; collectObjects(data,objs); for(const s of [models.checkpoint,...models.loras]){ if(!objs.some(o=>exactMatch(o,s)))issues.push({severity:'error',code:'CATALOG_IDENTITY',message:`${s.ref}: Model / Version / File が現在のcatalogに存在しません。`,path:s.ref}); }
  if(typeof data.generation==='number'&&data.generation!==models.catalog.generation) issues.push({severity:'warning',code:'CATALOG_GENERATION',message:`catalog generationが ${models.catalog.generation} → ${data.generation} に変わっています。選定identityを再検証しました。`}); return {valid:!issues.some(i=>i.severity==='error'),issues}; }
