import path from 'node:path';
import type { CatalogItem, CatalogStatus, CatalogVersion, ModelCatalog, ModelsArtifact, ModelSelectionRole, ValidationIssue, ValidationResult } from '../shared/types.js';
import { fileMatchesRole, versionMatchesFamily } from '../shared/model-selection.js';
import { exists, readJson } from './fs-utils.js';
import { readProjectMeta } from './project-meta.js';
export async function catalogPathFor(root:string){const global=(process.env.BATCH_STUDIO_CATALOG_PATH??'').trim();if(global)return global;const meta=await readProjectMeta(root);return meta?.settings.catalogPath?.trim()||null;}
export async function loadCatalog(root:string):Promise<ModelCatalog|null>{const p=await catalogPathFor(root);if(!p)return null;return readJson<ModelCatalog>(path.resolve(p));}
export async function catalogStatus(root:string):Promise<CatalogStatus>{const p=await catalogPathFor(root);if(!p)return {configured:false,path:null,exists:false,itemCount:0};const absolute=path.resolve(p);if(!(await exists(absolute)))return {configured:true,path:absolute,exists:false,itemCount:0,error:'model_catalog.jsonが見つかりません。'};const c=await readJson<ModelCatalog>(absolute);if(!c)return {configured:true,path:absolute,exists:true,itemCount:0,error:'model_catalog.jsonを解析できません。'};const count=(c.collections??[]).reduce((n,x)=>n+(x.items?.length??0),0);return {configured:true,path:absolute,exists:true,itemCount:count,schemaVersion:c.schemaVersion,generation:c.generation,generatedAt:c.generatedAt};}
function findItem(c:ModelCatalog,modelId:number){for(const collection of c.collections??[]){const item=collection.items?.find(x=>x.modelId===modelId);if(item)return item;}return null;}
function versionAndFile(item:CatalogItem,versionId:number,fileId:number):{version:CatalogVersion;file:CatalogVersion['files'][number]}|null{const version=(item.versions??[]).find(v=>v.versionId===versionId)??(item.versionId===versionId?{versionId:item.versionId,versionName:item.versionName,files:item.files,trainedWords:item.trainedWords,modelUrl:item.modelUrl,thumbnailUrl:item.thumbnailUrl,thumbnailWidth:item.thumbnailWidth,thumbnailHeight:item.thumbnailHeight}:null);if(!version)return null;const file=(version.files??[]).find(f=>f.id===fileId);return file?{version,file}:null;}
export async function validateModelsAgainstCatalog(root:string,m:ModelsArtifact,base:ValidationResult):Promise<ValidationResult>{const issues:ValidationIssue[]=[...base.issues];const c=await loadCatalog(root);if(!c){issues.push({severity:'error',code:'CATALOG_MISSING',message:'モデルカタログが設定されていません。'});return {valid:false,issues};}if(c.generation!==m.catalog.generation)issues.push({severity:'warning',code:'CATALOG_GENERATION_CHANGED',message:`カタログgenerationが ${m.catalog.generation} → ${c.generation} に変わっています。選定identityを再検証しました。`});const baseSelection=m.schemaVersion===5&&m.modelFamily==='anima'?m.diffusionModel:m.checkpoint;const selections:Array<{role:ModelSelectionRole;selection:any}>=[...(baseSelection?[{role:'checkpoint' as const,selection:baseSelection}]:[]),...(m.schemaVersion===2&&m.textEncoder?[{role:'text_encoder' as const,selection:m.textEncoder}]:[]),...(m.schemaVersion===2&&m.clip?[{role:'clip' as const,selection:m.clip}]:[]),...m.loras.map(x=>({role:'lora' as const,selection:x}))];for(const {role,selection:s} of selections){const item=findItem(c,s.modelId);if(!item){issues.push({severity:'error',code:'MODEL_NOT_FOUND',message:`catalogにmodelId=${s.modelId}がありません。`,path:s.ref});continue;}const vf=versionAndFile(item,s.versionId,s.fileId);if(!vf){issues.push({severity:'error',code:'VERSION_FILE_NOT_FOUND',message:`${s.ref} のversion/file identityがcatalogにありません。`,path:s.ref});continue;}if(vf.file.name!==s.fileName)issues.push({severity:'error',code:'FILE_NAME_MISMATCH',message:`${s.ref} のfileNameがcatalogと一致しません。`,path:s.ref});if(item.modelName!==s.modelName)issues.push({severity:'warning',code:'MODEL_NAME_CHANGED',message:`${s.ref} のモデル名がcatalog側で変更されています。`,path:s.ref});if(m.schemaVersion>=2){if(!fileMatchesRole(item,vf.file,role))issues.push({severity:'error',code:'MODEL_ROLE_MISMATCH',message:`${s.ref} は ${role} 用のCivitaiモデルではありません。`,path:s.ref});if(role!=='lora'&&m.modelFamily&&!versionMatchesFamily(vf.version,m.modelFamily))issues.push({severity:'error',code:'MODEL_FAMILY_MISMATCH',message:`${s.ref} のbaseModelが ${m.modelFamily} と一致しません。`,path:s.ref});}}return {valid:!issues.some(x=>x.severity==='error'),issues};}
