import path from 'node:path';
import type { ModelsArtifact, PreflightResult, PromptPlanArtifact, ValidationIssue } from '../shared/types.js';
import { exists, readJson } from './fs-utils.js';
import { scanProject } from './project-scan.js';
import { validateModels, validatePromptPlan } from './validation.js';
import { validateModelsAgainstCatalog } from './model-catalog.js';
import { checkAvailability } from './availability.js';
export async function runPreflight(root:string,r2Lookup?:((fileName:string)=>Promise<boolean>)|null,localModelsRoot?:string|null):Promise<PreflightResult>{const project=await scanProject(root);const sections:PreflightResult['sections']=[];const block:ValidationIssue[]=[];const warn:ValidationIssue[]=[];const add=(name:string,issues:ValidationIssue[])=>{sections.push({name,valid:!issues.some(i=>i.severity==='error'),issues});block.push(...issues.filter(i=>i.severity==='error'));warn.push(...issues.filter(i=>i.severity==='warning'));};
 for(const a of project.artifacts){if(a.state==='stale'&&['story','models','promptPlan','workflow'].includes(a.key))block.push({severity:'error',code:'ARTIFACT_STALE',message:`${a.label} は上流Artifact更新後に再確定/再生成が必要です。`,path:a.key});}
 const storyExists=await exists(path.join(root,'story.md'));add('ストーリー',storyExists?[]:[{severity:'error',code:'STORY_MISSING',message:'story.mdが確定していません。'}]);const models=await readJson<ModelsArtifact>(path.join(root,'models.json'));if(!models)add('モデル選定',[{severity:'error',code:'MODELS_MISSING',message:'models.jsonが確定していません。'}]);else{const v=validateModels(models);add('モデル選定',v.valid?(await validateModelsAgainstCatalog(root,models,v)).issues:v.issues);}const plan=await readJson<PromptPlanArtifact>(path.join(root,'prompt_plan.json'));if(!plan)add('プロンプト設計',[{severity:'error',code:'PLAN_MISSING',message:'prompt_plan.jsonが確定していません。'}]);else add('プロンプト設計',validatePromptPlan(plan,models).issues);const workflowName=project.artifacts.find(a=>a.key==='workflow')?.relativePath;add('ワークフロー',workflowName?[]:[{severity:'error',code:'WORKFLOW_MISSING',message:'ワークフローが生成されていません。'}]);const av=await checkAvailability(root,r2Lookup,localModelsRoot);add('モデル配置',av.validation.issues);const planned=plan?plan.branches.reduce((n,b)=>n+b.leaves.length,0):0;if(project.targetImageCount!=null&&planned&&planned!==project.targetImageCount)warn.push({severity:'warning',code:'TARGET_DELTA',message:`目標${project.targetImageCount}枚 / 現在${planned}枚です。`});const uniqueBlock=block.filter((x,i,a)=>a.findIndex(y=>y.code===x.code&&y.path===x.path&&y.message===x.message)===i);return {state:uniqueBlock.length?'BLOCKED':'READY',plannedImages:planned,targetImages:project.targetImageCount,blocking:uniqueBlock,warnings:warn,sections};}
