import path from 'node:path';
import type { PreflightResult, ValidationIssue } from '../shared/types.js';
import { readText, exists } from './fs-utils.js';
import { parseModels, parsePromptPlan, validateModels, validatePromptPlan } from './validation.js';
import { validateModelsAgainstCatalog } from './model-catalog.js';
import { checkAvailability } from './availability.js';
import { scanProject } from './project-scan.js';

export async function runPreflight(root:string):Promise<PreflightResult>{ const blocking:ValidationIssue[]=[]; const warnings:ValidationIssue[]=[]; const checks:PreflightResult['checks']=[];
 const story=await readText(path.join(root,'story.md')); checks.push({key:'story',label:'ストーリー',ok:!!story?.trim(),detail:story?.trim()?'確定済み':'story.mdがありません'}); if(!story?.trim())blocking.push({severity:'error',code:'STORY_MISSING',message:'確定済みstory.mdがありません。',path:'story'});
 const modelsText=await readText(path.join(root,'models.json')); const models=modelsText?parseModels(modelsText):null; if(!models){blocking.push({severity:'error',code:'MODELS_MISSING',message:'確定済みmodels.jsonがありません。',path:'models'});checks.push({key:'models',label:'モデル選定',ok:false,detail:'models.jsonがありません'});} else {const v=await validateModelsAgainstCatalog(root,models,validateModels(models)); v.issues.forEach(i=>(i.severity==='error'?blocking:warnings).push(i)); checks.push({key:'models',label:'モデル選定',ok:v.valid,detail:v.valid?'検証済み':'検証エラーあり'});}
 const planText=await readText(path.join(root,'prompt_plan.json')); const plan=planText?parsePromptPlan(planText):null; let imageCount=0; if(!plan){blocking.push({severity:'error',code:'PLAN_MISSING',message:'確定済みprompt_plan.jsonがありません。',path:'promptPlan'});checks.push({key:'promptPlan',label:'プロンプト設計',ok:false,detail:'prompt_plan.jsonがありません'});} else {imageCount=plan.branches.reduce((n,b)=>n+b.leaves.length,0); const v=validatePromptPlan(plan,models); v.issues.forEach(i=>(i.severity==='error'?blocking:warnings).push(i)); checks.push({key:'promptPlan',label:'プロンプト設計',ok:v.valid,detail:`${imageCount}枚予定`});}
 const project=await scanProject(root); const workflowName=plan&&models&&project.id?`LoRA_${project.id}.json`:''; const workflow=workflowName?await exists(path.join(root,workflowName)):false; checks.push({key:'workflow',label:'ワークフロー',ok:workflow,detail:workflow?'生成済み':'未生成'}); if(!workflow)blocking.push({severity:'error',code:'WORKFLOW_MISSING',message:'最新ワークフローが生成されていません。',path:'workflow'});
 const availability=await checkAvailability(root); const unavailable=availability.filter(i=>!i.local); const avOk=availability.length>0&&unavailable.length===0; checks.push({key:'availability',label:'モデル配置',ok:avOk,detail:availability.length?`${availability.length-unavailable.length}/${availability.length} 利用可能`:'モデル情報なし'}); unavailable.forEach(i=>blocking.push({severity:'error',code:'MODEL_UNAVAILABLE',message:`${i.fileName} がLocal生成環境にありません。`,path:'availability'}));
 const brief=await (await import('./fs-utils.js')).readJson<{generation?:{target_image_count?:number|null}}>(path.join(root,'project_brief.json')); const target=brief?.generation?.target_image_count; if(target&&imageCount&&target!==imageCount)warnings.push({severity:'warning',code:'TARGET_DELTA',message:`目標${target}枚に対して現在${imageCount}枚です（差 ${imageCount-target>=0?'+':''}${imageCount-target}）。`});
 return {ready:blocking.length===0,imageCount,blocking,warnings,checks}; }
