import { readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import type { ArtifactKey, ArtifactState, ArtifactSummary, ProjectBriefInput, ProjectSummary } from '../shared/types.js';
import { readJson } from './fs-utils.js';
import { readProjectMeta } from './project-meta.js';
import { readArtifact } from './artifact-service.js';
const defs:Array<[ArtifactKey,string,string]>=[['projectBrief','基本設定','project_brief.json'],['story','ストーリー','story.md'],['models','モデル選定','models.json'],['promptPlan','プロンプト設計','prompt_plan.json']];
async function mtime(p:string){try{return (await stat(p)).mtimeMs}catch{return 0}}
export async function scanProject(root:string):Promise<ProjectSummary>{const entries=await readdir(root,{withFileTypes:true});const names=new Set(entries.filter(e=>e.isFile()).map(e=>e.name));const brief=await readJson<{schemaVersion?:number}&ProjectBriefInput>(path.join(root,'project_brief.json'));const meta=await readProjectMeta(root);const artifacts:ArtifactSummary[]=[];
 for(const [key,label,file] of defs){const confirmed=await readArtifact(root,key,'confirmed');let state:ArtifactState='missing';if(confirmed.exists)state=confirmed.validation.valid?(confirmed.validation.issues.some(x=>x.severity==='warning')?'warning':'confirmed'):'invalid';else if(key!=='projectBrief'){const draft=await readArtifact(root,key,'draft');if(draft.exists)state=draft.validation.valid?'draft':'invalid';}artifacts.push({key,label,relativePath:names.has(file)?file:null,state,validation:confirmed.exists?confirmed.validation:undefined});}
 const briefT=await mtime(path.join(root,'project_brief.json')),storyT=await mtime(path.join(root,'story.md')),modelsT=await mtime(path.join(root,'models.json')),planT=await mtime(path.join(root,'prompt_plan.json'));
 const storyA=artifacts.find(a=>a.key==='story');if(storyA&&storyT&&briefT>storyT&&['confirmed','warning'].includes(storyA.state))storyA.state='stale';
 const modelsA=artifacts.find(a=>a.key==='models');if(modelsA&&modelsT&&Math.max(briefT,storyT)>modelsT&&['confirmed','warning'].includes(modelsA.state))modelsA.state='stale';
 const planA=artifacts.find(a=>a.key==='promptPlan');if(planA&&planT&&Math.max(briefT,storyT,modelsT)>planT&&['confirmed','warning'].includes(planA.state))planA.state='stale';
 const workflow=[...names].find(n=>/^LoRA_.+\.json$/i.test(n))??null;let workflowState:ArtifactState=workflow?'generated':'missing';if(workflow){const wt=await mtime(path.join(root,workflow));if(Math.max(briefT,storyT,modelsT,planT)>wt||artifacts.some(a=>['story','models','promptPlan'].includes(a.key)&&a.state==='stale'))workflowState='stale';}artifacts.push({key:'workflow',label:'ワークフロー',relativePath:workflow,state:workflowState});artifacts.push({key:'legacyPromptTree',label:'旧 Prompt Tree',relativePath:names.has('prompt_tree.md')?'prompt_tree.md':null,state:names.has('prompt_tree.md')?'legacy':'missing'});return {rootPath:root,title:brief?.project?.title?.trim()||path.basename(root),id:brief?.project?.id??null,targetImageCount:brief?.generation?.target_image_count??null,artifacts,meta};}
