import { randomUUID } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import path from 'node:path';
import {
  AbortMultipartUploadCommand, CompleteMultipartUploadCommand, CopyObjectCommand, CreateBucketCommand,
  CreateMultipartUploadCommand, DeleteBucketCommand, DeleteObjectCommand, DeleteObjectsCommand,
  GetObjectCommand, HeadObjectCommand, ListBucketsCommand, ListObjectsV2Command, PutObjectCommand,
  S3Client, UploadPartCommand, UploadPartCopyCommand,
} from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import type { R2BatchDownloadTemplate, R2DownloadInfo, R2ListResult, R2Object, R2SearchResult, R2UploadJob } from '../shared/types.js';
import { exists, readJson, writeJsonAtomic } from './fs-utils.js';
import { R2ConfigStore, type R2ConnectionInput } from './r2-config.js';

const MIB=1024*1024, DEFAULT_PART=16*MIB, MAX_PARTS=10000, FIVE_GIB=5*1024*1024*1024;
const BUCKET=/^[a-z0-9](?:[a-z0-9-]{1,61}[a-z0-9])?$/;
function partSize(size:number){const required=Math.max(DEFAULT_PART,Math.ceil(Math.max(size,1)/MAX_PARTS));return Math.ceil(required/MIB)*MIB;}
function objectName(key:string){return key.split('/').pop()||'download';}
function encodeKey(key:string){return key.split('/').map(encodeURIComponent).join('/');}
function publicObjectUrl(base:string,key:string){return `${base.replace(/\/+$/,'')}/${encodeKey(key)}`;}
function quote(value:string){return `"${value.replace(/(["\\$`])/g,'\\$1')}"`;}
function uniqueNames(keys:string[]){const used=new Map<string,number>();return keys.map(key=>{const raw=objectName(key),lower=raw.toLowerCase(),count=(used.get(lower)??0)+1;used.set(lower,count);if(count===1)return raw;const dot=raw.lastIndexOf('.');return dot>0?`${raw.slice(0,dot)} (${count})${raw.slice(dot)}`:`${raw} (${count})`;});}
function serializeObject(item:any,prefix=''):R2Object{const key=String(item.Key??'');return {key,name:prefix&&key.startsWith(prefix)?key.slice(prefix.length):objectName(key),size:Number(item.Size??0),etag:String(item.ETag??'').replace(/^"|"$/g,''),lastModified:item.LastModified?.toISOString?.()??null,storageClass:String(item.StorageClass??'STANDARD')};}
function statusCode(error:any){return Number(error?.$metadata?.httpStatusCode??0);}

interface UploadState {schemaVersion:1;jobs:R2UploadJob[]}
interface TemplateState {schemaVersion:1;templates:R2BatchDownloadTemplate[]}

export class R2Manager {
  private clientCache:{key:string;client:S3Client}|null=null;
  private readonly uploadsPath:string;
  private readonly templatesPath:string;
  private controls=new Map<string,{paused:boolean;cancelled:boolean}>();
  constructor(private readonly config:R2ConfigStore,private readonly userData:string){this.uploadsPath=path.join(userData,'r2','uploads.json');this.templatesPath=path.join(userData,'r2','batch-download-templates.json');}
  async settings(){return this.config.status();}
  environment(){return this.config.environmentDefaults();}
  async saveSettings(input:R2ConnectionInput){await this.test(input);this.clientCache=null;return this.config.save(input);}
  private async clientFor(input?:R2ConnectionInput){const c=input??await this.config.credentials();const secret=(c.secretAccessKey??'').trim();if(!secret)throw new Error('Secret Access Keyが必要です。');const key=`${c.accountId}|${c.accessKeyId}|${secret}`;if(!input&&this.clientCache?.key===key)return this.clientCache.client;const client=new S3Client({endpoint:`https://${c.accountId}.r2.cloudflarestorage.com`,region:'auto',credentials:{accessKeyId:c.accessKeyId,secretAccessKey:secret},maxAttempts:5});if(!input)this.clientCache={key,client};return client;}
  async test(input:R2ConnectionInput){const resolved=await this.config.resolveInput(input);const client=await this.clientFor(resolved);await client.send(new ListBucketsCommand({}));}
  async buckets(){const r=await (await this.clientFor()).send(new ListBucketsCommand({}));return (r.Buckets??[]).map(x=>({name:x.Name??'',createdAt:x.CreationDate?.toISOString()??null})).filter(x=>x.name);}
  async createBucket(name:string){if(!BUCKET.test(name))throw new Error('バケット名は3～63文字の小文字、数字、ハイフンで入力してください。');await (await this.clientFor()).send(new CreateBucketCommand({Bucket:name}));}
  async deleteBucket(name:string){const client=await this.clientFor();const probe=await client.send(new ListObjectsV2Command({Bucket:name,MaxKeys:1}));if((probe.KeyCount??0)>0)throw new Error('ファイルが存在するバケットは削除できません。');await client.send(new DeleteBucketCommand({Bucket:name}));}
  async list(bucket:string,prefix='',token?:string|null):Promise<R2ListResult>{if(!bucket)throw new Error('バケットを指定してください。');const r=await (await this.clientFor()).send(new ListObjectsV2Command({Bucket:bucket,Prefix:prefix,Delimiter:'/',MaxKeys:500,ContinuationToken:token||undefined}));return {folders:(r.CommonPrefixes??[]).map(x=>x.Prefix??'').filter(Boolean).map(p=>({prefix:p,name:p.slice(prefix.length).replace(/\/$/, '')})),objects:(r.Contents??[]).filter(x=>x.Key&&x.Key!==prefix&&!x.Key.endsWith('/')).map(x=>serializeObject(x,prefix)),nextToken:r.NextContinuationToken??null};}
  async search(bucket:string,query:string,token?:string|null):Promise<R2SearchResult>{const q=query.trim().toLowerCase();if(!q)throw new Error('検索文字列を入力してください。');const client=await this.clientFor();let continuation=token||undefined,scanned=0;const objects:R2Object[]=[];for(let page=0;page<10&&scanned<1000&&objects.length<100;page++){const r=await client.send(new ListObjectsV2Command({Bucket:bucket,MaxKeys:Math.min(100,1000-scanned),ContinuationToken:continuation}));scanned+=(r.Contents??[]).length;for(const item of r.Contents??[]){if(item.Key&&!item.Key.endsWith('/')&&item.Key.toLowerCase().includes(q))objects.push(serializeObject(item));if(objects.length>=100)break;}continuation=r.NextContinuationToken;if(!continuation)break;}return {objects,nextToken:continuation??null,scanned};}
  private async signed(bucket:string,key:string,expiresIn=3600){const settings=await this.config.credentials();if(settings.publicUrl)return {url:publicObjectUrl(settings.publicUrl,key),public:true,expiresIn:null as number|null};const url=await getSignedUrl(await this.clientFor(),new GetObjectCommand({Bucket:bucket,Key:key}),{expiresIn});return {url,public:false,expiresIn};}
  private info(key:string,url:string,isPublic:boolean,expiresIn:number|null,fileName=objectName(key)):R2DownloadInfo{return {key,url,public:isPublic,expiresIn,fileName,commands:{url,curl:`curl -L --fail --output ${quote(fileName)} ${quote(url)}`,wget:`wget -O ${quote(fileName)} ${quote(url)}`,aria2c:`aria2c -o ${quote(fileName)} ${quote(url)}`}};}
  async downloadInfo(bucket:string,key:string,expiresIn=3600){const d=await this.signed(bucket,key,expiresIn);return this.info(key,d.url,d.public,d.expiresIn);}
  async batchDownloadInfo(bucket:string,keys:string[],expiresIn=3600){if(!keys.length||keys.length>500)throw new Error('一度に生成できるダウンロードURLは1～500件です。');const names=uniqueNames(keys);return Promise.all(keys.map(async(key,i)=>{const d=await this.signed(bucket,key,expiresIn);return this.info(key,d.url,d.public,d.expiresIn,names[i]);}));}
  async deleteObjects(bucket:string,keys:string[]){if(!keys.length)throw new Error('削除するファイルを選択してください。');if(keys.length>1000)throw new Error('一度に削除できるのは1,000件までです。');const r=await (await this.clientFor()).send(new DeleteObjectsCommand({Bucket:bucket,Delete:{Objects:keys.map(Key=>({Key})),Quiet:false}}));return {deleted:(r.Deleted??[]).map(x=>x.Key??'').filter(Boolean),errors:r.Errors??[]};}
  async move(bucket:string,sourceKey:string,destinationKey:string,overwrite=false){if(!sourceKey||!destinationKey||sourceKey===destinationKey)throw new Error('移動元と異なる移動先を指定してください。');const client=await this.clientFor();if(!overwrite){try{await client.send(new HeadObjectCommand({Bucket:bucket,Key:destinationKey}));throw new Error('移動先に同名のファイルが存在します。');}catch(e:any){if(e instanceof Error&&e.message.includes('同名'))throw e;if(statusCode(e)!==404&&e?.name!=='NotFound')throw e;}}
    const head=await client.send(new HeadObjectCommand({Bucket:bucket,Key:sourceKey})),size=Number(head.ContentLength??0),copySource=`${bucket}/${encodeKey(sourceKey)}`;
    if(size<=FIVE_GIB){await client.send(new CopyObjectCommand({Bucket:bucket,Key:destinationKey,CopySource:copySource}));}
    else {const chunk=Math.max(64*MIB,partSize(size));const create=await client.send(new CreateMultipartUploadCommand({Bucket:bucket,Key:destinationKey}));if(!create.UploadId)throw new Error('Multipart copyを開始できませんでした。');try{const parts=[] as Array<{ETag?:string;PartNumber:number}>;for(let start=0,n=1;start<size;start+=chunk,n++){const end=Math.min(size-1,start+chunk-1);const p=await client.send(new UploadPartCopyCommand({Bucket:bucket,Key:destinationKey,UploadId:create.UploadId,PartNumber:n,CopySource:copySource,CopySourceRange:`bytes=${start}-${end}`}));parts.push({PartNumber:n,ETag:p.CopyPartResult?.ETag});}await client.send(new CompleteMultipartUploadCommand({Bucket:bucket,Key:destinationKey,UploadId:create.UploadId,MultipartUpload:{Parts:parts}}));}catch(e){await client.send(new AbortMultipartUploadCommand({Bucket:bucket,Key:destinationKey,UploadId:create.UploadId})).catch(()=>{});throw e;}}
    await client.send(new DeleteObjectCommand({Bucket:bucket,Key:sourceKey}));}
  private async uploadState(){return (await readJson<UploadState>(this.uploadsPath))??{schemaVersion:1 as const,jobs:[]};}
  private async saveUpload(job:R2UploadJob){const s=await this.uploadState(),i=s.jobs.findIndex(x=>x.id===job.id);if(i>=0)s.jobs[i]=job;else s.jobs.push(job);await writeJsonAtomic(this.uploadsPath,s);}
  async uploads(){const s=await this.uploadState();return s.jobs.map(j=>j.status==='uploading'?{...j,status:'paused' as const}:j);}
  async beginUpload(bucket:string,prefix:string,filePath:string,overwrite=false){if(!(await exists(filePath)))throw new Error('アップロード元ファイルが見つかりません。');const st=await stat(filePath),name=path.basename(filePath),key=`${prefix.replace(/^\/+|\/+$/g,'')}${prefix?'/' : ''}${name}`;if(Buffer.byteLength(key)>1024)throw new Error('オブジェクト名が1,024バイトを超えています。');const client=await this.clientFor();if(!overwrite){try{await client.send(new HeadObjectCommand({Bucket:bucket,Key:key}));throw new Error('同名のファイルが存在します。');}catch(e:any){if(e instanceof Error&&e.message.includes('同名'))throw e;if(statusCode(e)!==404&&e?.name!=='NotFound')throw e;}}
    let uploadId:string|null=null;if(st.size>0){const r=await client.send(new CreateMultipartUploadCommand({Bucket:bucket,Key:key,ContentType:'application/octet-stream'}));uploadId=r.UploadId??null;if(!uploadId)throw new Error('Multipart uploadを開始できませんでした。');}
    const job:R2UploadJob={id:randomUUID(),bucket,key,filePath,fileName:name,size:st.size,contentType:'application/octet-stream',uploadId,partSize:partSize(st.size),completedParts:{},status:'paused',transferredBytes:0,error:'',createdAt:new Date().toISOString()};await this.saveUpload(job);void this.resumeUpload(job.id);return job;}
  async resumeUpload(id:string){const state=await this.uploadState(),job=state.jobs.find(x=>x.id===id);if(!job)throw new Error('アップロードセッションが見つかりません。');if(job.status==='complete'||job.status==='cancelled')return job;if(!(await exists(job.filePath)))throw new Error('元ファイルが見つかりません。');const control={paused:false,cancelled:false};this.controls.set(id,control);job.status='uploading';job.error='';await this.saveUpload(job);void this.runUpload(job,control);return job;}
  private async runUpload(job:R2UploadJob,control:{paused:boolean;cancelled:boolean}){try{const client=await this.clientFor();if(job.size===0){await client.send(new PutObjectCommand({Bucket:job.bucket,Key:job.key,Body:new Uint8Array(0),ContentType:job.contentType}));job.status='complete';await this.saveUpload(job);return;}if(!job.uploadId)throw new Error('Upload IDがありません。');const count=Math.ceil(job.size/job.partSize);for(let n=1;n<=count;n++){if(control.cancelled)return;if(control.paused){job.status='paused';await this.saveUpload(job);return;}if(job.completedParts[String(n)])continue;const start=(n-1)*job.partSize,end=Math.min(job.size-1,start+job.partSize-1),length=end-start+1;const r=await client.send(new UploadPartCommand({Bucket:job.bucket,Key:job.key,UploadId:job.uploadId,PartNumber:n,Body:createReadStream(job.filePath,{start,end}),ContentLength:length}));if(!r.ETag)throw new Error(`Part ${n} のETagを取得できませんでした。`);job.completedParts[String(n)]=r.ETag;job.transferredBytes=Math.min(job.size,job.transferredBytes+length);await this.saveUpload(job);}const parts=Array.from({length:count},(_,i)=>({PartNumber:i+1,ETag:job.completedParts[String(i+1)]}));await client.send(new CompleteMultipartUploadCommand({Bucket:job.bucket,Key:job.key,UploadId:job.uploadId,MultipartUpload:{Parts:parts}}));job.status='complete';job.transferredBytes=job.size;await this.saveUpload(job);}catch(e){job.status='failed';job.error=e instanceof Error?e.message:String(e);await this.saveUpload(job);}finally{this.controls.delete(job.id);}}
  async pauseUpload(id:string){const c=this.controls.get(id);if(c)c.paused=true;const s=await this.uploadState(),job=s.jobs.find(x=>x.id===id);if(!job)throw new Error('アップロードセッションが見つかりません。');job.status='paused';await this.saveUpload(job);return job;}
  async cancelUpload(id:string){const c=this.controls.get(id);if(c)c.cancelled=true;const s=await this.uploadState(),job=s.jobs.find(x=>x.id===id);if(!job)return;if(job.uploadId)await (await this.clientFor()).send(new AbortMultipartUploadCommand({Bucket:job.bucket,Key:job.key,UploadId:job.uploadId})).catch(()=>{});job.status='cancelled';await this.saveUpload(job);}
  private async templateState(){return (await readJson<TemplateState>(this.templatesPath))??{schemaVersion:1 as const,templates:[]};}
  async templates(bucket?:string){const s=await this.templateState();return bucket?s.templates.filter(x=>x.bucket===bucket):s.templates;}
  async saveTemplate(input:{id?:string;name:string;bucket:string;objects:Array<{key:string;name:string;size?:number}>}){if(!input.name.trim()||!input.bucket||!input.objects.length||input.objects.length>500)throw new Error('テンプレート名・バケット・1～500件の対象が必要です。');const s=await this.templateState(),now=new Date().toISOString(),i=input.id?s.templates.findIndex(x=>x.id===input.id):-1;const t:R2BatchDownloadTemplate={id:input.id||randomUUID(),name:input.name.trim(),bucket:input.bucket,createdAt:i>=0?s.templates[i].createdAt:now,updatedAt:now,objects:input.objects};if(i>=0)s.templates[i]=t;else s.templates.push(t);await writeJsonAtomic(this.templatesPath,s);return s.templates;}
  async deleteTemplate(id:string){const s=await this.templateState();s.templates=s.templates.filter(x=>x.id!==id);await writeJsonAtomic(this.templatesPath,s);return s.templates;}
  async metrics(){const c=await this.config.credentials();if(!c.cloudflareApiToken)return {configured:false};const res=await fetch(`https://api.cloudflare.com/client/v4/accounts/${c.accountId}/r2/metrics`,{headers:{Authorization:`Bearer ${c.cloudflareApiToken}`,Accept:'application/json','Cache-Control':'no-cache'}});if(!res.ok)throw new Error(res.status===401||res.status===403?'Cloudflare API Tokenが無効か、R2読み取り権限がありません。':`使用量APIがエラーを返しました（HTTP ${res.status}）。`);const payload:any=await res.json();if(!payload?.success||typeof payload?.result!=='object')throw new Error(payload?.errors?.[0]?.message||'Cloudflare使用量APIから正常な応答がありません。');const result=payload.result;const value=(group:any,state:string,field:string)=>Number(group?.[state]?.[field]??0);const classes={standard:result.standard??{},infrequent_access:result.infrequentAccess??{}};const breakdown=Object.fromEntries(Object.entries(classes).map(([name,g]:any)=>{const payload=value(g,'published','payloadSize'),metadata=value(g,'published','metadataSize');return [name,{stored_bytes:payload+metadata,payload_bytes:payload,metadata_bytes:metadata,objects:value(g,'published','objects'),uploading_bytes:value(g,'uploaded','payloadSize')+value(g,'uploaded','metadataSize')}];}));const rows=Object.values(breakdown) as any[];return {configured:true,payload:{stored_bytes:rows.reduce((n,x)=>n+x.stored_bytes,0),payload_bytes:rows.reduce((n,x)=>n+x.payload_bytes,0),metadata_bytes:rows.reduce((n,x)=>n+x.metadata_bytes,0),objects:rows.reduce((n,x)=>n+x.objects,0),uploading_bytes:rows.reduce((n,x)=>n+x.uploading_bytes,0),storage_classes:breakdown}};}
}
