import { useEffect, useRef, useState } from 'react';
import type { AppSettingsStatus, ProjectBriefInput, ProjectSummary } from '../shared/types';
import { grokContextStage, stages, shouldShowGrok, statusDot, type Runner, type Stage } from './ui';
import { Overview, Settings } from './ProjectStages';
import { StoryStage, ModelsStage } from './GrokStages';
import { PromptPlanStage } from './PromptPlanStage';
import { WorkflowStage, AvailabilityStage, PreflightStage } from './ExecutionStages';
import { R2ManagerStage } from './R2ManagerStage';
import { CivitExplorerStage } from './CivitExplorerStage';
import './divider.css';

const blankBrief:ProjectBriefInput={project:{id:'',title:''},subject:{copyrightedCharacter:false,characterName:'',series:''},audience:'',request:'',exclusions:'',assumptions:{adultCharacters:false,consensual:false},generation:{target_image_count:500,modelFamily:'illustrious'},references:[]};
function hashId(value:string){let h=2166136261;for(const ch of value){h^=ch.codePointAt(0)??0;h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function suggestProjectId(title:string){const normalized=title.normalize('NFKD').toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/[-_.]{2,}/g,'-').replace(/^[-_.]+|[-_.]+$/g,'').slice(0,64);if(normalized)return normalized;return title.trim()?`project-${hashId(title).slice(0,8)}`:'';}
type StandaloneTool='r2'|'civit'|null;

function App(){
  const [project,setProject]=useState<ProjectSummary|null>(null),[recent,setRecent]=useState<ProjectSummary[]>([]),[stage,setStage]=useState<Stage>('概要'),[error,setError]=useState(''),[grok,setGrok]=useState(false),[ratio,setRatio]=useState(.45),[createOpen,setCreateOpen]=useState(false),[environmentOpen,setEnvironmentOpen]=useState(false),[restoring,setRestoring]=useState(true),[tool,setTool]=useState<StandaloneTool>(null);
  const refresh=async()=>project&&setProject(await window.batchStudio.project.scan(project.rootPath));
  const run:Runner=async fn=>{setError('');try{return await fn()}catch(e){setError(e instanceof Error?e.message:String(e));return undefined}};
  const rememberRecent=(p:ProjectSummary)=>setRecent(prev=>[p,...prev.filter(item=>item.rootPath!==p.rootPath)].slice(0,8));
  const loadRecent=async()=>setRecent(await window.batchStudio.project.recent());
  const openProject=()=>run(async()=>{const p=await window.batchStudio.project.select();if(p){setProject(p);rememberRecent(p);setTool(null)}});
  const openRecent=(root:string)=>run(async()=>{const p=await window.batchStudio.project.open(root);setProject(p);rememberRecent(p);setTool(null)});
  const closeProject=()=>run(async()=>{await window.batchStudio.project.close();setProject(null);setTool(null);setStage('概要');setGrok(false);await loadRecent()});
  useEffect(()=>{let cancelled=false;void window.batchStudio.project.recent().then(items=>{if(!cancelled)setRecent(items)}).catch(()=>{});return()=>{cancelled=true}},[]);
  useEffect(()=>{let cancelled=false;void window.batchStudio.project.last().then(p=>{if(!cancelled&&p)setProject(p)}).catch(()=>{}).finally(()=>{if(!cancelled)setRestoring(false)});return()=>{cancelled=true}},[]);
  useEffect(()=>{let cancelled=false;void (async()=>{const visible=Boolean(project&&!tool&&shouldShowGrok(stage)),context=grokContextStage(stage);if(visible&&context&&project)await window.batchStudio.grok.setContext(project.rootPath,context);const s=await window.batchStudio.grok.setVisible(visible);if(!cancelled){setGrok(s.visible);setRatio(s.ratio)}})().catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:String(e))});return()=>{cancelled=true}},[stage,project?.rootPath,tool]);
  const title=project?.title??(tool==='r2'?'R2 File Manager':tool==='civit'?'Civit Explorer':restoring?'前回のプロジェクトを復元中…':'ホーム');
  return <main className="shell"><header className="top"><div><span className="eyebrow">ComfyUI Batch Studio</span><h1>{title}</h1><small>{project?.rootPath}</small></div><div className="actions"><button onClick={()=>void openProject()}>開く</button><button onClick={()=>setCreateOpen(true)}>新規作成</button><button onClick={()=>setEnvironmentOpen(true)}>環境設定</button>{project&&<><button onClick={()=>window.batchStudio.project.openFolder(project.rootPath)}>フォルダー</button><button onClick={()=>void closeProject()}>プロジェクトを閉じる</button></>}{project&&!tool&&shouldShowGrok(stage)&&<button onClick={async()=>{const s=await window.batchStudio.grok.setVisible(!grok);setGrok(s.visible);setRatio(s.ratio)}}>{grok?'Grokを隠す':'Grokを表示'}</button>}</div></header>{error&&<div className="errorbar">{error}</div>}<div className="body">{project?<nav>{stages.map(s=><button key={s} className={!tool&&stage===s?'active':''} onClick={()=>{setTool(null);setStage(s)}}>{s}{statusDot(project,s)}</button>)}</nav>:<nav className="home-nav"><button className={tool===null?'active':''} onClick={()=>setTool(null)}>ホーム</button><button className={tool==='r2'?'active':''} onClick={()=>setTool('r2')}>R2 File Manager</button><button className={tool==='civit'?'active':''} onClick={()=>setTool('civit')}>Civit Explorer</button></nav>}<section className="workspace">{project&&!tool&&<><div className="stagehead"><h2>{stage}</h2></div><StageView project={project} stage={stage} refresh={refresh} setProject={setProject} run={run}/></>}{!project&&tool==='r2'&&<R2ManagerStage run={run}/>} {!project&&tool==='civit'&&<CivitExplorerStage run={run}/>} {!project&&!tool&&<Empty onCreate={()=>setCreateOpen(true)} onOpen={openProject} onOpenRecent={openRecent} onR2={()=>setTool('r2')} onCivit={()=>setTool('civit')} recent={recent} restoring={restoring}/>}</section></div>{grok&&<PaneDivider ratio={ratio} onRatio={setRatio}/>} {createOpen&&<CreateProject onClose={()=>setCreateOpen(false)} onCreated={p=>{setProject(p);rememberRecent(p);setTool(null);setCreateOpen(false)}} run={run}/>} {environmentOpen&&<EnvironmentSettings onClose={()=>setEnvironmentOpen(false)} run={run}/>}</main>;
}
function PaneDivider({ratio,onRatio}:{ratio:number;onRatio:(ratio:number)=>void}){const raf=useRef<number|null>(null),pending=useRef<number|null>(null);const flush=()=>{raf.current=null;const x=pending.current;if(x==null)return;pending.current=null;void window.batchStudio.grok.setDividerScreenX(x).then(s=>onRatio(s.ratio)).catch(()=>{})};const move=(e:React.PointerEvent<HTMLDivElement>)=>{if(!(e.buttons&1))return;pending.current=e.screenX;if(raf.current==null)raf.current=requestAnimationFrame(flush)};return <div className="pane-divider" role="separator" aria-orientation="vertical" aria-label={`Local ${Math.round(ratio*100)}% / Grok ${100-Math.round(ratio*100)}%`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);pending.current=e.screenX;flush()}} onPointerMove={move} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}}/>}
function Empty({onCreate,onOpen,onOpenRecent,onR2,onCivit,recent,restoring}:{onCreate:()=>void;onOpen:()=>void;onOpenRecent:(root:string)=>void;onR2:()=>void;onCivit:()=>void;recent:ProjectSummary[];restoring:boolean}){return <div className="home"><div className="empty home-start"><div className="logo">BS</div><h3>{restoring?'前回のプロジェクトを確認しています':'開始する操作を選択してください'}</h3>{!restoring&&<div className="actions home-actions"><button className="primary" onClick={onCreate}>プロジェクトを新規作成</button><button onClick={onOpen}>プロジェクトを開く</button><button onClick={onR2}>R2 File Manager</button><button onClick={onCivit}>Civit Explorer</button></div>}</div>{!restoring&&recent.length>0&&<section className="recent-projects" aria-labelledby="recent-projects-title"><div className="panelhead"><div><h3 id="recent-projects-title">最近使ったプロジェクト</h3><p>クリックするとそのままプロジェクトを開きます。</p></div></div><div className="recent-project-grid">{recent.map(p=><button key={p.rootPath} className="recent-project-card" onClick={()=>onOpenRecent(p.rootPath)}><strong>{p.title}</strong><small>{p.rootPath}</small><span>{p.targetImageCount!=null?`目標 ${p.targetImageCount} 枚`:'目標枚数未設定'}</span></button>)}</div></section>}</div>}
function CreateProject({onClose,onCreated,run}:{onClose:()=>void;onCreated:(p:ProjectSummary)=>void;run:Runner}){const [b,setB]=useState(blankBrief),[parent,setParent]=useState(''),[idTouched,setIdTouched]=useState(false);const set=(key:string,v:unknown)=>setB(prev=>{const n=structuredClone(prev) as Record<string,any>;const [a,c]=key.split('.');if(c)n[a][c]=v;else n[a]=v;return n as unknown as ProjectBriefInput});const setTitle=(title:string)=>setB(prev=>({...prev,project:{...prev.project,title,id:idTouched?prev.project.id:suggestProjectId(title)}}));const confirmed=b.assumptions.adultCharacters&&b.assumptions.consensual;return <div className="modal"><div className="modalcard"><h2>新規プロジェクト</h2><div className="formgrid"><label>作成先<input value={parent} readOnly/><button onClick={async()=>{const p=await window.batchStudio.project.selectParent();if(p)setParent(p)}}>選択</button></label><label>プロジェクト名 *<input value={b.project.title} onChange={e=>setTitle(e.target.value)}/></label><label>プロジェクトID<input value={b.project.id} onChange={e=>{setIdTouched(true);set('project.id',e.target.value)}}/><button onClick={()=>{setIdTouched(false);set('project.id',suggestProjectId(b.project.title))}}>自動生成</button></label><label style={{flexDirection:'row',alignItems:'center',gap:8}}><input style={{width:'auto'}} type="checkbox" checked={b.subject.copyrightedCharacter} onChange={e=>set('subject.copyrightedCharacter',e.target.checked)}/>版権キャラクター</label><label>キャラクター{b.subject.copyrightedCharacter?' *':''}<input value={b.subject.characterName} onChange={e=>set('subject.characterName',e.target.value)}/></label><label>作品<input value={b.subject.series} onChange={e=>set('subject.series',e.target.value)}/></label><label>目標画像枚数<input type="number" min={1} value={b.generation.target_image_count} onChange={e=>set('generation.target_image_count',+e.target.value)}/></label><label className="wide">ターゲット読者の特徴 *<textarea value={b.audience} onChange={e=>set('audience',e.target.value)}/></label><label className="wide">要望<textarea value={b.request} onChange={e=>set('request',e.target.value)}/></label><label className="wide">除外<textarea value={b.exclusions} onChange={e=>set('exclusions',e.target.value)}/></label><label className="wide" style={{flexDirection:'row',alignItems:'center',gap:8}}><input style={{width:'auto'}} type="checkbox" checked={confirmed} onChange={e=>setB(prev=>({...prev,assumptions:{adultCharacters:e.target.checked,consensual:e.target.checked}}))}/>登場人物は成人で、成人向け内容は合意を前提とする *</label></div><div className="actions"><button onClick={onClose}>キャンセル</button><button className="primary" disabled={!parent} onClick={()=>run(async()=>onCreated(await window.batchStudio.project.create(parent,b)))}>作成</button></div></div></div>}
function EnvironmentSettings({onClose,run}:{onClose:()=>void;run:Runner}){const [status,setStatus]=useState<AppSettingsStatus|null>(null),[comfyUiInstallPath,setComfyUiInstallPath]=useState('');useEffect(()=>{let cancelled=false;void window.batchStudio.appSettings.get().then(s=>{if(!cancelled){setStatus(s);setComfyUiInstallPath(s.comfyUiInstallPath)}}).catch(()=>{});return()=>{cancelled=true}},[]);const choose=()=>run(async()=>{const selected=await window.batchStudio.appSettings.selectComfyUiDirectory();if(selected)setComfyUiInstallPath(selected)});const save=()=>run(async()=>{const next=await window.batchStudio.appSettings.save({comfyUiInstallPath});setStatus(next);onClose()});return <div className="modal"><div className="modalcard"><h2>環境設定</h2><p>この設定はプロジェクト単位ではなく、ComfyUI Batch Studio全体で共通です。</p><div className="formgrid"><label className="wide">ComfyUI インストール先ディレクトリ<div className="actions"><input style={{flex:1,minWidth:280}} value={comfyUiInstallPath} readOnly placeholder="ComfyUI フォルダーを選択"/><button onClick={()=>void choose()}>選択</button></div></label></div><p className="hint">ローカル実行のモデル配置確認では、指定したComfyUIディレクトリ直下の <code>models</code> 配下を再帰的に探索します。</p>{status?.configured&&<div className="facts"><div>現在の設定 <code>{status.comfyUiInstallPath}</code></div><div>モデル探索先 <code>{status.modelsPath??'-'}</code></div><div>models <b>{status.modelsExists?'✓':'✕'}</b></div></div>}<div className="actions"><button onClick={onClose}>キャンセル</button><button className="primary" disabled={!comfyUiInstallPath.trim()} onClick={()=>void save()}>保存</button></div></div></div>}
function StageView({project,stage,refresh,setProject,run}:{project:ProjectSummary;stage:Stage;refresh:()=>Promise<void|ProjectSummary>;setProject:(p:ProjectSummary)=>void;run:Runner}){switch(stage){case '概要':return <Overview project={project} run={run}/>;case '基本設定':return <Settings project={project} setProject={setProject} run={run}/>;case 'ストーリー':return <StoryStage project={project} setProject={setProject} run={run}/>;case 'モデルカタログ':return <CivitExplorerStage run={run}/>;case 'モデル選定':return <ModelsStage project={project} setProject={setProject} run={run}/>;case 'プロンプト設計':return <PromptPlanStage project={project} setProject={setProject} run={run}/>;case 'Workflow':return <WorkflowStage project={project} refresh={refresh} run={run}/>;case 'モデル配置':return <AvailabilityStage project={project} setProject={setProject} run={run}/>;case 'Preflight':return <PreflightStage project={project} run={run}/>;default:return null}}
export default App;