import { useEffect, useState } from 'react';
import type { ProjectBriefInput, ProjectSummary } from '../shared/types';
import { stages, shouldShowGrok, statusDot, type Runner, type Stage } from './ui';
import { Overview, Settings } from './ProjectStages';
import { StoryStage, ModelsStage } from './GrokStages';
import { PromptPlanStage } from './PromptPlanStage';
import { WorkflowStage, AvailabilityStage, PreflightStage } from './ExecutionStages';

const blankBrief:ProjectBriefInput={project:{id:'',title:''},subject:{copyrightedCharacter:false,characterName:'',series:''},audience:'',request:'',exclusions:'',assumptions:{adultCharacters:false,consensual:false},generation:{target_image_count:500,modelFamily:'Illustrious'},references:[]};
function hashId(value:string){let h=2166136261;for(const ch of value){h^=ch.codePointAt(0)??0;h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function suggestProjectId(title:string){const normalized=title.normalize('NFKD').toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/[-_.]{2,}/g,'-').replace(/^[-_.]+|[-_.]+$/g,'').slice(0,64);if(normalized)return normalized;return title.trim()?`project-${hashId(title).slice(0,8)}`:'';}

function App(){
  const [project,setProject]=useState<ProjectSummary|null>(null),[stage,setStage]=useState<Stage>('概要'),[error,setError]=useState(''),[grok,setGrok]=useState(false),[ratio,setRatio]=useState(.45),[createOpen,setCreateOpen]=useState(false);
  const refresh=async()=>project&&setProject(await window.batchStudio.project.scan(project.rootPath));
  const run:Runner=async fn=>{setError('');try{return await fn()}catch(e){setError(e instanceof Error?e.message:String(e));return undefined}};
  useEffect(()=>{let cancelled=false;void window.batchStudio.grok.setVisible(shouldShowGrok(stage)).then(s=>{if(!cancelled)setGrok(s.visible)}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:String(e))});return()=>{cancelled=true}},[stage]);
  return <main className="shell"><header className="top"><div><span className="eyebrow">ComfyUI Batch Studio</span><h1>{project?.title??'プロジェクト未選択'}</h1><small>{project?.rootPath}</small></div><div className="actions"><button onClick={()=>run(async()=>{const p=await window.batchStudio.project.select();if(p)setProject(p)})}>開く</button><button onClick={()=>setCreateOpen(true)}>新規作成</button><button disabled={!project} onClick={()=>project&&window.batchStudio.project.openFolder(project.rootPath)}>フォルダー</button><button onClick={async()=>{const s=await window.batchStudio.grok.setVisible(!grok);setGrok(s.visible)}}>{grok?'Grokを隠す':'Grokを表示'}</button></div></header>{error&&<div className="errorbar">{error}</div>}<div className="body"><nav>{stages.map(s=><button key={s} className={stage===s?'active':''} onClick={()=>setStage(s)}>{s}{project&&statusDot(project,s)}</button>)}</nav><section className="workspace"><div className="stagehead"><h2>{stage}</h2><label>Local {Math.round(ratio*100)}% <input type="range" min={0.3} max={0.7} step={0.05} value={ratio} disabled={!grok} onChange={async e=>{const s=await window.batchStudio.grok.setRatio(+e.target.value);setRatio(s.ratio)}}/></label></div>{!project?<Empty onCreate={()=>setCreateOpen(true)}/>:<StageView project={project} stage={stage} refresh={refresh} setProject={setProject} run={run}/>}</section></div>{createOpen&&<CreateProject onClose={()=>setCreateOpen(false)} onCreated={p=>{setProject(p);setCreateOpen(false)}} run={run}/>}</main>;
}
function Empty({onCreate}:{onCreate:()=>void}){return <div className="empty"><div className="logo">BS</div><h3>プロジェクトを開くか新規作成してください</h3><button className="primary" onClick={onCreate}>新規プロジェクト</button></div>}
function CreateProject({onClose,onCreated,run}:{onClose:()=>void;onCreated:(p:ProjectSummary)=>void;run:Runner}){const [b,setB]=useState(blankBrief),[parent,setParent]=useState(''),[idTouched,setIdTouched]=useState(false);const set=(key:string,v:unknown)=>setB(prev=>{const n=structuredClone(prev) as Record<string,any>;const [a,c]=key.split('.');if(c)n[a][c]=v;else n[a]=v;return n as unknown as ProjectBriefInput});const setTitle=(title:string)=>setB(prev=>({...prev,project:{...prev.project,title,id:idTouched?prev.project.id:suggestProjectId(title)}}));const confirmed=b.assumptions.adultCharacters&&b.assumptions.consensual;return <div className="modal"><div className="modalcard"><h2>新規プロジェクト</h2><div className="formgrid"><label>作成先<input value={parent} readOnly/><button onClick={async()=>{const p=await window.batchStudio.project.selectParent();if(p)setParent(p)}}>選択</button></label><label>プロジェクト名 *<input value={b.project.title} onChange={e=>setTitle(e.target.value)}/></label><label>プロジェクトID<input value={b.project.id} onChange={e=>{setIdTouched(true);set('project.id',e.target.value)}}/><button onClick={()=>{setIdTouched(false);set('project.id',suggestProjectId(b.project.title))}}>自動生成</button></label><label style={{flexDirection:'row',alignItems:'center',gap:8}}><input style={{width:'auto'}} type="checkbox" checked={b.subject.copyrightedCharacter} onChange={e=>set('subject.copyrightedCharacter',e.target.checked)}/>版権キャラクター</label><label>キャラクター{b.subject.copyrightedCharacter?' *':''}<input value={b.subject.characterName} onChange={e=>set('subject.characterName',e.target.value)}/></label><label>作品<input value={b.subject.series} onChange={e=>set('subject.series',e.target.value)}/></label><label>目標画像枚数<input type="number" min={1} value={b.generation.target_image_count} onChange={e=>set('generation.target_image_count',+e.target.value)}/></label><label className="wide">ターゲット読者の特徴 *<textarea value={b.audience} onChange={e=>set('audience',e.target.value)}/></label><label className="wide">要望<textarea value={b.request} onChange={e=>set('request',e.target.value)}/></label><label className="wide">除外<textarea value={b.exclusions} onChange={e=>set('exclusions',e.target.value)}/></label><label className="wide" style={{flexDirection:'row',alignItems:'center',gap:8}}><input style={{width:'auto'}} type="checkbox" checked={confirmed} onChange={e=>setB(prev=>({...prev,assumptions:{adultCharacters:e.target.checked,consensual:e.target.checked}}))}/>登場人物は成人で、成人向け内容は合意を前提とする *</label></div><div className="actions"><button onClick={onClose}>キャンセル</button><button className="primary" disabled={!parent} onClick={()=>run(async()=>onCreated(await window.batchStudio.project.create(parent,b)))}>作成</button></div></div></div>}
function StageView(props:{project:ProjectSummary;stage:Stage;refresh:()=>Promise<unknown>;setProject:(p:ProjectSummary)=>void;run:Runner}){switch(props.stage){case'概要':return <Overview {...props}/>;case'基本設定':return <Settings {...props}/>;case'ストーリー':return <StoryStage {...props}/>;case'モデル選定':return <ModelsStage {...props}/>;case'プロンプト設計':return <PromptPlanStage {...props}/>;case'ワークフロー':return <WorkflowStage {...props}/>;case'モデル配置':return <AvailabilityStage {...props}/>;case'実行前チェック':return <PreflightStage {...props}/>}}

export default App;
