import { useEffect, useMemo, useState } from 'react';
import type { CatalogCollection, CatalogItem, CatalogSelectionEntry, CatalogSelectionTemplate, CatalogVersion, CivitaiCatalogStatus, ModelCatalog, ProjectSummary } from '../shared/types';
import type { Runner } from './ui';

const keyFor=(collectionId:number,modelId:number)=>`${collectionId}:${modelId}`;
const norm=(value:string)=>value.normalize('NFKC').toLocaleLowerCase('ja');
type CatalogView='collections'|'models'|'selected';
function versionsFor(item:CatalogItem):CatalogVersion[]{return item.versions?.length?item.versions:[{versionId:item.versionId,versionName:item.versionName,files:item.files,trainedWords:item.trainedWords,strengthBaseline:item.strengthBaseline,modelUrl:item.modelUrl,thumbnailUrl:item.thumbnailUrl,thumbnailWidth:item.thumbnailWidth,thumbnailHeight:item.thumbnailHeight}]}
function versionFor(item:CatalogItem,id:number){return versionsFor(item).find(v=>v.versionId===id)??versionsFor(item)[0]}
function searchable(item:CatalogItem){return norm([item.modelName,...versionsFor(item).flatMap(v=>v.files.map(f=>f.name))].join('\n'))}
function appliedItem(item:CatalogItem,versionId:number):CatalogItem{const v=versionFor(item,versionId);return {...item,versionId:v.versionId,versionName:v.versionName,files:v.files,trainedWords:v.trainedWords,strengthBaseline:v.strengthBaseline,modelUrl:v.modelUrl??item.modelUrl,thumbnailUrl:v.thumbnailUrl??item.thumbnailUrl,thumbnailWidth:v.thumbnailWidth,thumbnailHeight:v.thumbnailHeight}}
function buildExport(catalog:ModelCatalog,selected:Set<string>,versionChoice:Record<string,number>){const collections=catalog.collections.map(c=>({...c,items:c.items.filter(i=>selected.has(keyFor(c.id,i.modelId))).map(i=>appliedItem(i,versionChoice[keyFor(c.id,i.modelId)]??i.versionId))})).filter(c=>c.items.length);const files:Array<{name:string}>=[],seen=new Set<string>();for(const c of collections)for(const i of c.items)for(const f of i.files)if(f.name&&!seen.has(f.name)){seen.add(f.name);files.push({name:f.name})}return {generatedAt:new Date().toISOString(),files,collections}}

export function CatalogStage({project,setProject,run}:{project:ProjectSummary;setProject:(p:ProjectSummary)=>void;run:Runner}){
  const [status,setStatus]=useState<CivitaiCatalogStatus|null>(null),[catalog,setCatalog]=useState<ModelCatalog|null>(null),[templates,setTemplates]=useState<CatalogSelectionTemplate[]>([]),[selectedCollections,setSelectedCollections]=useState<Set<number>>(new Set()),[selected,setSelected]=useState<Set<string>>(new Set()),[versions,setVersions]=useState<Record<string,number>>({}),[query,setQuery]=useState(''),[limit,setLimit]=useState(100),[templateName,setTemplateName]=useState(''),[templateId,setTemplateId]=useState(''),[view,setView]=useState<CatalogView>('collections');
  const load=async()=>{const [s,c,t]=await Promise.all([window.batchStudio.catalog.integratedStatus(),window.batchStudio.catalog.snapshot(),window.batchStudio.catalog.templates()]);setStatus(s);setCatalog(c);setTemplates(t)};
  useEffect(()=>{void run(load)},[project.rootPath]);
  useEffect(()=>{if(status?.state!=='running')return;const timer=window.setInterval(()=>{void window.batchStudio.catalog.integratedStatus().then(async s=>{setStatus(s);if(s.state==='ready'){setCatalog(await window.batchStudio.catalog.snapshot());window.clearInterval(timer)}})},650);return()=>window.clearInterval(timer)},[status?.state]);
  useEffect(()=>setLimit(100),[query,selectedCollections]);
  const linked=Boolean(status&&project.meta?.settings.catalogPath===status.catalogPath);
  const collections=catalog?.collections??[];
  const q=norm(query.trim());
  const visibleRows=useMemo(()=>{const out:Array<{collection:CatalogCollection;item:CatalogItem}>=[];for(const collection of collections){if(!q&&!selectedCollections.has(collection.id))continue;for(const item of collection.items){if(q&&!searchable(item).includes(q))continue;out.push({collection,item})}}return out},[collections,q,selectedCollections]);
  const selectedEntries=useMemo<CatalogSelectionEntry[]>(()=>{const out:CatalogSelectionEntry[]=[];for(const c of collections)for(const item of c.items){const key=keyFor(c.id,item.modelId);if(selected.has(key))out.push({collectionId:c.id,modelId:item.modelId,versionId:versions[key]??item.versionId})}return out},[collections,selected,versions]);
  const toggleCollection=(id:number)=>setSelectedCollections(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next});
  const openCollection=(id:number)=>{setSelectedCollections(new Set([id]));setQuery('');setView('models')};
  const toggleItem=(collectionId:number,item:CatalogItem)=>setSelected(prev=>{const next=new Set(prev),key=keyFor(collectionId,item.modelId);next.has(key)?next.delete(key):next.add(key);return next});
  const applyTemplate=(template:CatalogSelectionTemplate)=>{const keys=new Set<string>(),choice:Record<string,number>={},collectionIds=new Set<number>();for(const row of template.selection){const key=keyFor(row.collectionId,row.modelId);keys.add(key);choice[key]=row.versionId;collectionIds.add(row.collectionId)}setSelected(keys);setVersions(choice);setSelectedCollections(collectionIds);setTemplateId(template.id);setTemplateName(template.name);setView('models')};
  const saveTemplate=()=>run(async()=>{const next=await window.batchStudio.catalog.saveTemplate({id:templateId||undefined,name:templateName,selection:selectedEntries});setTemplates(next);const saved=next.find(t=>t.name===templateName.trim());if(saved)setTemplateId(saved.id)});
  const copyJson=()=>catalog&&window.batchStudio.clipboard.writeText(JSON.stringify(buildExport(catalog,selected,versions),null,2));
  return <>
    <section className="panel catalog-status-panel"><div className="panelhead"><div><h3>Civitai モデルカタログ</h3><p>Civitai Collectionを同期し、コレクション → モデル → 選択結果の順に確認できます。</p></div><div className="actions"><button disabled={status?.state==='running'||!status?.apiKeyConfigured} onClick={()=>run(async()=>setStatus(await window.batchStudio.catalog.sync()))}>↻ SYNC</button><button className={linked?'':'primary'} disabled={!status} onClick={()=>run(async()=>setProject(await window.batchStudio.catalog.linkProject(project.rootPath)))}>{linked?'このプロジェクトで使用中':'このCatalogを使用'}</button></div></div>
      <div className="catalog-status-grid"><div><span>API KEY</span><strong>{status?.apiKeyConfigured?'設定済み':'未設定'}</strong></div><div><span>generation</span><strong>{status?.generation??0}</strong></div><div><span>models</span><strong>{collections.reduce((n,c)=>n+c.items.length,0)}</strong></div><div><span>changes</span><strong>+{status?.changes.added??0} / ~{status?.changes.updated??0} / -{status?.changes.removed??0}</strong></div></div>
      {status?.state==='running'&&<div className="catalog-progress"><div><strong>{status.phase}</strong><span>{status.completed} / {status.total}</span></div><progress value={status.completed} max={Math.max(status.total,1)}/><p>{status.message}</p></div>}
      {status?.state==='error'&&<div className="issue error">✕ {status.error??status.message}{catalog&&<span> — 保存済みCatalogは引き続き閲覧できます。</span>}</div>}
      {!status?.apiKeyConfigured&&<p className="hint">起動前に環境変数 <code>CIVIT_API_KEY</code> を設定してください。APIキーはMain ProcessからCivitaiへだけ送信され、Grok Webへは渡しません。</p>}
      {status&&<small>{status.catalogPath}</small>}
    </section>

    <div className="catalog-browser-nav" role="navigation" aria-label="モデルカタログ内ナビゲーション">
      <button className={view==='collections'?'active':''} onClick={()=>setView('collections')}><span>1</span>コレクション一覧 <b>{collections.length}</b></button>
      <span className="catalog-browser-arrow">→</span>
      <button className={view==='models'?'active':''} onClick={()=>setView('models')}><span>2</span>モデル一覧 <b>{q?visibleRows.length:selectedCollections.size?visibleRows.length:0}</b></button>
      <span className="catalog-browser-arrow">→</span>
      <button className={view==='selected'?'active':''} onClick={()=>setView('selected')}><span>3</span>選択結果 <b>{selectedEntries.length}</b></button>
    </div>

    <section className="panel"><div className="panelhead"><div><h3>検索・選択テンプレート</h3><p>検索語がある間はCollection選択に関係なく全Collectionを横断します。</p></div><label className="catalog-search">MODEL / FILE<input type="search" placeholder="モデル名・ファイル名で検索" value={query} onChange={e=>{setQuery(e.target.value);if(e.target.value.trim())setView('models')}}/></label></div>
      <div className="catalog-template-row"><input placeholder="テンプレート名" maxLength={60} value={templateName} onChange={e=>setTemplateName(e.target.value)}/><button disabled={!templateName.trim()||!selected.size} onClick={saveTemplate}>現在の選択を保存</button><select value={templateId} onChange={e=>{const t=templates.find(x=>x.id===e.target.value);if(t)applyTemplate(t);else setTemplateId('')}}><option value="">保存済みテンプレート</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button disabled={!templateId} onClick={()=>run(async()=>{setTemplates(await window.batchStudio.catalog.deleteTemplate(templateId));setTemplateId('');setTemplateName('')})}>削除</button></div>
    </section>

    {view==='collections'&&<section className="panel"><div className="panelhead"><div><h3>コレクション一覧</h3><p>{collections.length}件。対象Collectionを選択してモデル一覧へ進みます。</p></div><div className="actions"><button onClick={()=>setSelectedCollections(new Set(collections.map(c=>c.id)))}>すべて選択</button><button onClick={()=>setSelectedCollections(new Set())}>選択解除</button><button className="primary" disabled={!selectedCollections.size} onClick={()=>setView('models')}>選択したコレクションのモデルを見る →</button></div></div>
      {!collections.length?<div className="empty-inline">Catalogがありません。SYNCを実行してください。</div>:<div className="catalog-collections">{collections.map(c=><article key={c.id} className={`catalog-collection-card ${selectedCollections.has(c.id)?'selected':''}`}><label className="catalog-collection-select"><input type="checkbox" checked={selectedCollections.has(c.id)} onChange={()=>toggleCollection(c.id)}/></label>{c.thumbnailUrl?<img src={c.thumbnailUrl} alt=""/>:<div className="catalog-collection-placeholder">COL</div>}<div className="catalog-collection-copy"><strong>{c.name}</strong><small>{c.description||'説明はありません'}</small><span>{c.read??'Private'} · {c.items.length} models</span></div><button className="catalog-open-models" onClick={()=>openCollection(c.id)}>モデルを見る →</button></article>)}</div>}
    </section>}

    {view==='models'&&<section className="panel"><div className="panelhead"><div><div className="catalog-breadcrumb"><button onClick={()=>setView('collections')}>← コレクション一覧</button><span>/</span><strong>モデル一覧</strong></div><h3>モデル一覧</h3><p>{q?'全Collection検索中':selectedCollections.size?`${selectedCollections.size}コレクションを表示`:'表示するコレクションが選択されていません'} · {visibleRows.length}件中 {Math.min(limit,visibleRows.length)}件表示 / {selected.size}件選択</p></div><div className="actions"><button disabled={!visibleRows.length} onClick={()=>setSelected(prev=>{const next=new Set(prev);for(const {collection,item} of visibleRows)next.add(keyFor(collection.id,item.modelId));return next})}>表示中をすべて選択</button><button disabled={!selected.size} onClick={()=>setSelected(new Set())}>選択解除</button><button className="primary" disabled={!selected.size} onClick={()=>setView('selected')}>選択結果を見る →</button></div></div>
      {!visibleRows.length?<div className="empty-inline"><strong>モデルが表示されていません。</strong><br/>{q?'検索語を変更してください。':'「コレクション一覧」からCollectionを選択してください。'}<div className="actions catalog-empty-actions"><button onClick={()=>setView('collections')}>コレクション一覧へ</button></div></div>:<div className="catalog-model-list">{visibleRows.slice(0,limit).map(({collection,item})=>{const key=keyFor(collection.id,item.modelId),version=versionFor(item,versions[key]??item.versionId),checked=selected.has(key);return <article className={`catalog-model ${checked?'selected':''}`} key={key}><label className="catalog-model-check"><input type="checkbox" checked={checked} onChange={()=>toggleItem(collection.id,item)}/></label><div className="catalog-thumb">{(version.thumbnailUrl??item.thumbnailUrl)?<img src={version.thumbnailUrl??item.thumbnailUrl} alt=""/>:<span>MODEL</span>}</div><div className="catalog-model-main"><div className="catalog-model-title"><div><strong>{item.modelName}</strong><small>{collection.name}</small></div><button onClick={()=>window.batchStudio.catalog.openModel(version.modelUrl??item.modelUrl??`https://civitai.com/models/${item.modelId}`)}>Civitai ↗</button></div><label>Version<select value={version.versionId} onChange={e=>setVersions({...versions,[key]:Number(e.target.value)})}>{versionsFor(item).map(v=><option key={v.versionId} value={v.versionId}>{v.versionName}</option>)}</select></label><div className="catalog-meta"><div><span>FILES</span>{version.files.map(f=><code key={f.id}>{f.name}{f.primary?' ★':''}</code>)}</div><div><span>TRAINED WORDS</span>{version.trainedWords?.length?version.trainedWords.map(w=><code key={w}>{w}</code>):<small>なし</small>}</div><div><span>CIVITAI 基準値</span>{version.strengthBaseline?<strong>{version.strengthBaseline.value} <small>n={version.strengthBaseline.provenance.sampleCount??'-'}</small></strong>:<small>根拠なし</small>}</div></div>{item.error&&<div className="issue warning">⚠ {item.error}</div>}</div></article>})}</div>}
      {visibleRows.length>limit&&<button className="load-more" onClick={()=>setLimit(x=>x+100)}>さらに100件表示</button>}
    </section>}

    {view==='selected'&&<section className="panel"><div className="panelhead"><div><div className="catalog-breadcrumb"><button onClick={()=>setView('models')}>← モデル一覧</button><span>/</span><strong>選択結果</strong></div><h3>選択結果</h3><p>{selectedEntries.length}モデル。Model / Version / File / trained wordsをまとめて確認・コピーできます。</p></div><button className="primary" disabled={!catalog||!selectedEntries.length} onClick={copyJson}>JSONをコピー</button></div>{selectedEntries.length?<div className="selected-manifest">{selectedEntries.map(row=>{const collection=collections.find(c=>c.id===row.collectionId)!,item=collection.items.find(i=>i.modelId===row.modelId)!,version=versionFor(item,row.versionId);return <div key={keyFor(row.collectionId,row.modelId)}><strong>{item.modelName}</strong><span>{version.versionName}</span><small>{version.files.map(f=>f.name).join(' / ')}</small></div>})}</div>:<div className="empty-inline">モデルがまだ選択されていません。<div className="actions catalog-empty-actions"><button onClick={()=>setView('models')}>モデル一覧へ</button></div></div>}</section>}
  </>;
}
