import { useEffect, useState } from 'react';
import type { AppSettings, AppSettingsStatus, CivitaiConnectionStatus, R2ConnectionInput, R2ConnectionStatus } from '../shared/types';
import type { Runner } from './ui';

const EMPTY_SETTINGS:AppSettings={comfyUiInstallPath:'',catalogPath:'',r2Bucket:'',r2ModelPrefix:'',r2IndexPath:'',templatePath:'',manifestPath:''};
const EMPTY_R2:R2ConnectionInput={name:'Personal R2',accountId:'',accessKeyId:'',secretAccessKey:'',publicUrl:'',cloudflareApiToken:''};

export function EnvironmentSettings({onClose,run}:{onClose:()=>void;run:Runner}){
  const [settings,setSettings]=useState<AppSettings>(EMPTY_SETTINGS),[status,setStatus]=useState<AppSettingsStatus|null>(null),[r2Input,setR2Input]=useState<R2ConnectionInput>(EMPTY_R2),[r2Status,setR2Status]=useState<R2ConnectionStatus|null>(null),[r2Dirty,setR2Dirty]=useState(false),[civitaiStatus,setCivitaiStatus]=useState<CivitaiConnectionStatus|null>(null),[civitaiApiKey,setCivitaiApiKey]=useState('');
  useEffect(()=>{let cancelled=false;void Promise.all([window.batchStudio.appSettings.get(),window.batchStudio.r2.environment(),window.batchStudio.r2.settings(),window.batchStudio.civitai.settings()]).then(([appSettings,r2Environment,currentR2,currentCivitai])=>{if(cancelled)return;setStatus(appSettings);setSettings({comfyUiInstallPath:appSettings.comfyUiInstallPath,catalogPath:appSettings.catalogPath,r2Bucket:appSettings.r2Bucket,r2ModelPrefix:appSettings.r2ModelPrefix,r2IndexPath:appSettings.r2IndexPath,templatePath:appSettings.templatePath,manifestPath:appSettings.manifestPath});setR2Status(currentR2);const saved=currentR2.configured;setR2Input({name:currentR2.name||r2Environment.name||'Personal R2',accountId:currentR2.accountId||r2Environment.accountId,accessKeyId:currentR2.accessKeyId||r2Environment.accessKeyId,secretAccessKey:saved?'':(r2Environment.secretAccessKey??''),publicUrl:currentR2.publicUrl||r2Environment.publicUrl||'',cloudflareApiToken:saved?'':(r2Environment.cloudflareApiToken??'')});setCivitaiStatus(currentCivitai)}).catch(()=>{});return()=>{cancelled=true}},[]);
  const setApp=(key:keyof AppSettings,value:string)=>setSettings(prev=>({...prev,[key]:value}));
  const setR2=(key:keyof R2ConnectionInput,value:string)=>{setR2Dirty(true);setR2Input(prev=>({...prev,[key]:value}))};
  const choose=()=>run(async()=>{const selected=await window.batchStudio.appSettings.selectComfyUiDirectory();if(selected)setApp('comfyUiInstallPath',selected)});
  const testR2=()=>run(async()=>{await window.batchStudio.r2.test(r2Input)});
  const save=()=>run(async()=>{const next=await window.batchStudio.appSettings.save(settings);if(r2Dirty)setR2Status(await window.batchStudio.r2.saveSettings(r2Input));if(civitaiApiKey.trim())setCivitaiStatus(await window.batchStudio.civitai.saveSettings({apiKey:civitaiApiKey}));setStatus(next);onClose()});
  const civitaiSource=civitaiStatus?.source==='saved'?'アプリに安全に保存済み':civitaiStatus?.source==='environment'?'環境変数 CIVIT_API_KEY を使用中':'未設定';
  return <div className="modal"><div className="modalcard environment-settings-card"><h2>環境設定</h2><p>この設定はプロジェクト単位ではなく、ComfyUI Batch Studio全体で共通です。</p>
    <section className="environment-section"><div className="panelhead"><div><h3>パス設定</h3><p>基本設定から移動した共通パスです。空欄の場合は内蔵・統合機能を使用します。</p></div></div><div className="formgrid">
      <label className="wide">ComfyUI インストール先ディレクトリ<div className="actions"><input style={{flex:1,minWidth:280}} value={settings.comfyUiInstallPath} readOnly placeholder="ComfyUI フォルダーを選択（リモート実行のみなら空欄可）"/><button onClick={()=>void choose()}>選択</button><button disabled={!settings.comfyUiInstallPath} onClick={()=>setApp('comfyUiInstallPath','')}>解除</button></div></label>
      <label className="wide">外部 model_catalog.json（互換用）<input value={settings.catalogPath??''} onChange={e=>setApp('catalogPath',e.target.value)} placeholder="空欄 = Civitai統合カタログ"/></label>
      <label className="wide">R2ファイル一覧JSON（互換用）<input value={settings.r2IndexPath??''} onChange={e=>setApp('r2IndexPath',e.target.value)} placeholder="空欄 = R2統合インデックス"/></label>
      <label>Workflow Template<input value={settings.templatePath??''} onChange={e=>setApp('templatePath',e.target.value)} placeholder="空欄 = 内蔵"/></label><label>Manifest<input value={settings.manifestPath??''} onChange={e=>setApp('manifestPath',e.target.value)} placeholder="空欄 = 内蔵"/></label>
    </div><p className="hint">ローカル実行のモデル配置確認では、指定したComfyUIディレクトリ直下の <code>models</code> 配下を再帰的に探索します。</p>{status?.configured&&<div className="facts"><div>ComfyUI <code>{status.comfyUiInstallPath}</code></div><div>モデル探索先 <code>{status.modelsPath??'-'}</code></div><div>models <b>{status.modelsExists?'✓':'✕'}</b></div></div>}</section>
    <section className="environment-section"><div className="panelhead"><div><h3>Cloudflare R2 連携</h3><p>モデル保管先とR2 File Managerで共通利用する接続設定です。SecretはOSの安全な暗号化ストレージへ保存します。</p></div><span className={r2Status?.configured?'ok':'eyebrow'}>{r2Status?.configured?'設定済み':r2Status?.secretConfigured?'環境変数を使用中':'未設定'}</span></div><div className="formgrid">
      <label>接続名<input value={r2Input.name??''} onChange={e=>setR2('name',e.target.value)}/></label><label>モデル保管R2バケット<input value={settings.r2Bucket??''} onChange={e=>setApp('r2Bucket',e.target.value)}/></label>
      <label>Account ID<input value={r2Input.accountId} onChange={e=>setR2('accountId',e.target.value)} placeholder="32文字の16進数"/></label><label>Access Key ID<input value={r2Input.accessKeyId} onChange={e=>setR2('accessKeyId',e.target.value)}/></label>
      <label>Secret Access Key<input type="password" value={r2Input.secretAccessKey??''} onChange={e=>setR2('secretAccessKey',e.target.value)} placeholder={r2Status?.secretConfigured?'保存済み（変更時のみ入力）':''}/></label><label>モデル保管プレフィックス<input value={settings.r2ModelPrefix??''} onChange={e=>setApp('r2ModelPrefix',e.target.value)} placeholder="例: models"/></label>
      <label className="wide">Public URL<input value={r2Input.publicUrl??''} onChange={e=>setR2('publicUrl',e.target.value)} placeholder="https://..."/></label><label className="wide">Cloudflare API Token（メトリクス用・任意）<input type="password" value={r2Input.cloudflareApiToken??''} onChange={e=>setR2('cloudflareApiToken',e.target.value)} placeholder={r2Status?.metricsTokenConfigured?'保存済み（変更時のみ入力）':''}/></label>
    </div><div className="actions"><button onClick={()=>void testR2()}>R2接続テスト</button></div></section>
    <section className="environment-section"><div className="panelhead"><div><h3>Civitai 連携</h3><p>Collectionからモデルカタログを同期するためのAPI Keyです。保存したキーはOSの安全な暗号化ストレージで保護します。</p></div><span className={civitaiStatus?.configured?'ok':'eyebrow'}>{civitaiSource}</span></div><div className="formgrid"><label className="wide">Civitai API Key<input type="password" value={civitaiApiKey} onChange={e=>setCivitaiApiKey(e.target.value)} placeholder={civitaiStatus?.configured?'設定済み（変更時のみ入力）':'API Keyを入力'}/></label></div></section>
    <div className="actions environment-actions"><button onClick={onClose}>キャンセル</button><button className="primary" onClick={()=>void save()}>環境設定を保存</button></div>
  </div></div>;
}
