import { useEffect, useState } from 'react';
import type { AppSettings, AppSettingsStatus, AvailabilityResult, CompileResult, ExecutionTarget, ModelsArtifact, PreflightResult, ProjectSummary, VastAiConnectionStatus, VastAiInstance } from '../shared/types';
import type { Runner } from './ui';
import { issuesView } from './ui';
import { R2ManagerStage } from './R2ManagerStage';

export function WorkflowStage({project,refresh,run}:{project:ProjectSummary;refresh:()=>Promise<unknown>;run:Runner}){const [r,setR]=useState<CompileResult|null>(null);const hasWorkflow=Boolean(project.artifacts.find(a=>a.key==='workflow')?.relativePath);return <section className="panel"><h3>Workflow Compiler</h3><p>確定済み models.json / prompt_plan.json と Template/Manifestから決定論的に生成します。</p><div className="actions"><button className="primary" onClick={()=>run(async()=>{setR(await window.batchStudio.workflow.compile(project.rootPath));await refresh()})}>ワークフローを生成</button>{(r||hasWorkflow)&&<button onClick={()=>window.batchStudio.project.openFolder(project.rootPath)}>フォルダを開く</button>}</div>{r&&<div className="facts"><div>Branches <b>{r.branchCount}</b></div><div>Images <b>{r.imageCount}</b></div><div>Nodes <b>{r.nodeCount}</b></div><div>Links <b>{r.linkCount}</b></div><div>Output <code>{r.outputPath}</code></div></div>}</section>}

function appSettingsInput(s:AppSettingsStatus):AppSettings{return {comfyUiInstallPath:s.comfyUiInstallPath,catalogPath:s.catalogPath,r2Bucket:s.r2Bucket,r2ModelPrefix:s.r2ModelPrefix,r2IndexPath:s.r2IndexPath,templatePath:s.templatePath,manifestPath:s.manifestPath}}
function vastInstanceLabel(instance:VastAiInstance){const label=instance.label?` | ${instance.label}`:'',gpu=instance.gpuName?` | ${instance.gpuName}`:'';return `#${instance.id} | ${instance.status.toUpperCase()}${gpu}${label}`;}
export function AvailabilityStage({project,setProject,run}:{project:ProjectSummary;setProject:(p:ProjectSummary)=>void;run:Runner}){
  const [r,setR]=useState<AvailabilityResult|null>(null),[modelFileNames,setModelFileNames]=useState<string[]>([]),[appSettings,setAppSettings]=useState<AppSettingsStatus|null>(null),[vastStatus,setVastStatus]=useState<VastAiConnectionStatus|null>(null),[vastInstances,setVastInstances]=useState<VastAiInstance[]>([]),[cloudError,setCloudError]=useState('');
  const target:ExecutionTarget=project.meta?.settings.executionTarget==='remote'?'remote':'local';
  const selectedInstanceId=project.meta?.settings.remoteProvider==='vastai'?project.meta.settings.remoteInstanceId:undefined;
  const loadCloud=async()=>{setCloudError('');const status=await window.batchStudio.vastai.settings();setVastStatus(status);if(!status.configured){setVastInstances([]);return;}try{setVastInstances(await window.batchStudio.vastai.instances())}catch(e){setVastInstances([]);setCloudError(e instanceof Error?e.message:String(e));}};
  useEffect(()=>{let cancelled=false;void window.batchStudio.artifact.read(project.rootPath,'models','confirmed').then(a=>{if(cancelled||!a.content)return;try{const models=JSON.parse(a.content) as ModelsArtifact;const baseFile=models.modelFamily==='anima'?(models.diffusionModel?.fileName??models.checkpoint?.fileName):models.checkpoint?.fileName;const names=[baseFile,models.textEncoder?.fileName,models.vae?.fileName,...models.loras.map(x=>x.fileName)].filter((x):x is string=>typeof x==='string'&&x.length>0);setModelFileNames(names)}catch{setModelFileNames([])}}).catch(()=>{if(!cancelled)setModelFileNames([])});void window.batchStudio.appSettings.get().then(s=>{if(!cancelled)setAppSettings(s)}).catch(()=>{});void loadCloud().catch(()=>{});return()=>{cancelled=true}},[project.rootPath]);
  const check=()=>run(async()=>{const [settings,result]=await Promise.all([window.batchStudio.appSettings.get(),window.batchStudio.availability.check(project.rootPath)]);setAppSettings(settings);setR(result);if(target==='remote')await loadCloud()});
  const setTarget=(executionTarget:ExecutionTarget)=>run(async()=>{const updated=await window.batchStudio.project.saveSettings(project.rootPath,{executionTarget});setProject(updated);const result=await window.batchStudio.availability.check(project.rootPath);setR(result);if(executionTarget==='remote')await loadCloud()});
  const setRemoteInstance=(value:string)=>run(async()=>{const remoteInstanceId=Number(value);if(!Number.isInteger(remoteInstanceId)||remoteInstanceId<1)return;const updated=await window.batchStudio.project.saveSettings(project.rootPath,{executionTarget:'remote',remoteProvider:'vastai',remoteInstanceId});setProject(updated)});
  const selectBucket=(bucket:string)=>run(async()=>{const current=await window.batchStudio.appSettings.get();const updated=await window.batchStudio.appSettings.save({...appSettingsInput(current),r2Bucket:bucket});setAppSettings(updated);setR(await window.batchStudio.availability.check(project.rootPath))});
  const localRequirement=target==='local'?'必須':'任意',r2Requirement=target==='remote'?'必須':'任意';
  const selectedInstance=vastInstances.find(x=>x.id===selectedInstanceId);
  return <><section className="panel"><div className="panelhead"><div><h3>モデル配置</h3><p>ワークフロー実行先に応じて、必須となるモデル配置先を切り替えます。</p></div><div className="actions"><button onClick={()=>void check()}>再確認</button></div></div><div className="facts"><div><span className="eyebrow">ワークフロー実行先</span><div className="actions"><button className={target==='local'?'primary':''} onClick={()=>void setTarget('local')}>ローカル</button><button className={target==='remote'?'primary':''} onClick={()=>void setTarget('remote')}>リモート</button></div></div><div><span className="eyebrow">ローカル配置</span><b>{localRequirement}</b><small style={{display:'block',marginTop:6,color:'#8993a2'}}>ローカル実行時のみ必須</small></div><div><span className="eyebrow">R2配置</span><b>{r2Requirement}</b><small style={{display:'block',marginTop:6,color:'#8993a2'}}>リモート実行時のみ必須</small></div></div>{target==='local'&&<p className="hint">ローカル探索先: <code>{appSettings?.modelsPath??'未設定'}</code>。環境設定で指定したComfyUIインストール先の <code>models</code> 配下を再帰的に確認します。</p>}{target==='remote'&&<><div className="environment-section"><div className="panelhead"><div><h3>クラウド実行先</h3><p>サービス連携で設定したVast.aiの既存Instanceから、このProjectの実行先を選択します。</p></div><button disabled={!vastStatus?.configured} onClick={()=>void run(loadCloud)}>Instance更新</button></div>{!vastStatus?.configured?<p className="hint">Vast.aiが未設定です。プロジェクトを閉じ、ホームの「サービス連携 → クラウドインスタンス → Vast.ai」でAPI KeyとSSH秘密鍵を設定してください。</p>:<div className="formgrid"><label className="wide">Vast.ai Instance<select value={selectedInstanceId??''} onChange={e=>void setRemoteInstance(e.target.value)}><option value="">選択してください</option>{vastInstances.map(instance=><option key={instance.id} value={instance.id}>{vastInstanceLabel(instance)}</option>)}</select></label></div>}{cloudError&&<div className="errorbar">{cloudError}</div>}{selectedInstance&&<div className="facts"><div>Instance <b>#{selectedInstance.id}</b></div><div>Status <b>{selectedInstance.status.toUpperCase()}</b></div><div>GPU <b>{selectedInstance.gpuName??'-'}</b></div><div>SSH <code>{selectedInstance.sshHost&&selectedInstance.sshPort?`${selectedInstance.sshHost}:${selectedInstance.sshPort}`:'起動後に取得'}</code></div></div>}</div><p className="hint">リモート実行ではR2配置が必須です。SSH Host/PortはProjectへ固定保存せず、実行時にVast.ai APIから最新値を解決します。</p></>}{r&&<>{issuesView(r.validation.issues)}<div className="table">{r.rows.map(x=><div className="tablerow" key={x.ref}><code>{x.ref}</code><span>{x.fileName}</span><span>Local {localRequirement} {x.local?'✓':'✕'}</span><span>R2 {r2Requirement} {x.r2?'✓':'✕'}</span><b>{x.state==='available'?'要件OK':x.state==='transfer-required'?(target==='local'?'Localへ配置':'R2へ配置'):'未配置'}</b></div>)}</div></>}</section>{appSettings&&<section className="panel"><R2ManagerStage run={run} readOnly initialBucket={appSettings.r2Bucket} initialBatchFileNames={modelFileNames} onBucketChange={bucket=>void selectBucket(bucket)}/></section>}</>;
}

export function PreflightStage({project,run}:{project:ProjectSummary;run:Runner}){const [r,setR]=useState<PreflightResult|null>(null);return <section className="panel"><button className="primary" onClick={()=>run(async()=>setR(await window.batchStudio.preflight.run(project.rootPath)))}>実行前チェック</button>{r&&<><div className={`preflight ${r.state.toLowerCase()}`}><h2>{r.state}</h2><p>{r.plannedImages}枚予定 / 目標 {r.targetImages??'-'}枚</p></div>{r.sections.map(s=><div className="sectioncheck" key={s.name}><h4>{s.valid?'✓':'✕'} {s.name}</h4>{issuesView(s.issues)}</div>)}{r.warnings.length>0&&<><h3>注意</h3>{issuesView(r.warnings)}</>}</>}</section>}
