import { useEffect, useRef, useState } from 'react';
import type { ArtifactReadResult, AvailabilityResult, CatalogStatus, GrokTask, ImportResult, LoraSelection, ModelCatalog, ModelFamily, ModelSelectionBase, ModelsArtifact, ProjectBriefInput, ProjectSummary, TextEncoderSelection, VaeSelection, CheckpointSelection } from '../shared/types';
import type { Runner } from './ui';
import { issuesView } from './ui';
import { ModelPicker } from './ModelPicker';
import { ModelFilePicker } from './ModelFilePicker';
import './model-selection.css';

type GrokReturnFile={name:string;accept:string};
const GROK_RETURN_FILES:Partial<Record<GrokTask['stage'],GrokReturnFile>>={
 'story-finalize':{name:'story.md',accept:'.md,text/markdown,text/plain'},
 'story-fix':{name:'story.md',accept:'.md,text/markdown,text/plain'},
 models:{name:'model_loras.json',accept:'.json,application/json,text/plain'},
 'models-fix':{name:'model_loras.json',accept:'.json,application/json,text/plain'},
 'prompt-plan':{name:'prompt_plan.json',accept:'.json,application/json,text/plain'},
 'prompt-plan-fix':{name:'prompt_plan.json',accept:'.json,application/json,text/plain'}
};
function fileSizeLabel(size:number){if(size<1024)return `${size} B`;if(size<1024*1024)return `${(size/1024).toFixed(1)} KB`;return `${(size/1024/1024).toFixed(1)} MB`}
function importResultView(result:ImportResult|null){return result?<div className="result">{issuesView(result.validation.issues)}{result.missingRequirements.map((m,n)=><div className="issue error" key={n}>✕ {m.role}: {m.requirement} — {m.reason}</div>)}</div>:null}

export function GrokBridge({project,stage,title,onImport,run,receive=true}:{project:ProjectSummary;stage:GrokTask['stage'];title:string;onImport?:(raw:string)=>Promise<ImportResult>;run:Runner;receive?:boolean}){
 const [task,setTask]=useState<GrokTask|null>(null),[raw,setRaw]=useState(''),[result,setResult]=useState<ImportResult|null>(null),[extra,setExtra]=useState(''),[selectedFile,setSelectedFile]=useState<File|null>(null),[fileIssue,setFileIssue]=useState(''),[dragging,setDragging]=useState(false);const fileInput=useRef<HTMLInputElement|null>(null),isFix=stage.endsWith('-fix'),returnFile=GROK_RETURN_FILES[stage];
 const selectReturnFile=(file:File|null)=>{setResult(null);setFileIssue('');if(!file){setSelectedFile(null);return}if(returnFile){const expectedExt=returnFile.name.slice(returnFile.name.lastIndexOf('.')).toLowerCase();if(expectedExt&&!file.name.toLowerCase().endsWith(expectedExt)){setSelectedFile(null);setFileIssue(`Grok返却ファイルは ${returnFile.name} と同じ ${expectedExt} 形式を選択してください。`);return}}setSelectedFile(file)};
 const importReturnFile=()=>selectedFile&&onImport&&run(async()=>{const content=await selectedFile.text();if(!content.trim())throw new Error(`${selectedFile.name} は空です。`);setResult(await onImport(content))});
 return <section className="panel"><h3>{title}</h3>{isFix&&<label>修正条件<textarea value={extra} onChange={e=>setExtra(e.target.value)} placeholder="直したい点を入力（任意）"/></label>}<div className="actions"><button onClick={()=>run(async()=>setTask(await window.batchStudio.grokTask.build(project.rootPath,stage,extra)))}>依頼内容を生成</button>{task&&<button onClick={()=>window.batchStudio.clipboard.writeText(task.prompt)}>コピー</button>}</div>{task&&<><textarea className="promptbox" value={task.prompt} readOnly/><div className="attachments">{task.attachments.map(a=><div className="attachment-row" key={`${a.path}:${a.name}`}><span>{a.exists?'✓':'✕'} {a.name} — {a.purpose}</span><button disabled={!a.exists} onClick={()=>window.batchStudio.file.showInFolder(a.path)}>場所を開く</button></div>)}</div></>}{receive&&returnFile?<><h4>Grok返却ファイルを添付</h4><p className="grok-return-note">Grokからダウンロードした <code>{returnFile.name}</code> を添付してください。チャット本文の貼り付けではなく、このファイルを検証して下書きへ取り込みます。</p><div className={`grok-file-dropzone ${dragging?'dragging':''}`} onDragEnter={e=>{e.preventDefault();e.stopPropagation();setDragging(true)}} onDragOver={e=>{e.preventDefault();e.stopPropagation();setDragging(true)}} onDragLeave={e=>{e.preventDefault();e.stopPropagation();setDragging(false)}} onDrop={e=>{e.preventDefault();e.stopPropagation();setDragging(false);selectReturnFile(e.dataTransfer.files?.[0]??null)}}><input ref={fileInput} type="file" accept={returnFile.accept} onChange={e=>{selectReturnFile(e.currentTarget.files?.[0]??null);e.currentTarget.value=''}}/><strong>{selectedFile?selectedFile.name:`${returnFile.name} をここにドラッグ＆ドロップ`}</strong><span>{selectedFile?`${fileSizeLabel(selectedFile.size)} · 取り込み待ち`:'またはファイルエクスプローラーから選択'}</span><button type="button" onClick={()=>fileInput.current?.click()}>ファイルを選択</button></div>{fileIssue&&<div className="issue error">✕ {fileIssue}</div>}<div className="actions grok-file-actions"><button className="primary" disabled={!selectedFile||!onImport} onClick={()=>void importReturnFile()}>ファイルを解析・取り込む</button>{selectedFile&&<button type="button" onClick={()=>selectReturnFile(null)}>選択を解除</button>}</div>{importResultView(result)}</>:receive?<><h4>Grokの回答を貼り付け</h4><textarea className="raw" value={raw} onChange={e=>setRaw(e.target.value)}/><button className="primary" disabled={!raw.trim()||!onImport} onClick={()=>onImport&&run(async()=>setResult(await onImport(raw)))}>結果を解析・取り込む</button>{importResultView(result)}</>:null}</section>
}

async function loadEditable(root:string,key:'story'|'models',setter:(r:ArtifactReadResult)=>void){const draft=await window.batchStudio.artifact.read(root,key,'draft');if(draft.exists){setter(draft);return true}const confirmed=await window.batchStudio.artifact.read(root,key,'confirmed');setter(confirmed);return false}
export function StoryStage({project,setProject,run}:{project:ProjectSummary;setProject:(p:ProjectSummary)=>void;run:Runner}){const [doc,setDoc]=useState<ArtifactReadResult|null>(null),[editing,setEditing]=useState(false);const load=()=>run(async()=>setEditing(await loadEditable(project.rootPath,'story',setDoc)));useEffect(()=>{void load()},[project.rootPath]);const importStory=async(raw:string)=>{const r=await window.batchStudio.artifact.importGrok(project.rootPath,'story',raw);setEditing(true);setDoc(await window.batchStudio.artifact.read(project.rootPath,'story','draft'));return r};return <><GrokBridge project={project} stage="story-initial" title="1. Grokでストーリーを検討" run={run} receive={false}/><GrokBridge project={project} stage="story-finalize" title="2. 完成版 story.md を作成" run={run} onImport={importStory}/>{project.artifacts.find(a=>a.key==='story')?.state!=='missing'&&<GrokBridge project={project} stage="story-fix" title="確定済みストーリーを修正" run={run} onImport={importStory}/>}<section className="panel"><div className="panelhead"><h3>{editing?'story.md 下書き':'story.md 確定版'}</h3>{!editing&&doc?.exists&&<button onClick={()=>run(async()=>{setDoc(await window.batchStudio.artifact.beginEdit(project.rootPath,'story'));setEditing(true)})}>編集を開始</button>}</div><textarea className="editor" readOnly={!editing} value={doc?.content??''} onChange={e=>doc&&setDoc({...doc,content:e.target.value})}/>{editing&&<div className="actions"><button onClick={()=>doc?.content!=null&&run(async()=>setDoc(await window.batchStudio.artifact.saveDraft(project.rootPath,'story',doc.content!)))}>下書き保存</button><button className="primary" disabled={!doc?.content?.trim()} onClick={()=>run(async()=>{const saved=await window.batchStudio.artifact.saveDraft(project.rootPath,'story',doc!.content!);setDoc(saved);if(!saved.validation.valid)throw new Error('検証エラーがあるため確定できません。');setProject(await window.batchStudio.artifact.confirm(project.rootPath,'story'));await load()})}>確定</button></div>}{doc&&issuesView(doc.validation.issues)}</section></>}

function parseModelsArtifact(content:string|null):ModelsArtifact|null{if(!content)return null;try{return JSON.parse(content) as ModelsArtifact}catch{return null}}
function checkpointView(value:CheckpointSelection|null,onPick:()=>void){return <div className="base-model-row"><span>Checkpoint</span>{value?<div className="base-model-value"><strong>{value.modelName}</strong><small>{value.versionName} · {value.fileName}</small></div>:<div className="base-model-empty">未選択</div>}<button onClick={onPick}>{value?'変更':'Civitai Collectionから選択'}</button></div>}
function fileSelectionView(label:string,value:TextEncoderSelection|VaeSelection|null,onPick:()=>void){return <div className="base-model-row"><span>{label}</span>{value?<div className="base-model-value"><strong>{value.fileName}</strong><small>ComfyUI / R2 モデルファイル</small></div>:<div className="base-model-empty">未選択</div>}<button onClick={onPick}>{value?'変更':'モデルファイルから選択'}</button></div>}
function catalogLoraMatch(catalog:ModelCatalog|null,lora:LoraSelection){if(!catalog)return null;for(const collection of catalog.collections)for(const item of collection.items){if(item.modelId!==lora.modelId)continue;const rootVersion={versionId:item.versionId,files:item.files,thumbnailUrl:item.thumbnailUrl};const versions=[rootVersion,...(item.versions??[])];const version=versions.find(v=>v.versionId===lora.versionId);if(!version)continue;const file=version.files.find(f=>f.id===lora.fileId&&f.name===lora.fileName);if(file)return {collectionName:collection.name,thumbnailUrl:version.thumbnailUrl??item.thumbnailUrl??null};}return null}
function SelectedLorasPanel({models,catalog,availability}:{models:ModelsArtifact|null;catalog:ModelCatalog|null;availability:AvailabilityResult|null}){if(!models?.loras.length)return null;const availabilityByRef=new Map((availability?.rows??[]).filter(r=>r.kind==='lora').map(r=>[r.ref,r]));return <section className="panel grok-lora-summary"><div className="panelhead"><div><h3>Grok選定LoRA</h3><p>Grok返却ファイルから取り込んだLoRAと、現在の配置・Collection登録状況です。</p></div><strong>{models.loras.length}件</strong></div><div className="grok-lora-list">{models.loras.map(lora=>{const placement=availabilityByRef.get(lora.ref),catalogMatch=catalogLoraMatch(catalog,lora),local=!!placement?.local,r2=!!placement?.r2,civit=!!catalogMatch,nowhere=availability!=null&&!local&&!r2&&!civit;return <article className="grok-lora-row" key={lora.ref}><div className="grok-lora-thumb">{catalogMatch?.thumbnailUrl?<img src={catalogMatch.thumbnailUrl} alt="" loading="lazy"/>:<span>NO IMAGE</span>}</div><div className="grok-lora-copy"><strong>{lora.fileName}</strong><small>{lora.modelName} · {lora.versionName}</small>{catalogMatch&&<small>{catalogMatch.collectionName}</small>}<div className="grok-lora-indicators"><span className={`grok-lora-indicator ${local?'active local':'inactive'}`}>{local?'✓':'—'} ローカル</span><span className={`grok-lora-indicator ${r2?'active r2':'inactive'}`}>{r2?'✓':'—'} R2</span><span className={`grok-lora-indicator ${civit?'active civit':'inactive'}`}>{civit?'✓':'—'} Civitai Collection</span>{availability==null&&<span className="grok-lora-indicator checking">… 配置確認中</span>}{nowhere&&<span className="grok-lora-indicator missing">✕ いずれにもない</span>}</div></div></article>})}</div></section>}

export function ModelsStage({project,setProject,run}:{project:ProjectSummary;setProject:(p:ProjectSummary)=>void;run:Runner}){
 const [cat,setCat]=useState<CatalogStatus|null>(null),[catalog,setCatalog]=useState<ModelCatalog|null>(null),[doc,setDoc]=useState<ArtifactReadResult|null>(null),[editing,setEditing]=useState(false),[family,setFamily]=useState<ModelFamily|null>(null),[checkpoint,setCheckpoint]=useState<CheckpointSelection|null>(null),[textEncoder,setTextEncoder]=useState<TextEncoderSelection|null>(null),[vae,setVae]=useState<VaeSelection|null>(null),[picker,setPicker]=useState<'checkpoint'|'text_encoder'|'vae'|null>(null),[baseDirty,setBaseDirty]=useState(false),[migrationNeeded,setMigrationNeeded]=useState(false),[availability,setAvailability]=useState<AvailabilityResult|null>(null);
 const hydrate=(content:string|null)=>{const m=parseModelsArtifact(content);if(!m||m.schemaVersion===1)return false;setFamily(m.modelFamily??null);setCheckpoint(m.checkpoint??null);if(m.schemaVersion===4){setTextEncoder((m.textEncoder??null) as TextEncoderSelection|null);setVae((m.vae??null) as VaeSelection|null);setBaseDirty(false);setMigrationNeeded(false);return true}if(m.modelFamily==='illustrious'){setTextEncoder(null);setVae(null);setBaseDirty(false);setMigrationNeeded(false);return true}setTextEncoder(null);setVae(null);setBaseDirty(true);setMigrationNeeded(true);return true};
 const load=()=>run(async()=>{setCat(await window.batchStudio.catalog.status(project.rootPath));const nextCatalog=await window.batchStudio.catalog.snapshot();setCatalog(nextCatalog);const draft=await window.batchStudio.artifact.read(project.rootPath,'models','draft');const confirmed=draft.exists?draft:await window.batchStudio.artifact.read(project.rootPath,'models','confirmed');setDoc(confirmed);setEditing(draft.exists);if(!hydrate(confirmed.content)){const brief=await window.batchStudio.artifact.read(project.rootPath,'projectBrief','confirmed');if(brief.content)try{const b=JSON.parse(brief.content) as {generation?:{modelFamily?:ModelFamily|'Illustrious'}};const f=String(b.generation?.modelFamily??'').toLowerCase();if(f==='illustrious'||f==='anima')setFamily(f as ModelFamily)}catch{}}setAvailability(await window.batchStudio.availability.check(project.rootPath))});
 useEffect(()=>{void load()},[project.rootPath]);
 const setModelFamily=(next:ModelFamily)=>{if(next===family)return;setFamily(next);setCheckpoint(null);setTextEncoder(null);setVae(null);setMigrationNeeded(false);setBaseDirty(true)};
 const assignCheckpoint=(value:ModelSelectionBase)=>{setCheckpoint(value as CheckpointSelection);setPicker(null);setBaseDirty(true)};
 const assignFile=(role:'text_encoder'|'vae',value:TextEncoderSelection|VaeSelection)=>{if(role==='text_encoder')setTextEncoder(value as TextEncoderSelection);else setVae(value as VaeSelection);setPicker(null);setMigrationNeeded(false);setBaseDirty(true)};
 const requiredSelected=!!family&&!!checkpoint&&(family==='illustrious'||(!!textEncoder&&!!vae));
 const current=parseModelsArtifact(doc?.content??null),baseConfigured=requiredSelected&&!baseDirty&&!!current&&(current.schemaVersion===4||(current.schemaVersion>=2&&current.schemaVersion<=3&&current.modelFamily==='illustrious'));
 const saveBase=async()=>{if(!family||!checkpoint||!catalog)throw new Error('Model系統とCheckpointを選択してください。');if(family==='anima'&&(!textEncoder||!vae))throw new Error('AnimaではText EncoderとVAEの選択が必須です。');const value:any={schemaVersion:4,modelFamily:family,catalog:{schemaVersion:catalog.schemaVersion,generation:catalog.generation,generatedAt:catalog.generatedAt},checkpoint,...(family==='anima'?{textEncoder,vae}:{}),loras:[]};const saved=await window.batchStudio.artifact.saveDraft(project.rootPath,'models',JSON.stringify(value,null,2));setDoc(saved);setEditing(true);if(!saved.validation.valid)throw new Error('基盤モデルの検証に失敗しました。');const briefRead=await window.batchStudio.artifact.read(project.rootPath,'projectBrief','confirmed');if(!briefRead.content)throw new Error('project_brief.jsonがありません。');const raw=JSON.parse(briefRead.content) as ProjectBriefInput&{schemaVersion?:number};delete raw.schemaVersion;raw.generation={...raw.generation,modelFamily:family};setProject(await window.batchStudio.project.saveBrief(project.rootPath,raw));setBaseDirty(false);setMigrationNeeded(false);setAvailability(await window.batchStudio.availability.check(project.rootPath))};
 const importModels=async(raw:string)=>{const r=await window.batchStudio.artifact.importGrok(project.rootPath,'models',raw);setEditing(true);const next=await window.batchStudio.artifact.read(project.rootPath,'models','draft');setDoc(next);hydrate(next.content);setAvailability(await window.batchStudio.availability.check(project.rootPath));return r};
 return <><section className="panel"><div className="panelhead"><div><h3>使用するモデルカタログ</h3><p>Checkpoint と LoRA は Civitai Collection に登録されているモデルを対象にします。</p><p>{cat?.exists?<strong>{`登録済みモデル: ${cat.itemCount}件`}</strong>:'モデルカタログ工程でCivitai同期を実行してください。'}</p></div>{cat?.path&&<button onClick={()=>window.batchStudio.file.showInFolder(cat.path!)}>場所を開く</button>}</div>{cat?.error&&<div className="issue error">✕ {cat.error}</div>}</section>
 <section className="panel"><h3>基盤モデルを選択</h3><p className="model-selection-note">CheckpointはCivitai Collectionから選択します。AnimaではText Encoderを <code>models\text_encoders</code>、VAEを <code>models\vae</code> から選択し、R2連携時はR2上の同ディレクトリも候補へ統合します。</p>{migrationNeeded&&<div className="issue warning">既存のText Encoder / CLIP選択を検出しました。Text EncoderとVAEをローカル/R2モデルファイルから再選択してください。</div>}<div className="model-family-grid"><button className={`model-family-card ${family==='illustrious'?'active':''}`} onClick={()=>setModelFamily('illustrious')}><strong>Illustrious</strong><small>通常タグ: looking_at_viewer</small></button><button className={`model-family-card ${family==='anima'?'active':''}`} onClick={()=>setModelFamily('anima')}><strong>Anima</strong><small>通常タグ: looking at viewer</small></button></div>{family&&<div className="base-model-list">{checkpointView(checkpoint,()=>setPicker('checkpoint'))}{family==='anima'&&fileSelectionView('Text Encoder',textEncoder,()=>setPicker('text_encoder'))}{family==='anima'&&fileSelectionView('VAE',vae,()=>setPicker('vae'))}</div>}<div className="actions"><button className="primary" disabled={!catalog||!requiredSelected||!baseDirty} onClick={()=>run(saveBase)}>基盤モデルを保存</button>{baseConfigured?<span className="model-base-ready">✓ 基盤モデル確定済み — GrokはLoRAのみ選定します</span>:family&&<span className="model-base-warning">基盤モデルを保存するとLoRA選定へ進めます</span>}</div></section>
 {baseConfigured&&<GrokBridge project={project} stage="models" title="GrokでLoRAを選定" run={run} onImport={importModels}/>} {baseConfigured&&project.artifacts.find(a=>a.key==='models')?.state!=='missing'&&<GrokBridge project={project} stage="models-fix" title="LoRAを再選定" run={run} onImport={importModels}/>}<SelectedLorasPanel models={current} catalog={catalog} availability={availability}/><section className="panel"><div className="panelhead"><h3>{editing?'models.json 下書き':'models.json 確定版'}</h3></div><textarea className="editor code" readOnly value={doc?.content??''}/>{editing&&<div className="actions"><button className="primary" disabled={!doc?.content?.trim()||!doc.validation.valid} onClick={()=>run(async()=>{setProject(await window.batchStudio.artifact.confirm(project.rootPath,'models'));await load()})}>確定</button></div>}{doc&&issuesView(doc.validation.issues)}</section>
 {picker==='checkpoint'&&catalog&&<ModelPicker catalog={catalog} role="checkpoint" family={family??undefined} onSelect={assignCheckpoint} onClose={()=>setPicker(null)} onCatalogChange={next=>{setCatalog(next);void window.batchStudio.catalog.status(project.rootPath).then(setCat)}}/>}{(picker==='text_encoder'||picker==='vae')&&<ModelFilePicker project={project} role={picker} onSelect={value=>assignFile(picker,value)} onClose={()=>setPicker(null)}/>}</>;
}
