import { useMemo, useState } from 'react';
import type { CatalogCollection, CatalogItem, ModelCatalog, ModelFamily, ModelSelectionBase, ModelSelectionRole } from '../shared/types';
import { candidateVersions, roleLabel, selectionRef } from '../shared/model-selection';
import './model-selection.css';
const norm=(value:string)=>value.normalize('NFKC').toLocaleLowerCase('ja');
type BaseRole=Exclude<ModelSelectionRole,'lora'>;type Row={collection:CatalogCollection;item:CatalogItem;matches:ReturnType<typeof candidateVersions>};
export function ModelPicker({catalog,role,family,onSelect,onClose}:{catalog:ModelCatalog;role:BaseRole;family?:ModelFamily;onSelect:(selection:ModelSelectionBase)=>void;onClose:()=>void}){
  const [collectionId,setCollectionId]=useState<number|null>(null),[query,setQuery]=useState(''),[versionIds,setVersionIds]=useState<Record<number,number>>({}),[fileIds,setFileIds]=useState<Record<number,number>>({});
  const rows=useMemo(()=>{const q=norm(query.trim()),source=collectionId==null?catalog.collections:catalog.collections.filter(c=>c.id===collectionId),out:Row[]=[];for(const collection of source)for(const item of collection.items){const matches=candidateVersions(item,role,family);if(!matches.length)continue;const haystack=norm([item.modelName,item.modelType,...matches.flatMap(m=>[m.version.versionName,m.version.baseModel,...m.files.map(f=>f.name)])].filter(Boolean).join('\n'));if(!q||haystack.includes(q))out.push({collection,item,matches});}return out;},[catalog,collectionId,query,role,family]);
  const counts=useMemo(()=>new Map(catalog.collections.map(c=>[c.id,c.items.filter(item=>candidateVersions(item,role,family).length>0).length])),[catalog,role,family]);
  const choose=(row:Row)=>{const selectedVersionId=versionIds[row.item.modelId]??row.matches[0].version.versionId;const match=row.matches.find(x=>x.version.versionId===selectedVersionId)??row.matches[0];const file=match.files.find(x=>x.id===(fileIds[row.item.modelId]??match.files[0].id))??match.files[0];const modelUrl=match.version.modelUrl??row.item.modelUrl??`https://civitai.com/models/${row.item.modelId}?modelVersionId=${match.version.versionId}`;onSelect({ref:selectionRef(role),modelId:row.item.modelId,modelName:row.item.modelName,versionId:match.version.versionId,versionName:match.version.versionName,fileId:file.id,fileName:file.name,modelUrl,trainedWords:match.version.trainedWords??row.item.trainedWords??[],reason:'ユーザーがCivitai Collectionから選択'});};
  return <div className="modal model-picker-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modalcard model-picker-card"><div className="model-picker-head"><div><span className="eyebrow">CIVITAI COLLECTION</span><h2>{roleLabel(role)}を選択</h2><p>{family?`${family==='anima'?'Anima':'Illustrious'} 系統の${roleLabel(role)}候補だけを表示します。`:`${roleLabel(role)}として利用できるモデル / ファイルだけを表示します。`}</p></div><button aria-label="閉じる" onClick={onClose}>✕</button></div><div className="model-picker-toolbar"><label><span>検索</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="モデル名・Version・File名を検索"/></label><strong>{rows.length} 件</strong></div><div className="model-picker-collections"><button className={collectionId==null?'active':''} onClick={()=>setCollectionId(null)}>すべて</button>{catalog.collections.filter(c=>(counts.get(c.id)??0)>0).map(c=><button key={c.id} className={collectionId===c.id?'active':''} onClick={()=>setCollectionId(c.id)}>{c.name}<span>{counts.get(c.id)}</span></button>)}</div><div className="model-picker-list">{rows.length===0?<div className="empty-inline"><strong>{roleLabel(role)}候補がありません。</strong><p>Civitaiカタログを再同期してモデル種別を更新してください。対象外モデルを代替表示するfallbackは行いません。</p></div>:rows.map(row=>{const selectedVersionId=versionIds[row.item.modelId]??row.matches[0].version.versionId;const match=row.matches.find(x=>x.version.versionId===selectedVersionId)??row.matches[0];const fileId=fileIds[row.item.modelId]??match.files[0].id;const image=match.version.thumbnailUrl??row.item.thumbnailUrl;return <article className="model-picker-row" key={`${row.collection.id}:${row.item.modelId}`}><div className="model-picker-thumb">{image?<img src={image} alt="" loading="lazy"/>:<span>MODEL</span>}</div><div className="model-picker-copy"><div className="panelhead"><div><strong>{row.item.modelName}</strong><small>{row.item.modelType||'種別情報なし'} · {row.collection.name}</small></div>{match.version.modelUrl&&<button onClick={()=>window.batchStudio.catalog.openModel(match.version.modelUrl!)}>Civitai</button>}</div><div className="model-picker-fields"><label><span>Version</span><select value={match.version.versionId} onChange={e=>{const id=Number(e.target.value);setVersionIds(p=>({...p,[row.item.modelId]:id}));setFileIds(p=>{const next={...p};delete next[row.item.modelId];return next})}}>{row.matches.map(x=><option key={x.version.versionId} value={x.version.versionId}>{x.version.versionName}{x.version.baseModel?` · ${x.version.baseModel}`:''}</option>)}</select></label><label><span>File</span><select value={fileId} onChange={e=>setFileIds(p=>({...p,[row.item.modelId]:Number(e.target.value)}))}>{match.files.map(file=><option key={file.id} value={file.id}>{file.name}</option>)}</select></label></div></div><button className="primary model-picker-select" onClick={()=>choose(row)}>このモデルを選択</button></article>})}</div></div></div>;
}
