import { useEffect, useMemo, useState } from 'react';
import type { ModelFileCandidate, ModelFileRole, ProjectSummary, R2Object } from '../shared/types';
import { mergeModelFileCandidates, modelFileDirectory, r2ModelDirectoryPrefix } from '../shared/model-file-selection';
import { roleLabel } from '../shared/model-selection';
import './model-selection.css';

const norm=(value:string)=>value.normalize('NFKC').toLocaleLowerCase('ja');
function bytes(value?:number){if(value==null)return '';if(value<1024)return `${value} B`;if(value<1024**2)return `${(value/1024).toFixed(1)} KB`;if(value<1024**3)return `${(value/1024**2).toFixed(1)} MB`;return `${(value/1024**3).toFixed(2)} GB`;}
async function listR2Recursive(bucket:string,rootPrefix:string){const out:Array<{fileName:string;key:string;size:number}>=[],queue=[rootPrefix],seen=new Set<string>();while(queue.length){const prefix=queue.shift()!;if(seen.has(prefix))continue;seen.add(prefix);let token:string|null=null;do{const page=await window.batchStudio.r2.list(bucket,prefix,token);for(const folder of page.folders)if(folder.prefix.startsWith(rootPrefix))queue.push(folder.prefix);for(const object of page.objects as R2Object[]){if(!object.key.startsWith(rootPrefix))continue;const fileName=object.key.slice(rootPrefix.length).replace(/^\/+/, '');if(fileName)out.push({fileName,key:object.key,size:object.size})}token=page.nextToken}while(token)}return out;}

export function ModelFilePicker({project,role,onSelect,onClose}:{project:ProjectSummary;role:ModelFileRole;onSelect:(value:{ref:'text_encoder.main'|'vae.main';fileName:string;reason:string})=>void;onClose:()=>void}){
  const [files,setFiles]=useState<ModelFileCandidate[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[localPath,setLocalPath]=useState<string|null>(null),[localExists,setLocalExists]=useState(false),[r2Location,setR2Location]=useState(''),[r2Warning,setR2Warning]=useState('');
  const directory=modelFileDirectory(role),selectionRef:'text_encoder.main'|'vae.main'=role==='text_encoder'?'text_encoder.main':'vae.main';
  const load=async()=>{setLoading(true);setError('');setR2Warning('');try{const localSettings=await window.batchStudio.appSettings.get(),localDir=localSettings.modelFiles[directory];setLocalPath(localDir.path);setLocalExists(localDir.exists);const bucket=(localSettings.r2Bucket||project.meta?.settings.r2Bucket||'').trim(),modelPrefix=(localSettings.r2ModelPrefix||project.meta?.settings.r2ModelPrefix||'').trim(),prefix=r2ModelDirectoryPrefix(modelPrefix,role);let remote:Array<{fileName:string;key:string;size:number}>=[];if(bucket){setR2Location(`${bucket}/${prefix}`);const r2Settings=await window.batchStudio.r2.settings();if(r2Settings.configured||r2Settings.secretConfigured){try{remote=await listR2Recursive(bucket,prefix)}catch(e){setR2Warning(`R2を参照できませんでした: ${e instanceof Error?e.message:String(e)}`)}}else setR2Warning('R2バケットは設定されていますが、R2接続設定が完了していません。')}else setR2Location('');setFiles(mergeModelFileCandidates(localDir.files,remote));}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
  useEffect(()=>{void load()},[project.rootPath,role,project.meta?.settings.r2Bucket,project.meta?.settings.r2ModelPrefix]);
  const shown=useMemo(()=>{const q=norm(query.trim());return q?files.filter(file=>norm(file.fileName).includes(q)):files},[files,query]);
  return <div className="modal model-picker-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modalcard model-picker-card"><div className="model-picker-head"><div><span className="eyebrow">COMFYUI / R2 MODEL FILES</span><h2>{role==='vae'?'VAE':roleLabel(role)}を選択</h2><p>ローカルの <code>models\{directory}</code> と、R2連携時は同じモデルディレクトリを参照します。</p></div><div className="actions"><button disabled={loading} onClick={()=>void load()}>↻ 再読込</button><button aria-label="閉じる" onClick={onClose}>✕</button></div></div><div className="model-file-sources"><div><span>ローカル</span><code>{localPath??'ComfyUIインストール先が未設定'}</code><b className={localExists?'ok':'warn'}>{localExists?'参照中':'未検出'}</b></div>{r2Location&&<div><span>R2</span><code>{r2Location}</code><b className={r2Warning?'warn':'ok'}>{r2Warning?'確認要':'参照中'}</b></div>}</div>{r2Warning&&<div className="issue warning">{r2Warning}</div>}{error&&<div className="issue error">✕ {error}</div>}<div className="model-picker-toolbar"><label><span>検索</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ファイル名を検索"/></label><strong>{loading?'読込中…':`${shown.length} 件`}</strong></div><div className="model-picker-list">{!loading&&shown.length===0?<div className="empty-inline"><strong>{role==='vae'?'VAE':roleLabel(role)}候補がありません。</strong><p>ローカルは <code>models\{directory}</code>、R2は設定済みモデルプレフィックス配下の <code>{directory}/</code> を確認してください。</p></div>:shown.map(file=><article className="model-file-row" key={norm(file.fileName)}><div className="model-file-copy"><div className="model-file-name"><strong>{file.fileName}</strong><span className="model-source-badges">{file.local&&<span className="model-source local" title={file.localPath}>ローカル</span>}{file.r2&&<span className="model-source r2" title={file.r2Key}>R2</span>}</span></div><small>{file.local&&file.r2?`Local ${bytes(file.localSize)} · R2 ${bytes(file.r2Size)}`:file.local?bytes(file.localSize):bytes(file.r2Size)}</small></div><button className="primary model-picker-select" onClick={()=>onSelect({ref:selectionRef,fileName:file.fileName,reason:'ユーザーがComfyUI / R2モデルファイル一覧から選択'})}>このファイルを選択</button></article>)}</div></div></div>;
}
