import { useEffect, useMemo, useState } from 'react';
import type { AppSettings, AppSettingsStatus, CivitaiConnectionStatus, R2ConnectionInput, R2ConnectionStatus, VastAiConnectionInput, VastAiConnectionStatus, VastAiInstance } from '../shared/types';
import type { Runner } from './ui';

type Page='root'|'r2'|'civitai'|'cloud'|'vastai';

const EMPTY_R2:R2ConnectionInput={name:'Personal R2',accountId:'',accessKeyId:'',secretAccessKey:'',publicUrl:'',cloudflareApiToken:''};
const EMPTY_VAST:VastAiConnectionInput={apiKey:'',sshPrivateKeyPath:'',sshUser:'root',comfyUiDirectory:'/workspace/ComfyUI',comfyUiPort:18188};

function appSettingsInput(s:AppSettingsStatus):AppSettings{return {comfyUiInstallPath:s.comfyUiInstallPath,catalogPath:s.catalogPath,r2Bucket:s.r2Bucket,r2ModelPrefix:s.r2ModelPrefix,r2IndexPath:s.r2IndexPath,templatePath:s.templatePath,manifestPath:s.manifestPath};}
function statusLabel(configured:boolean,source?:'saved'|'environment'|'none'){if(!configured)return'未設定';if(source==='environment')return'環境変数を使用';return'設定済み';}
function instanceStatusLabel(status:VastAiInstance['status']){return ({running:'RUNNING',stopped:'STOPPED',starting:'STARTING',scheduling:'SCHEDULING',stopping:'STOPPING',offline:'OFFLINE',error:'ERROR',unknown:'UNKNOWN'} as const)[status];}
function formatCost(value:number|null){return value==null?'-':`$${value.toFixed(3)}/h`;}
function formatVram(value:number|null){return value==null?'-':`${Math.round(value/1024)} GB`;}

export function ServiceIntegrationsStage({run,onOpenR2,onOpenCivit}:{run:Runner;onOpenR2:()=>void;onOpenCivit:()=>void}){
  const [page,setPage]=useState<Page>('root');
  const [r2Status,setR2Status]=useState<R2ConnectionStatus|null>(null),[civitaiStatus,setCivitaiStatus]=useState<CivitaiConnectionStatus|null>(null),[vastStatus,setVastStatus]=useState<VastAiConnectionStatus|null>(null);
  const refreshStatuses=async()=>{const [r,c,v]=await Promise.all([window.batchStudio.r2.settings(),window.batchStudio.civitai.settings(),window.batchStudio.vastai.settings()]);setR2Status(r);setCivitaiStatus(c);setVastStatus(v);};
  useEffect(()=>{void refreshStatuses().catch(()=>{});},[]);
  const back=()=>setPage(page==='vastai'?'cloud':'root');
  if(page==='r2')return <R2Integration run={run} onBack={back} onOpenManager={onOpenR2} onStatus={setR2Status}/>;
  if(page==='civitai')return <CivitaiIntegration run={run} onBack={back} onOpenExplorer={onOpenCivit} onStatus={setCivitaiStatus}/>;
  if(page==='cloud')return <section className="panel service-page"><div className="service-page-head"><button onClick={back}>← サービス連携</button><div><h3>クラウドインスタンス</h3><p>リモート実行で利用するクラウドサービスを選択します。</p></div></div><div className="service-card-grid"><button className="service-card" onClick={()=>setPage('vastai')}><div><strong>Vast.ai</strong><span>GPU Cloud</span></div><b className={vastStatus?.configured?'ok':'muted'}>{statusLabel(Boolean(vastStatus?.configured),vastStatus?.source)}</b><p>Instance一覧・起動・停止と、リモート実行用SSH設定を管理します。</p></button></div></section>;
  if(page==='vastai')return <VastAiIntegration run={run} onBack={back} onStatus={setVastStatus}/>;
  return <section className="panel service-page"><div className="panelhead"><div><h3>サービス連携</h3><p>外部サービスの接続情報とクラウドリソースを、プロジェクトとは独立したアプリ共通設定として管理します。</p></div><button onClick={()=>void run(refreshStatuses)}>状態を更新</button></div><div className="service-card-grid">
    <button className="service-card" onClick={()=>setPage('r2')}><div><strong>Cloudflare R2</strong><span>Model / Artifact Storage</span></div><b className={r2Status?.configured||r2Status?.secretConfigured?'ok':'muted'}>{r2Status?.configured?'設定済み':r2Status?.secretConfigured?'環境変数を使用':'未設定'}</b><p>API Key、モデル保管先、R2 File Managerへの入口を管理します。</p></button>
    <button className="service-card" onClick={()=>setPage('civitai')}><div><strong>Civitai</strong><span>Model Catalog</span></div><b className={civitaiStatus?.configured?'ok':'muted'}>{statusLabel(Boolean(civitaiStatus?.configured),civitaiStatus?.source)}</b><p>Collection同期に使うAPI KeyとCivit Explorerへの入口を管理します。</p></button>
    <button className="service-card" onClick={()=>setPage('cloud')}><div><strong>クラウドインスタンス</strong><span>Remote Compute</span></div><b className={vastStatus?.configured?'ok':'muted'}>{vastStatus?.configured?'Vast.ai 設定済み':'未設定'}</b><p>リモート生成で利用するGPUクラウドプロバイダーを管理します。</p></button>
  </div></section>;
}

function R2Integration({run,onBack,onOpenManager,onStatus}:{run:Runner;onBack:()=>void;onOpenManager:()=>void;onStatus:(s:R2ConnectionStatus)=>void}){
  const [input,setInput]=useState<R2ConnectionInput>(EMPTY_R2),[status,setStatus]=useState<R2ConnectionStatus|null>(null),[appSettings,setAppSettings]=useState<AppSettingsStatus|null>(null);
  useEffect(()=>{let cancelled=false;void Promise.all([window.batchStudio.r2.settings(),window.batchStudio.appSettings.get()]).then(([s,a])=>{if(cancelled)return;setStatus(s);onStatus(s);setAppSettings(a);setInput({name:s.name||'Personal R2',accountId:s.accountId,accessKeyId:s.accessKeyId,secretAccessKey:'',publicUrl:s.publicUrl,cloudflareApiToken:''});}).catch(()=>{});return()=>{cancelled=true};},[]);
  const set=(key:keyof R2ConnectionInput,value:string)=>setInput(prev=>({...prev,[key]:value}));
  const save=()=>run(async()=>{const next=await window.batchStudio.r2.saveSettings(input);setStatus(next);onStatus(next);if(appSettings){const updated=await window.batchStudio.appSettings.save({...appSettingsInput(appSettings),r2Bucket:appSettings.r2Bucket,r2ModelPrefix:appSettings.r2ModelPrefix});setAppSettings(updated);}});
  return <section className="panel service-page"><div className="service-page-head"><button onClick={onBack}>← サービス連携</button><div><h3>Cloudflare R2</h3><p>モデル保管とリモート成果物転送で使用する接続設定です。SecretはOSの安全な暗号化ストレージで保護します。</p></div><b className={status?.configured||status?.secretConfigured?'ok':'muted'}>{status?.configured?'設定済み':status?.secretConfigured?'環境変数を使用':'未設定'}</b></div><div className="formgrid service-form">
    <label>接続名<input value={input.name??''} onChange={e=>set('name',e.target.value)}/></label><label>Account ID<input value={input.accountId} onChange={e=>set('accountId',e.target.value)}/></label><label>Access Key ID<input value={input.accessKeyId} onChange={e=>set('accessKeyId',e.target.value)}/></label><label>Secret Access Key<input type="password" value={input.secretAccessKey??''} onChange={e=>set('secretAccessKey',e.target.value)} placeholder={status?.secretConfigured?'保存済み / 環境変数（変更時のみ入力）':'Secret Access Key'}/></label><label className="wide">Public URL（任意）<input value={input.publicUrl??''} onChange={e=>set('publicUrl',e.target.value)} placeholder="https://..."/></label><label className="wide">Cloudflare API Token（メトリクス用・任意）<input type="password" value={input.cloudflareApiToken??''} onChange={e=>set('cloudflareApiToken',e.target.value)} placeholder={status?.metricsTokenConfigured?'保存済み（変更時のみ入力）':'任意'}/></label>
    <label>デフォルトモデルバケット<input value={appSettings?.r2Bucket??''} onChange={e=>setAppSettings(prev=>prev?{...prev,r2Bucket:e.target.value}:prev)}/></label><label>モデルプレフィックス<input value={appSettings?.r2ModelPrefix??''} onChange={e=>setAppSettings(prev=>prev?{...prev,r2ModelPrefix:e.target.value}:prev)} placeholder="例: models"/></label>
  </div><div className="actions service-actions"><button onClick={()=>void run(()=>window.batchStudio.r2.test(input))}>接続テスト</button><button className="primary" onClick={()=>void save()}>保存</button><button onClick={onOpenManager}>R2 File Managerを開く</button></div></section>;
}

function CivitaiIntegration({run,onBack,onOpenExplorer,onStatus}:{run:Runner;onBack:()=>void;onOpenExplorer:()=>void;onStatus:(s:CivitaiConnectionStatus)=>void}){
  const [status,setStatus]=useState<CivitaiConnectionStatus|null>(null),[apiKey,setApiKey]=useState('');
  useEffect(()=>{let cancelled=false;void window.batchStudio.civitai.settings().then(s=>{if(!cancelled){setStatus(s);onStatus(s)}}).catch(()=>{});return()=>{cancelled=true};},[]);
  const save=()=>run(async()=>{const next=await window.batchStudio.civitai.saveSettings({apiKey});setStatus(next);onStatus(next);setApiKey('');});
  return <section className="panel service-page"><div className="service-page-head"><button onClick={onBack}>← サービス連携</button><div><h3>Civitai</h3><p>Collectionからモデルカタログを同期するためのAPI Keyです。</p></div><b className={status?.configured?'ok':'muted'}>{statusLabel(Boolean(status?.configured),status?.source)}</b></div><div className="formgrid service-form"><label className="wide">Civitai API Key<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={status?.configured?'設定済み（変更時のみ入力）':'API Keyを入力'}/></label></div><p className="hint">環境変数: <code>CIVIT_API_KEY</code></p><div className="actions service-actions"><button className="primary" disabled={!apiKey.trim()} onClick={()=>void save()}>保存</button><button onClick={onOpenExplorer}>Civit Explorerを開く</button></div></section>;
}

function VastAiIntegration({run,onBack,onStatus}:{run:Runner;onBack:()=>void;onStatus:(s:VastAiConnectionStatus)=>void}){
  const [status,setStatus]=useState<VastAiConnectionStatus|null>(null),[input,setInput]=useState<VastAiConnectionInput>(EMPTY_VAST),[instances,setInstances]=useState<VastAiInstance[]>([]),[loadingInstances,setLoadingInstances]=useState(false);
  const configured=Boolean(status?.configured);
  const loadInstances=async()=>{setLoadingInstances(true);try{setInstances(await window.batchStudio.vastai.instances());}finally{setLoadingInstances(false);}};
  const load=async()=>{const s=await window.batchStudio.vastai.settings();setStatus(s);onStatus(s);setInput({apiKey:'',sshPrivateKeyPath:s.sshPrivateKeyPath,sshUser:s.sshUser,comfyUiDirectory:s.comfyUiDirectory,comfyUiPort:s.comfyUiPort});if(s.configured)await loadInstances();};
  useEffect(()=>{void load().catch(()=>{});},[]);
  const set=<K extends keyof VastAiConnectionInput>(key:K,value:VastAiConnectionInput[K])=>setInput(prev=>({...prev,[key]:value}));
  const save=()=>run(async()=>{const next=await window.batchStudio.vastai.saveSettings(input);setStatus(next);onStatus(next);setInput(prev=>({...prev,apiKey:''}));await loadInstances();});
  const chooseKey=()=>run(async()=>{const selected=await window.batchStudio.vastai.selectPrivateKey();if(selected)set('sshPrivateKeyPath',selected);});
  const changeState=(instance:VastAiInstance,next:'start'|'stop')=>run(async()=>{if(next==='start')await window.batchStudio.vastai.startInstance(instance.id);else await window.batchStudio.vastai.stopInstance(instance.id);await loadInstances();});
  const sorted=useMemo(()=>instances.slice().sort((a,b)=>Number(b.status==='running')-Number(a.status==='running')||b.id-a.id),[instances]);
  return <section className="panel service-page"><div className="service-page-head"><button onClick={onBack}>← クラウドインスタンス</button><div><h3>Vast.ai</h3><p>Vast.ai APIと、リモートComfyUIへ接続するためのSSH既定値を管理します。</p></div><b className={configured?'ok':'muted'}>{statusLabel(configured,status?.source)}</b></div>
    <div className="formgrid service-form"><label className="wide">Vast.ai API Key<input type="password" value={input.apiKey??''} onChange={e=>set('apiKey',e.target.value)} placeholder={configured?'設定済み（変更時のみ入力）':'API Keyを入力'}/></label><label className="wide">SSH秘密鍵<div className="actions"><input style={{flex:1}} value={input.sshPrivateKeyPath??''} readOnly placeholder="秘密鍵ファイルを選択"/><button onClick={()=>void chooseKey()}>選択</button><button disabled={!input.sshPrivateKeyPath} onClick={()=>set('sshPrivateKeyPath','')}>解除</button></div></label><label>SSH User<input value={input.sshUser??''} onChange={e=>set('sshUser',e.target.value)} placeholder="root"/></label><label>ComfyUI Port<input type="number" min={1} max={65535} value={input.comfyUiPort??18188} onChange={e=>set('comfyUiPort',Number(e.target.value))}/></label><label className="wide">Remote ComfyUI Directory<input value={input.comfyUiDirectory??''} onChange={e=>set('comfyUiDirectory',e.target.value)} placeholder="/workspace/ComfyUI"/></label></div>
    <p className="hint">API Key環境変数: <code>VASTAI_API_KEY</code>。SSHは公開Host/Port + 秘密鍵認証を前提とし、SSH Tunnelは使用しません。</p><div className="actions service-actions"><button disabled={!configured&&!input.apiKey?.trim()} onClick={()=>void run(()=>window.batchStudio.vastai.test(input))}>API接続テスト</button><button className="primary" disabled={!configured&&!input.apiKey?.trim()} onClick={()=>void save()}>保存</button></div>
    <div className="service-subsection"><div className="panelhead"><div><h4>インスタンス</h4><p>既存Instanceの状態確認・起動・停止を行います。新規作成・Destroy・Rebootはこの初期実装の対象外です。</p></div><button disabled={!configured||loadingInstances} onClick={()=>void run(loadInstances)}>{loadingInstances?'更新中…':'更新'}</button></div>{configured&&sorted.length===0&&!loadingInstances&&<p className="hint">Vast.ai Instanceがありません。</p>}{sorted.length>0&&<div className="vast-instance-table"><div className="vast-instance-row vast-instance-head"><span>ID / Label</span><span>GPU</span><span>Status</span><span>Cost</span><span>SSH</span><span>操作</span></div>{sorted.map(instance=><div className="vast-instance-row" key={instance.id}><span><b>#{instance.id}</b><small>{instance.label||'ラベルなし'}</small></span><span>{instance.gpuName??'-'}<small>{instance.gpuCount??'-'} GPU / {formatVram(instance.gpuRamMb)}</small></span><span><b className={`vast-status vast-status-${instance.status}`}>{instanceStatusLabel(instance.status)}</b><small>{instance.statusMessage??instance.rawStatus}</small></span><span>{formatCost(instance.hourlyCost)}</span><span>{instance.sshHost&&instance.sshPort?<code>{instance.sshHost}:{instance.sshPort}</code>:'-'}</span><span className="actions">{instance.status==='running'?<button onClick={()=>void changeState(instance,'stop')}>停止</button>:instance.status==='stopped'?<button onClick={()=>void changeState(instance,'start')}>起動</button>:<button disabled>操作待ち</button>}</span></div>)}</div>}</div>
  </section>;
}
